/* Auto-generated by tools/m2c_batch.py */
/* Address range: 0x801BA854 – 0x801BEF40 */
#include "nonmatch.h"

/* --- auto_fn_801BA854_text.s --- */
u32 fn_8030C210(s32, void *, void *);                 /* extern */
extern void *lbl_8053AB10;

void fn_801BA854(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    if ((s32) (*(u32*)((char*)(arg0)+0x248)) != 0) {
        fn_8030C210((*(u32*)((char*)(lbl_8053AB10)+0x24)), arg0 + 0xC, lbl_8053AB10);
    }
}

/* --- auto_fn_801BA88C_text.s --- */
s32 fn_801F15BC(s32, s32, s32);                     /* extern */
u16 fn_8022461C(s32);                               /* extern */

s32 fn_801BA88C(s32 arg0, s32 arg1, s32 arg2) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    if (fn_8022461C(arg2) == 0xD) {
        return 0;
    }
    return fn_801F15BC(arg0, arg1, arg2);
}

/* --- auto_fn_801BA8F8_text.s --- */
s32 fn_800C3638(void *, s32, f32);                  /* extern */
u32 fn_801BACE8(void *, u32);                           /* extern */
u32 fn_801CD950(void *, f32);                         /* extern */
u8 fn_801CECF4(void *, u32, f32, f32);                /* extern */
s32 fn_801D05F8(void *, void *, f32);               /* extern */
u8 fn_801D217C(void *);                             /* extern */
u8 fn_801D21F0(void *);                             /* extern */
u32 fn_801F0E34(void *, u32, u32);                        /* extern */
extern f32 lbl_8053EBB0;
extern f32 lbl_8053EBB4;
extern f32 lbl_8053EBB8;
extern f32 lbl_8053EBBC;
extern f32 lbl_8053EBC0;
extern f32 lbl_8053EBC4;
extern f32 lbl_8053EBC8;
extern f32 lbl_8053EBCC;
extern f32 lbl_8053EBD0;

void fn_801BA8F8(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 temp_r0;
    s32 temp_r0_2;
    s32 temp_r4;

    temp_r0 = (*(u32*)((char*)(arg0)+0x248));
    switch (temp_r0) {                              /* irregular */
    case 0:
        if ((u32) ((*(u32*)((char*)(arg0)+0x1A0)) + 0xB3AC0000) == 0x5A52U) {
            (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053EBB4;
            (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053EBB4;
            (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053EBB8;
            (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053EBB8;
            (*(u32*)((char*)(arg0)+0x70)) = (f32) (*(u32*)((char*)(arg0)+0x60));
            (*(u32*)((char*)(arg0)+0x74)) = (f32) (*(u32*)((char*)(arg0)+0x64));
            (*(u32*)((char*)(arg0)+0x78)) = (f32) (*(u32*)((char*)(arg0)+0x68));
            (*(u32*)((char*)(arg0)+0x7C)) = (f32) (*(u32*)((char*)(arg0)+0x6C));
        }
        ((u32(*)())(*(void**)((char*)(unk0)+0xA8)))(arg0);
        if (((s32) (*(u32*)((char*)(arg0)+0x24C)) >= (s32) (*(u32*)((char*)(arg0)+0x250))) && (fn_801D05F8(arg0, arg0 + 0xC, lbl_8053EBBC) >= 0)) {
            fn_801BACE8(arg0, 1);
        }
        break;
    case 1:
        fn_801F0E34((void *)0x4006F, 0);
        if ((u32) ((*(u32*)((char*)(arg0)+0x1A0)) + 0xB3AC0000) == 0x5A52U) {
            (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053EBB4;
            (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053EBB4;
            (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053EBB8;
            (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053EBB8;
            (*(u32*)((char*)(arg0)+0x70)) = (f32) (*(u32*)((char*)(arg0)+0x60));
            (*(u32*)((char*)(arg0)+0x74)) = (f32) (*(u32*)((char*)(arg0)+0x64));
            (*(u32*)((char*)(arg0)+0x78)) = (f32) (*(u32*)((char*)(arg0)+0x68));
            (*(u32*)((char*)(arg0)+0x7C)) = (f32) (*(u32*)((char*)(arg0)+0x6C));
        }
        ((u32(*)())(*(void**)((char*)(unk0)+0xA8)))(arg0);
        if (lbl_8053EBC0 != (*(u32*)((char*)(arg0)+0x54))) {
            fn_801CD950(arg0 + 0x54, lbl_8053EBC4);
            (*(u32*)((char*)(arg0)+0x58)) = (f32) (*(u32*)((char*)(arg0)+0x54));
            (*(u32*)((char*)(arg0)+0x5C)) = (f32) (*(u32*)((char*)(arg0)+0x54));
        } else if (((s32) (*(u32*)((char*)(arg0)+0x24C)) >= (s32) (*(u32*)((char*)(arg0)+0x250))) && (fn_801D217C(arg0 + 0x270) != 0)) {
            fn_801BACE8(arg0, 2);
            ((u32(*)())(*(void**)((char*)(unk0)+0xB0)))(arg0);
        }
        break;
    case 2:
        if (((s32) (*(u32*)((char*)(arg0)+0x24C)) > 1) && (fn_801D21F0(arg0 + 0x270) != 0)) {
            fn_801BACE8(arg0, 3);
        }
        break;
    case 3:
        if (((s32) (*(u32*)((char*)(arg0)+0x24C)) >= (s32) (*(u32*)((char*)(arg0)+0x250))) && (fn_801D217C(arg0 + 0x270) != 0)) {
            fn_801BACE8(arg0, 4);
        }
        break;
    case 4:
        if ((s32) (*(u32*)((char*)(arg0)+0x24C)) > 1) {
            if ((u32) ((*(u32*)((char*)(arg0)+0x1A0)) + 0xA5B10000) == 0x5241U) {
                temp_r4 = (*(u32*)((char*)(arg0)+0x27C));
                if ((fn_800C3638(arg0 + 0x294, temp_r4, (f32) (temp_r4 - 2)) != 0) && (fn_801CECF4(arg0, 0x5A4F5348, lbl_8053EBC0, lbl_8053EBBC) != 0)) {
                    fn_801F0E34(arg0, 0x50030, 0);
                }
            }
            if (fn_801D21F0(arg0 + 0x270) != 0) {
                fn_801BACE8(arg0, 5);
            }
        }
        break;
    case 5:
        if ((u32) ((*(u32*)((char*)(arg0)+0x1A0)) + 0xB3AC0000) == 0x5A52U) {
            (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053EBB4;
            (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053EBB4;
            (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053EBB8;
            (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053EBB8;
            (*(u32*)((char*)(arg0)+0x70)) = (f32) (*(u32*)((char*)(arg0)+0x60));
            (*(u32*)((char*)(arg0)+0x74)) = (f32) (*(u32*)((char*)(arg0)+0x64));
            (*(u32*)((char*)(arg0)+0x78)) = (f32) (*(u32*)((char*)(arg0)+0x68));
            (*(u32*)((char*)(arg0)+0x7C)) = (f32) (*(u32*)((char*)(arg0)+0x6C));
        }
        if (((s32) (*(u32*)((char*)(arg0)+0x24C)) > 1) && (fn_801D21F0(arg0 + 0x270) != 0)) {
            fn_801BACE8(arg0, 0);
        }
        break;
    }
    ((u32(*)())(*(void**)((char*)(unk0)+0xAC)))(arg0);
    temp_r0_2 = (*(u32*)((char*)(arg0)+0x248));
    if (temp_r0_2 != 5) {
        if ((temp_r0_2 < 5) && (temp_r0_2 < 3)) {
            if (temp_r0_2 < 0) {
                goto block_45;
            }
            goto block_44;
        }
block_45:
        (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053EBCC;
        (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053EBCC;
        (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053EBD0;
        (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053EBD0;
        (*(u32*)((char*)(arg0)+0x70)) = (f32) (*(u32*)((char*)(arg0)+0x60));
        (*(u32*)((char*)(arg0)+0x74)) = (f32) (*(u32*)((char*)(arg0)+0x64));
        (*(u32*)((char*)(arg0)+0x78)) = (f32) (*(u32*)((char*)(arg0)+0x68));
        (*(u32*)((char*)(arg0)+0x7C)) = (f32) (*(u32*)((char*)(arg0)+0x6C));
        return;
    }
block_44:
    (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053EBB0;
    (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053EBB0;
    (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053EBC8;
    (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053EBC8;
    (*(u32*)((char*)(arg0)+0x70)) = (f32) (*(u32*)((char*)(arg0)+0x60));
    (*(u32*)((char*)(arg0)+0x74)) = (f32) (*(u32*)((char*)(arg0)+0x64));
    (*(u32*)((char*)(arg0)+0x78)) = (f32) (*(u32*)((char*)(arg0)+0x68));
    (*(u32*)((char*)(arg0)+0x7C)) = (f32) (*(u32*)((char*)(arg0)+0x6C));
}

/* --- auto_fn_801BACE8_text.s --- */
u32 fn_80066FFC(char *, char *, u32, u32, u32);                   /* extern */
s32 fn_8013CC50(s32, void *, u32, u32, u32, u32, u32, u32, f32); /* extern */
s32 fn_801CD664(s32, f32);                          /* extern */
u32 fn_801D22A0(void *, u32, u32);                        /* extern */
u32 fn_801D22DC(void *, u32, u32, u32, s32, f32);           /* extern */
u32 fn_801EE434(s32);                                 /* extern */


void fn_801BB1A8(void);
extern f32 lbl_8053EBAC;




extern f32 lbl_8053EBE0;

/* Warning: Gap in callee-saved word stack region.
 * Saved: [0x1e38, 0x1e3c, 0x1e40, 0x1e44, 0x1e48, 0x1e4c, 0x1e50, 0x1e54, 0x1e58, 0x1e5c, 0x1e60, 0x1e64, 0x1e70, 0x1e74, 0x1e80, 0x1e84], gap at: 0x1e68. */
void fn_801BACE8(void *arg0, s32 arg1) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    u32 sp24;
    u32 sp20;
    f32 sp1C;
    f32 sp18;
    f32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    char *var_r25;
    char *var_r26;
    f32 temp_f0;
    f32 temp_f1;
    f32 temp_f2;
    f32 temp_f30;
    f32 temp_f3;
    s32 temp_r0;
    s32 temp_r24;
    s32 temp_r7;
    s32 var_r22;
    s32 var_r27;
    s32 var_r28;
    u32 temp_r23;

    M2C_ERROR(/* unknown instruction: psq_stx $f31, $r1, $r0, 0x0, qr0 */);
    M2C_ERROR(/* unknown instruction: psq_stx $f30, $r1, $r0, 0x0, qr0 */);
    M2C_ERROR(/* unknown instruction: psq_stx $f29, $r1, $r0, 0x0, qr0 */);
    switch (arg1) {                                 /* irregular */
    case 0:
        (*(u32*)((char*)(arg0)+0x250)) = (s32) (fn_801CD664(0x79) + 0x3C);
        (*(u32*)((char*)(arg0)+0x54)) = (f32) lbl_8053EBAC;
        (*(u32*)((char*)(arg0)+0x58)) = (f32) lbl_8053EBAC;
        (*(u32*)((char*)(arg0)+0x5C)) = (f32) lbl_8053EBAC;
        break;
    case 1:
        (*(u32*)((char*)(arg0)+0x250)) = (s32) (fn_801CD664(0x79) + 0x3C);
        fn_801D22DC(arg0 + 0x270, 0, 2, 0);
        if ((u32) ((*(u32*)((char*)(arg0)+0x1A0)) + 0xA5B10000) == 0x5241U) {
            temp_r23 = (*(u32*)((char*)(arg0)+0x90));
            sp10 = (*(u32*)((char*)(arg0)+0x2C));
            if (temp_r23 != 0U) {
                var_r28 = 0;
                fn_80066FFC(&sp20, &fn_801BB1A8, 0, 8, 0x3C1);
                var_r22 = -(s32) temp_r23;
                temp_f30 = lbl_8053EBE0;
                temp_r24 = var_r22;
                var_r25 = &sp20;
loop_19:
                if (var_r22 <= (s32) temp_r23) {
                    var_r27 = temp_r24;
                    var_r26 = var_r25;
loop_17:
                    if (var_r27 <= (s32) temp_r23) {
                        temp_f0 = (*(u32*)((char*)(arg0)+0x24));
                        temp_f1 = temp_f0 + (temp_f30 * (f32) var_r22);
                        sp14 = temp_f0;
                        temp_f3 = (*(u32*)((char*)(arg0)+0x28));
                        sp18 = temp_f3;
                        temp_f2 = (*(u32*)((char*)(arg0)+0x2C));
                        sp1C = temp_f2;
                        sp14 = temp_f1;
                        sp18 = (temp_f30 * (f32) var_r27) + temp_f3;
                        if (fn_8022461C(&sp14, (*(u32*)((char*)(arg0)+0x4)), temp_f1, temp_f2, temp_f3) == 0xD) {
                            (*(u32*)((char*)(var_r26)+0x0)) = var_r22;
                            var_r25 += 8;
                            var_r28 += 1;
                            (*(u32*)((char*)(var_r26)+0x4)) = var_r27;
                            var_r26 += 8;
                        }
                        var_r27 += 1;
                        goto loop_17;
                    }
                    var_r22 += 1;
                    goto loop_19;
                }
                if (var_r28 > 0) {
                    temp_r0 = fn_801CD664(var_r28) * 8;
                    sp8 += lbl_8053EBE0 * (f32) *(&sp20 + temp_r0);
                    spC += lbl_8053EBE0 * (f32) *(&sp24 + temp_r0);
                }
            }
            (*(u32*)((char*)(arg0)+0x14)) = sp10;
            (*(u32*)((char*)(arg0)+0x20)) = sp10;
        }
        (*(u32*)((char*)(arg0)+0x54)) = (f32) lbl_8053EBAC;
        (*(u32*)((char*)(arg0)+0x58)) = (f32) lbl_8053EBAC;
        (*(u32*)((char*)(arg0)+0x5C)) = (f32) lbl_8053EBAC;
        (*(u32*)((char*)(arg0)+0x2A8)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x555, -1, 0, 0, 0, 1, lbl_8053EBB0);
        break;
    case 2:
        (*(u32*)((char*)(arg0)+0x250)) = -1;
        fn_801D22DC(arg0 + 0x270, 1, 0, 0);
        fn_801EE434((*(u32*)((char*)(arg0)+0x2A8)));
        (*(u32*)((char*)(arg0)+0x2A8)) = 0;
        fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x15B, 0, 1, 0, 0, 1, lbl_8053EBB0);
        fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x15C, -1, 0, 0, 0, 1, lbl_8053EBB0);
        fn_801F0E34(arg0, 0x40050, 0);
        break;
    case 3:
        (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053EBCC;
        (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053EBCC;
        (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053EBD0;
        (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053EBD0;
        (*(u32*)((char*)(arg0)+0x70)) = (f32) (*(u32*)((char*)(arg0)+0x60));
        (*(u32*)((char*)(arg0)+0x74)) = (f32) (*(u32*)((char*)(arg0)+0x64));
        (*(u32*)((char*)(arg0)+0x78)) = (f32) (*(u32*)((char*)(arg0)+0x68));
        (*(u32*)((char*)(arg0)+0x7C)) = (f32) (*(u32*)((char*)(arg0)+0x6C));
        (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) & 0xFFFFFEFF);
        (*(u32*)((char*)(arg0)+0x250)) = (s32) (fn_801CD664(0x29, lbl_8053EBCC) + 0x28);
        fn_801D22A0(arg0 + 0x270, 2, 2);
        break;
    case 4:
        (*(u32*)((char*)(arg0)+0x250)) = -1;
        fn_801D22DC(arg0 + 0x270, 3, 0, 0);
        break;
    case 5:
        ((u32(*)())(*(void**)((char*)(unk0)+0xA4)))();
        (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053EBB0;
        (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053EBB0;
        (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053EBC8;
        (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053EBC8;
        (*(u32*)((char*)(arg0)+0x70)) = (f32) (*(u32*)((char*)(arg0)+0x60));
        (*(u32*)((char*)(arg0)+0x74)) = (f32) (*(u32*)((char*)(arg0)+0x64));
        (*(u32*)((char*)(arg0)+0x78)) = (f32) (*(u32*)((char*)(arg0)+0x68));
        (*(u32*)((char*)(arg0)+0x7C)) = (f32) (*(u32*)((char*)(arg0)+0x6C));
        temp_r7 = (*(u32*)((char*)(arg0)+0x230)) | 0x100;
        (*(u32*)((char*)(arg0)+0x230)) = temp_r7;
        (*(u32*)((char*)(arg0)+0x250)) = -1;
        fn_801D22DC(arg0 + 0x270, 4, 0, 0, temp_r7, lbl_8053EBB0);
        fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x15B, 0, 1, 0, 0, 1, lbl_8053EBB0);
        fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x15C, -1, 0, 0, 0, 1, lbl_8053EBB0);
        fn_801F0E34(arg0, 0x50032, 0);
        break;
    }
    (*(u32*)((char*)(arg0)+0x24C)) = 0;
    (*(u32*)((char*)(arg0)+0x248)) = arg1;
    M2C_ERROR(/* unknown instruction: psq_lx $f31, $r1, $r0, 0x0, qr0 */);
    M2C_ERROR(/* unknown instruction: psq_lx $f30, $r1, $r0, 0x0, qr0 */);
    M2C_ERROR(/* unknown instruction: psq_lx $f29, $r1, $r0, 0x0, qr0 */);
}

/* --- auto_03_801BB1A8_text.s --- */
void fn_801BB1A8(void) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;

}

/* --- auto_fn_801BB1AC_text.s --- */

u32 fn_801D0E58(void *);                              /* extern */
u32 fn_801D0ED0();                                    /* extern */
u32 fn_801D1D60(void *);                              /* extern */

u32 fn_801D2608(void *, char *, u32);                      /* extern */
extern char lbl_804A3D68;



extern f32 lbl_8053EBE4;
extern f32 lbl_8053EBE8;

void fn_801BB1AC(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 temp_r4;
    u32 var_r0;

    fn_801D0ED0();
    fn_801D0E58(arg0);
    (*(u32*)((char*)(arg0)+0x98)) = 2;
    (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053EBB0;
    (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053EBB0;
    (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053EBC8;
    (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053EBC8;
    (*(u32*)((char*)(arg0)+0x70)) = (f32) (*(u32*)((char*)(arg0)+0x60));
    (*(u32*)((char*)(arg0)+0x74)) = (f32) (*(u32*)((char*)(arg0)+0x64));
    (*(u32*)((char*)(arg0)+0x78)) = (f32) (*(u32*)((char*)(arg0)+0x68));
    (*(u32*)((char*)(arg0)+0x7C)) = (f32) (*(u32*)((char*)(arg0)+0x6C));
    (*(u32*)((char*)(arg0)+0x80)) = (f32) lbl_8053EBE4;
    (*(u32*)((char*)(arg0)+0x84)) = (f32) lbl_8053EBE4;
    (*(u32*)((char*)(arg0)+0x88)) = (f32) lbl_8053EBE8;
    (*(u32*)((char*)(arg0)+0x8C)) = (f32) lbl_8053EBE8;
    if ((u32) ((*(u32*)((char*)(arg0)+0x1A0)) + 0xB3AC0000) == 0x5A52U) {
        (*(u32*)((char*)(arg0)+0xB0)) = 0;
    } else {
        (*(u32*)((char*)(arg0)+0xB0)) = 0x10101;
    }
    temp_r4 = (*(u32*)((char*)(arg0)+0x230)) | 0x100;
    (*(u32*)((char*)(arg0)+0x230)) = temp_r4;
    (*(u32*)((char*)(arg0)+0x54)) = (f32) lbl_8053EBAC;
    (*(u32*)((char*)(arg0)+0x58)) = (f32) lbl_8053EBAC;
    (*(u32*)((char*)(arg0)+0x5C)) = (f32) lbl_8053EBAC;
    (*(u32*)((char*)(arg0)+0x248)) = 0;
    (*(u32*)((char*)(arg0)+0x24C)) = 0;
    (*(u32*)((char*)(arg0)+0x250)) = (s32) (fn_801CD664(0x79, temp_r4) + 0x3C);
    (*(u32*)((char*)(arg0)+0x254)) = (f32) lbl_8053EBAC;
    (*(u32*)((char*)(arg0)+0x258)) = (f32) lbl_8053EBAC;
    fn_801D2608(arg0 + 0x270, &lbl_804A3D68, 5);
    fn_801D22DC(arg0 + 0x270, 0, 2, 0);
    fn_801D1D60(arg0 + 0x270);
    var_r0 = (*(u32*)((char*)(arg0)+0x90));
    if (var_r0 > 0xFU) {
        var_r0 = 0xFU;
    } else if (var_r0 < 0U) {
        var_r0 = 0U;
    }
    (*(u32*)((char*)(arg0)+0x90)) = var_r0;
    ((u32(*)())(*(void**)((char*)(unk0)+0xA4)))(arg0);
}

/* --- auto_fn_801BB30C_text.s --- */
u32 dtor_80084580(void *);                            /* extern */
u32 dtor_801F593C(void *, u32);                         /* extern */

extern char lbl_8049CC34;
extern char lbl_804A3D7C;
extern char lbl_804A4808;

void *fn_801BB30C(void *arg0, s16 arg1) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    if (arg0 != NULL) {
        (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A3D7C;
        fn_801EE434((*(u32*)((char*)(arg0)+0x2A8)));
        (*(u32*)((char*)(arg0)+0x2A8)) = 0;
        if (arg0 != NULL) {
            (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A4808;
            if (((arg0 + 0x270) != NULL) && ((arg0 + 0x294) != NULL)) {
                (*(u32*)((char*)(arg0)+0x294)) = (u32)&lbl_8049CC34;
            }
            dtor_801F593C(arg0, 0);
        }
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_801BB3B0_text.s --- */
u32 fn_801D0F40();                                    /* extern */


void *fn_801BB3B0(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    fn_801D0F40();
    (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A3D7C;
    (*(u32*)((char*)(arg0)+0x2A8)) = 0;
    return arg0;
}

/* --- auto_fn_801BB3F4_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */
u32 fn_80028974(char *);                                 /* extern */
void fn_80021A6C();
void fn_80021AC0();
void fn_80021B14();
void fn_80021B68();
void fn_80021BBC();
void fn_80021C10();
void fn_80021C64();
void fn_80021CB8();
void fn_80021D0C();
extern char lbl_804B21AC;
extern char lbl_804B21BC;
extern char lbl_804B21CC;
extern char lbl_804B21DC;
extern char lbl_804B21EC;
extern char lbl_804B21FC;
extern char lbl_804B220C;
extern char lbl_804B221C;
extern char lbl_804B222C;
extern char lbl_804C7770;
extern u8 lbl_8053A2AC;
extern u8 lbl_8053A2AD;
extern u8 lbl_8053A2AE;
extern u8 lbl_8053A2AF;
extern u8 lbl_8053A2B0;
extern u8 lbl_8053A2B1;
extern u8 lbl_8053A2B2;
extern u8 lbl_8053A2B3;
extern u8 lbl_8053A2B4;

void fn_801BB3F4(void) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804C7770);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804C7770 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804C7770 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804C7770 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804C7770 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804C7770 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804C7770 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804C7770 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804C7770 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_801BB618_text.s --- */
u32 fn_801F02BC(char *, s32, char *, u32, u32, u32, f32, f32);    /* extern */
extern char lbl_804693C4;
extern f32 lbl_8053EC00;
extern f32 lbl_8053EC04;
extern f32 lbl_8053EC08;
extern f32 lbl_8053EC0C;
extern f32 lbl_8053EC10;

void fn_801BB618(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 sp40;
    s32 sp3C;
    s32 sp38;
    s8 sp36;
    s8 sp35;
    s8 sp34;
    s32 sp30;
    s8 sp2E;
    s8 sp2D;
    s8 sp2C;
    s8 sp2B;
    s8 sp2A;
    s8 sp29;
    s8 sp28;
    s8 sp27;
    s8 sp26;
    s8 sp25;
    s8 sp24;
    s32 sp20;
    s32 sp1C;
    s32 sp18;
    u32 sp8;
    f32 var_f1;
    s32 temp_r0;
    s32 temp_r0_3;
    s8 var_r0;
    u8 temp_r0_2;
    u8 temp_r4;
    u8 temp_r4_2;
    u8 temp_r5;
    u8 temp_r5_2;
    u8 temp_r6;
    u8 temp_r6_2;
    u8 temp_r7;
    u8 temp_r8;
    u8 temp_r9;
    u8 var_r11;

    temp_r0 = (*(u32*)((char*)(arg0)+0x248));
    if (temp_r0 != 9) {
        if (temp_r0 < 9) {
            if (temp_r0 != 0) {
                goto block_5;
            }
        } else {
block_5:
            sp18 = -1;
            var_r11 = 0;
            sp1C = -1;
loop_7:
            if (var_r11 < 0x10U) {
                temp_r8 = var_r11 + 5;
                temp_r6 = var_r11 + 1;
                *(&sp8 + var_r11) = var_r11;
                temp_r4 = var_r11 + 2;
                *(&sp8 + temp_r6) = temp_r6;
                temp_r5 = var_r11 + 3;
                temp_r9 = var_r11 + 4;
                *(&sp8 + temp_r4) = temp_r4;
                temp_r7 = temp_r8;
                temp_r6_2 = var_r11 + 6;
                *(&sp8 + temp_r5) = temp_r5;
                temp_r4_2 = var_r11 + 7;
                temp_r5_2 = temp_r6_2;
                *(&sp8 + temp_r9) = temp_r9;
                temp_r0_2 = temp_r4_2;
                var_r11 += 8;
                *(&sp8 + temp_r7) = temp_r8;
                *(&sp8 + temp_r5_2) = temp_r6_2;
                *(&sp8 + temp_r0_2) = temp_r4_2;
                goto loop_7;
            }
            sp18 = -1;
            sp1C = 0;
            sp20 = 0;
            sp24 = 0;
            sp25 = 0;
            sp26 = 0;
            sp27 = 1;
            sp28 = 1;
            sp29 = 0;
            sp2A = 0;
            sp2B = 0;
            sp2C = 0;
            sp2D = 0;
            sp2E = 1;
            sp30 = 3;
            sp34 = 1;
            sp35 = 0;
            sp36 = 0;
            sp38 = -1;
            sp3C = 0;
            sp40 = 2;
            temp_r0_3 = (*(u32*)((char*)(arg0)+0x248));
            if (temp_r0_3 < 7) {
                if (temp_r0_3 != 0) {
                    goto block_16;
                }
                goto block_14;
            }
            if (temp_r0_3 != 9) {
                if (temp_r0_3 < 9) {
                    var_r0 = -1;
                } else {
block_16:
                    var_f1 = ((*(u32*)((char*)(arg0)+0x14)) - lbl_8053EC00) * lbl_8053EC04;
                    if (var_f1 > lbl_8053EC08) {
                        var_f1 = lbl_8053EC08;
                    } else if (var_f1 < lbl_8053EC0C) {
                        var_f1 = lbl_8053EC0C;
                    }
                    var_r0 = (s8) (lbl_8053EC10 * var_f1);
                }
            } else {
block_14:
                var_r0 = 0;
            }
            unksp1B = var_r0;
            fn_801F02BC(&lbl_804693C4, (*(u32*)((char*)(arg0)+0x280)) + 0x8A, &sp8, 0x407, 0, 0, lbl_8053EC08, lbl_8053EC08);
        }
    }
}

/* --- auto_fn_801BB7F4_text.s --- */

extern void *lbl_8053AB10;

void fn_801BB7F4(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 temp_r0;

    temp_r0 = (*(u32*)((char*)(arg0)+0x248));
    if (temp_r0 != 5) {
        if (temp_r0 < 5) {
            if (temp_r0 < 2) {
                return;
            }
            goto block_5;
        }
        if (temp_r0 < 9) {
block_5:
            fn_8030C210((*(u32*)((char*)(lbl_8053AB10)+0x24)), arg0 + 0xC, lbl_8053AB10);
        }
    }
}

/* --- auto_fn_801BB844_text.s --- */
u32 fn_801CE9F8(void *);                              /* extern */
u32 fn_801CEA60(void *);                              /* extern */
s32 fn_802D6A9C();                                  /* extern */
extern f32 lbl_8053EC14;

void fn_801BB844(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 temp_r31;

    temp_r31 = (*(u32*)((char*)(arg0)+0x4));
    if (((u8) (*(u32*)((char*)((fn_802D6A9C() + 0x10000 + temp_r31))+0x31DF)) == 0) && ((*(u32*)((char*)(arg0)+0x14)) > lbl_8053EC14)) {
        fn_801CEA60(arg0);
        return;
    }
    fn_801CE9F8(arg0);
}

/* --- auto_fn_801BB8B4_text.s --- */
u8 fn_8022DCD8();                                   /* extern */
u8 fn_8022DD74(s32);                                /* extern */

void fn_801BB8B4(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    if (((s32) (*(u32*)((char*)(arg0)+0x2B8)) >= 0) && (fn_8022DCD8() != 0)) {
        if (fn_8022DD74((*(u32*)((char*)(arg0)+0x2B8))) == 0) {
            (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) | 0x8000);
            (*(u32*)((char*)(arg0)+0x2C4)) = (s32) (*(u32*)((char*)(arg0)+0x2B8));
        }
        (*(u32*)((char*)(arg0)+0x2B8)) = -1;
    }
}

/* --- auto_fn_801BB920_text.s --- */
/*
Decompilation failure in function fn_801BB920:

Found bctr instruction at auto_fn_801BB920_text.s line 58, but the corresponding jump table is not provided.

Please include it in the input .s file(s), or in an additional file.

*/

/* --- auto_fn_801BBA0C_text.s --- */
/*
Decompilation failure in function fn_801BBA0C:

Found bctr instruction at auto_fn_801BBA0C_text.s line 56, but the corresponding jump table is not provided.

Please include it in the input .s file(s), or in an additional file.

*/

/* --- auto_fn_801BC244_text.s --- */
u32 fn_801BC554(void *, u32);                           /* extern */


void *fn_801F1184(void *);                          /* extern */


u32 fn_80236074(s32, u32, u32);                           /* extern */
s32 fn_80236228(s32);                               /* extern */
u32 fn_8023DFF4(s32, f32 *, f32, f32);                /* extern */
f32 *fn_8023E724(s32, f32, f32);                    /* extern */





extern f32 lbl_8053EC30;
extern f32 lbl_8053EC58;
extern f64 lbl_8053EC60;

void fn_801BC244(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    f32 temp_f1_2;
    f32 temp_f1_3;
    f32 temp_f1_4;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f30;
    f32 temp_f31;
    f32 var_f1;
    s32 temp_r0;
    s32 temp_r0_2;
    s32 temp_r0_3;
    s32 temp_r0_4;
    s32 temp_r3;
    s32 temp_r5;
    s32 var_r30;
    u8 var_r3;
    u8 var_r3_2;

    temp_r0 = (*(u32*)((char*)(arg0)+0x248));
    if (temp_r0 < 3) {
        if (temp_r0 < 1) {

        } else {
            if (temp_r0 < 7) {
                if (temp_r0 != 0) {
                    goto block_11;
                }
                goto block_9;
            }
            if (temp_r0 != 9) {
                if (temp_r0 < 9) {
                    var_r30 = 0xFF;
                } else {
block_11:
                    var_f1 = ((*(u32*)((char*)(arg0)+0x14)) - lbl_8053EC00) * lbl_8053EC04;
                    if (var_f1 > lbl_8053EC08) {
                        var_f1 = lbl_8053EC08;
                    } else if (var_f1 < lbl_8053EC0C) {
                        var_f1 = lbl_8053EC0C;
                    }
                    var_r30 = (s32) (lbl_8053EC10 * var_f1);
                }
            } else {
block_9:
                var_r30 = 0;
            }
            temp_f1 = (f32) (u8) var_r30;
            fn_801F1184(*(u32*)((char*)((arg0))+0x4C)) = (f32) (temp_f1 / lbl_8053EC10);
            fn_801F0E34(arg0, 0x400A3, 0, temp_f1);
        }
    }
    temp_r0_2 = (*(u32*)((char*)(arg0)+0x248));
    if (temp_r0_2 < 3) {
        if (temp_r0_2 < 1) {

        } else {
            temp_r5 = (*(u32*)((char*)(arg0)+0x2BC));
            (*(u32*)((char*)(arg0)+0x2BC)) = (s32) (temp_r5 + 1);
            temp_r3 = fn_801D05F8(arg0, arg0 + 0xC, temp_r5, lbl_8053EC0C);
            if (temp_r3 != (s32) (*(u32*)((char*)(arg0)+0x2B8))) {
                if (temp_r3 < 0) {
                    if (((s32) (*(u32*)((char*)(arg0)+0x248)) != 1) || ((s32) (*(u32*)((char*)(arg0)+0x24C)) >= 0x3C)) {
                        fn_801BC554(arg0, 5);
                    }
                } else if ((s32) (*(u32*)((char*)(arg0)+0x2BC)) >= 0x2D) {
                    (*(u32*)((char*)(arg0)+0x2B8)) = temp_r3;
                    (*(u32*)((char*)(arg0)+0x2BC)) = 0;
                }
            }
        }
    }
    temp_r0_3 = (*(u32*)((char*)(arg0)+0x248));
    var_r3 = 0;
    if (temp_r0_3 != 5) {
        if (temp_r0_3 < 5) {
            if (temp_r0_3 < 4) {

            } else {
                goto block_32;
            }
        } else if (temp_r0_3 < 9) {
block_32:
            var_r3 = 1;
        }
    }
    if (var_r3 != 0) {
        if (fn_8022DCD8((*(u32*)((char*)(arg0)+0x2B8))) == 0) {
            fn_801BC554(arg0, 5);
        } else {
            temp_f2 = fn_8023E724(*(u32*)((char*)(((*(u32*)((char*)(arg0)+0x2B8))))+0x8));
            temp_f1_2 = (*(u32*)((char*)(arg0)+0x14)) - temp_f2;
            temp_f30 = temp_f1_2 - lbl_8053EC30;
            temp_f1_3 = fn_8023E724(*(u32*)((char*)(((*(u32*)((char*)(arg0)+0x2B8)), temp_f1_2, temp_f2))+0x4));
            temp_f31 = (*(u32*)((char*)(arg0)+0x10)) - temp_f1_3;
            temp_f2_2 = (*(u32*)((char*)(arg0)+0xC)) - *fn_8023E724((*(u32*)((char*)(arg0)+0x2B8)), temp_f1_3);
            spC = temp_f31;
            sp10 = temp_f30;
            temp_f1_4 = temp_f2_2 * lbl_8053EC58;
            sp8 = temp_f2_2;
            sp8 = temp_f1_4;
            spC = temp_f31 * lbl_8053EC58;
            fn_8023DFF4((*(u32*)((char*)(arg0)+0x2B8)), &sp8, temp_f1_4, temp_f2_2);
        }
    }
    temp_r0_4 = (*(u32*)((char*)(arg0)+0x248));
    var_r3_2 = 0;
    if (temp_r0_4 < 9) {
        if (temp_r0_4 < 6) {

        } else {
            var_r3_2 = 1;
        }
    }
    if (var_r3_2 != 0) {
        (*(u32*)((char*)(arg0)+0x2C0)) = (s32) ((*(u32*)((char*)(arg0)+0x2C0)) + 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x2C0)) >= 0x78) {
            if (fn_80236228((*(u32*)((char*)(arg0)+0x2B8))) >= 0x14) {
                fn_80236074((*(u32*)((char*)(arg0)+0x2B8)), 0x14, 1);
            }
            (*(u32*)((char*)(arg0)+0x2C0)) = 0;
        }
    }
    if (((*(u32*)((char*)(arg0)+0x230)) & 0x8000) && (fn_8022DD74((*(u32*)((char*)(arg0)+0x2C4))) != 0)) {
        (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) & 0xFFFF7FFF);
        (*(u32*)((char*)(arg0)+0x2C4)) = -1;
    }
}

/* --- auto_fn_801BC554_text.s --- */
/*
Decompilation failure in function fn_801BC554:

Found bctr instruction at auto_fn_801BC554_text.s line 55, but the corresponding jump table is not provided.

Please include it in the input .s file(s), or in an additional file.

*/

/* --- auto_fn_801BC9DC_text.s --- */
u32 fn_801BCD70(void *, u32);                         /* extern */





extern char lbl_804A3E30;



extern f32 lbl_8053EC3C;
extern f32 lbl_8053EC68;

void fn_801BC9DC(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    f32 var_f4;
    f32 var_f5;
    s32 temp_r0;
    s32 temp_r30;
    s32 temp_r3_2;
    s32 temp_r3_3;
    u32 temp_r3;
    u32 temp_r4;
    u8 var_r3_2;
    char *var_r3;

    fn_801D0ED0();
    temp_r3 = (*(u32*)((char*)(arg0)+0x90)) & 0x1F;
    if (temp_r3 >= 2U) {
        (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) | 0x4000);
    }
    (*(u32*)((char*)(arg0)+0x2A8)) = (s32) (temp_r3 & 1);
    fn_801BCD70(arg0 + 0x2C8, (*(u32*)((char*)(arg0)+0x90)));
    if ((*(u32*)((char*)(arg0)+0x230)) & 0x4000) {
        (*(u32*)((char*)(arg0)+0x2AC)) = (s32) (*(u32*)((char*)(arg0)+0x4));
    } else {
        (*(u32*)((char*)(arg0)+0x2AC)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x18U) & 7);
        temp_r3_2 = (*(u32*)((char*)(arg0)+0x2AC));
        if (temp_r3_2 != 0) {
            (*(u32*)((char*)(arg0)+0x2AC)) = (s32) (temp_r3_2 + 7);
        }
    }
    if (!((*(u32*)((char*)(arg0)+0x230)) & 0x4000)) {
        var_f4 = lbl_8053EC0C;
        temp_r30 = (*(u32*)((char*)(arg0)+0x2AC));
        var_f5 = var_f4;
        if (temp_r30 == 0) {
            temp_r3_3 = fn_802D6A9C();
            if (temp_r30 < 8) {
                var_r3 = temp_r3_3 + 0xCC;
            } else {
                var_r3 = temp_r3_3 + 0xDC;
            }
            var_f4 = (*(u32*)((char*)(var_r3)+0x0));
            var_f5 = (*(u32*)((char*)(var_r3)+0x4));
        }
        temp_r4 = (*(u32*)((char*)(arg0)+0x90));
        (*(u32*)((char*)(arg0)+0x2B0)) = (f32) (lbl_8053EC3C + ((f32) ((temp_r4 >> 0xDU) & 0x1F8) + var_f4));
        (*(u32*)((char*)(arg0)+0x2B4)) = (f32) (lbl_8053EC3C + ((f32) ((temp_r4 >> 5U) & 0x1F8) + var_f5));
    }
    (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053EC08;
    (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053EC08;
    (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053EC68;
    (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053EC68;
    (*(u32*)((char*)(arg0)+0x70)) = (f32) (*(u32*)((char*)(arg0)+0x60));
    (*(u32*)((char*)(arg0)+0x74)) = (f32) (*(u32*)((char*)(arg0)+0x64));
    (*(u32*)((char*)(arg0)+0x78)) = (f32) (*(u32*)((char*)(arg0)+0x68));
    (*(u32*)((char*)(arg0)+0x7C)) = (f32) (*(u32*)((char*)(arg0)+0x6C));
    (*(u32*)((char*)(arg0)+0x80)) = (f32) lbl_8053EC08;
    (*(u32*)((char*)(arg0)+0x84)) = (f32) lbl_8053EC08;
    (*(u32*)((char*)(arg0)+0x88)) = (f32) lbl_8053EC68;
    (*(u32*)((char*)(arg0)+0x8C)) = (f32) lbl_8053EC68;
    (*(u32*)((char*)(arg0)+0x98)) = 2;
    (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) | 0x100);
    (*(u32*)((char*)(arg0)+0x194)) = 1;
    if ((s32) (*(u32*)((char*)(arg0)+0x2A8)) == 0) {
        (*(u32*)((char*)(arg0)+0x248)) = 0;
        (*(u32*)((char*)(arg0)+0x250)) = (s32) (fn_801CD664(0x79) + 0x3C);
        (*(u32*)((char*)(arg0)+0x14)) = (f32) lbl_8053EC00;
    } else {
        (*(u32*)((char*)(arg0)+0x248)) = 9;
        (*(u32*)((char*)(arg0)+0x250)) = (s32) (fn_801CD664(0xB5) + 0xB4);
    }
    (*(u32*)((char*)(arg0)+0x24C)) = 0;
    (*(u32*)((char*)(arg0)+0x254)) = (f32) lbl_8053EC0C;
    (*(u32*)((char*)(arg0)+0x258)) = (f32) lbl_8053EC0C;
    fn_801D2608(arg0 + 0x270, &lbl_804A3E30, 5);
    fn_801D22DC(arg0 + 0x270, 0, 0, 0);
    temp_r0 = (*(u32*)((char*)(arg0)+0x248));
    var_r3_2 = 0;
    if (temp_r0 != 5) {
        if (temp_r0 < 5) {
            if (temp_r0 < 4) {

            } else {
                goto block_21;
            }
        } else if (temp_r0 < 9) {
block_21:
            var_r3_2 = 1;
        }
    }
    if (var_r3_2 != 0) {
        (*(u32*)((char*)(arg0)+0xB0)) = 0x40004;
        return;
    }
    (*(u32*)((char*)(arg0)+0xB0)) = 0x41101;
}

/* --- auto_fn_801BCC40_text.s --- */




extern char lbl_804A3E44;


void *fn_801BCC40(void *arg0, s16 arg1) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    if (arg0 != NULL) {
        (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A3E44;
        if (((*(u32*)((char*)(arg0)+0x230)) & 0x8000) && ((s32) (*(u32*)((char*)(arg0)+0x2C4)) >= 0)) {
            fn_8022DD74();
        }
        if (arg0 != NULL) {
            (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A4808;
            if (((arg0 + 0x270) != NULL) && ((arg0 + 0x294) != NULL)) {
                (*(u32*)((char*)(arg0)+0x294)) = (u32)&lbl_8049CC34;
            }
            dtor_801F593C(arg0, 0);
        }
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_801BCCF0_text.s --- */




void *fn_801BCCF0(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    fn_801D0F40();
    (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A3E44;
    (*(u32*)((char*)(arg0)+0x2A8)) = 0;
    (*(u32*)((char*)(arg0)+0x2AC)) = 0;
    (*(u32*)((char*)(arg0)+0x2B0)) = (f32) lbl_8053EC0C;
    (*(u32*)((char*)(arg0)+0x2B4)) = (f32) lbl_8053EC0C;
    (*(u32*)((char*)(arg0)+0x2B8)) = -1;
    (*(u32*)((char*)(arg0)+0x2BC)) = 0;
    (*(u32*)((char*)(arg0)+0x2C0)) = 0;
    (*(u32*)((char*)(arg0)+0x2C4)) = -1;
    (*(u32*)((char*)(arg0)+0x2C8)) = 8;
    (*(u32*)((char*)(arg0)+0x2E4)) = 0;
    (*(u32*)((char*)(arg0)+0x2E8)) = 2;
    (*(u32*)((char*)(arg0)+0x2EC)) = 0;
    return arg0;
}

/* --- auto_03_801BCD70_text.s --- */
/*
Decompilation failure in function fn_801BCD70:

Found bctr instruction at auto_03_801BCD70_text.s line 20, but the corresponding jump table is not provided.

Please include it in the input .s file(s), or in an additional file.

*/

/* --- auto_fn_801BCEE4_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804C7870;










void fn_801BCEE4(void) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804C7870);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804C7870 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804C7870 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804C7870 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804C7870 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804C7870 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804C7870 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804C7870 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804C7870 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_801BD108_text.s --- */



extern char lbl_804A3F90;


void *fn_801BD108(void *arg0, s16 arg1) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 temp_cr0_eq;

    temp_cr0_eq = arg0 == NULL;
    if (temp_cr0_eq == 0) {
        (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A3F90;
        if (temp_cr0_eq == 0) {
            (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A4808;
            if (((arg0 + 0x270) != NULL) && ((arg0 + 0x294) != NULL)) {
                (*(u32*)((char*)(arg0)+0x294)) = (u32)&lbl_8049CC34;
            }
            dtor_801F593C(arg0, 0);
        }
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_801BD198_text.s --- */
u32 fn_801BD8C0(f32 *, s16);                          /* extern */
u32 fn_801F666C(s32);                                 /* extern */
u32 fn_801F856C();                                    /* extern */

u8 fn_802D800C(s32);                                /* extern */
extern char lbl_8052EBC0;
extern f32 lbl_8053EC70;

void fn_801BD198(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f30;
    f32 temp_f31;
    s16 var_r30;
    s16 var_r30_2;
    s32 temp_r29;
    s32 temp_r29_2;
    s32 temp_r3;
    s32 temp_r5;
    s32 var_r30_3;
    char *var_r29;

    temp_r29 = (*(u32*)((char*)(arg0)+0x2F0));
    var_r30 = (*(u32*)((char*)(arg0)+0x2F8));
    if (temp_r29 != 0) {
        fn_802D6A9C();
        if (fn_802D800C(temp_r29) != 0) {
            var_r30 = -var_r30;
        }
    }
    (*(u32*)((char*)(arg0)+0x2FA)) = (s16) ((*(u32*)((char*)(arg0)+0x2FA)) + var_r30);
    temp_r29_2 = (*(u32*)((char*)(arg0)+0x2F0));
    var_r30_2 = (*(u32*)((char*)(arg0)+0x2F8));
    if (temp_r29_2 != 0) {
        fn_802D6A9C();
        if (fn_802D800C(temp_r29_2) != 0) {
            var_r30_2 = -var_r30_2;
        }
    }
    if (var_r30_2 < 0) {
        (*(u32*)((char*)(arg0)+0x2FC)) = (s16) ((*(u32*)((char*)(arg0)+0x2FA)) - 0x4000);
    } else {
        (*(u32*)((char*)(arg0)+0x2FC)) = (s16) ((*(u32*)((char*)(arg0)+0x2FA)) + 0x4000);
    }
    temp_r5 = ((u32) (*(u32*)((char*)(arg0)+0x2FA)) >> 2U) & 0x3FF8;
    var_r29 = arg0;
    var_r30_3 = 0;
    sp10 = (*(u32*)((char*)(arg0)+0x14));
    temp_f31 = *(&lbl_8052EBC0 + temp_r5) * lbl_8053EC70;
    temp_r3 = (*(u32*)((char*)(arg0)+0x2F4));
    temp_f30 = (*(u32*)((char*)((&lbl_8052EBC0 + temp_r5))+0x4)) * lbl_8053EC70;
    sp8 += (f32) temp_r3 * temp_f31;
    spC += (f32) temp_r3 * temp_f30;
loop_11:
    if (var_r30_3 < (s32) (*(u32*)((char*)(arg0)+0x2A8))) {
        fn_801F856C();
        fn_801F666C((*(u32*)((char*)(var_r29)+0x2AC)));
        fn_801BD8C0(&sp8, (*(u32*)((char*)(arg0)+0x2FC)));
        var_r29 += 4;
        var_r30_3 += 1;
        sp8 += temp_f31;
        spC += temp_f30;
        goto loop_11;
    }
}

/* --- auto_fn_801BD348_text.s --- */




s16 fn_801F6874(u8);                                /* extern */

s32 fn_801F9484(u32, s32, f32 *, s32, u32, u32);          /* extern */




extern f32 lbl_8053EC80;
extern f32 lbl_8053EC84;

void fn_801BD348(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f30;
    f32 temp_f31;
    s16 var_r29_2;
    s32 temp_r27;
    s32 temp_r28;
    s32 temp_r3;
    s32 temp_r5;
    s32 var_r29;
    s32 var_r29_3;
    u32 temp_r0;
    u32 temp_r0_2;
    u8 var_r0;
    u8 var_r3;
    char *var_r27;

    fn_801D0ED0();
    if (!(((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x11U) & 1)) {
        fn_801D0E58(arg0);
    }
    (*(u32*)((char*)(arg0)+0x2EC)) = (u8) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x1FU) ^ 1);
    (*(u32*)((char*)(arg0)+0x2F0)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x1AU) & 0x1F);
    temp_r0 = (*(u32*)((char*)(arg0)+0x90));
    var_r29 = (temp_r0 >> 0x18U) & 3;
    if (var_r29 > 2) {
        var_r29 = 2;
    } else if (var_r29 < 0) {
        var_r29 = 0;
    }
    (*(u32*)((char*)(arg0)+0x2F4)) = (s32) (((temp_r0 >> 0x14U) & 0xF) + 1);
    temp_r0_2 = (*(u32*)((char*)(arg0)+0x90));
    var_r3 = (u8) (temp_r0_2 >> 8U);
    if ((s32) var_r3 > 3) {
        var_r3 = 3;
    } else if ((s32) var_r3 < 0) {
        var_r3 = 0;
    }
    var_r0 = (u8) temp_r0_2;
    if ((s32) var_r0 > 0x10) {
        var_r0 = 0x10;
    } else if ((s32) var_r0 < 1) {
        var_r0 = 1;
    }
    (*(u32*)((char*)(arg0)+0x2A8)) = (s32) var_r0;
    (*(u32*)((char*)(arg0)+0x2FA)) = fn_801F6874(var_r3);
    switch (var_r29) {                              /* irregular */
    case 0:
        (*(u32*)((char*)(arg0)+0x2F8)) = 0x80;
        break;
    case 1:
        (*(u32*)((char*)(arg0)+0x2F8)) = 0x100;
        break;
    default:
        (*(u32*)((char*)(arg0)+0x2F8)) = 0x40;
        break;
    }
    if ((u32) ((temp_r0_2 >> 0x10U) & 1) == 0) {
        (*(u32*)((char*)(arg0)+0x2F8)) = (s16) -(*(u32*)((char*)(arg0)+0x2F8));
    }
    (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053EC80;
    (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053EC80;
    (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053EC84;
    (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053EC84;
    (*(u32*)((char*)(arg0)+0x70)) = (f32) (*(u32*)((char*)(arg0)+0x60));
    (*(u32*)((char*)(arg0)+0x74)) = (f32) (*(u32*)((char*)(arg0)+0x64));
    (*(u32*)((char*)(arg0)+0x78)) = (f32) (*(u32*)((char*)(arg0)+0x68));
    (*(u32*)((char*)(arg0)+0x7C)) = (f32) (*(u32*)((char*)(arg0)+0x6C));
    (*(u32*)((char*)(arg0)+0x80)) = (f32) lbl_8053EC80;
    (*(u32*)((char*)(arg0)+0x84)) = (f32) lbl_8053EC80;
    (*(u32*)((char*)(arg0)+0x88)) = (f32) lbl_8053EC84;
    (*(u32*)((char*)(arg0)+0x8C)) = (f32) lbl_8053EC84;
    (*(u32*)((char*)(arg0)+0xB0)) = 0;
    (*(u32*)((char*)(arg0)+0x98)) = 2;
    temp_r27 = (*(u32*)((char*)(arg0)+0x2F0));
    var_r29_2 = (*(u32*)((char*)(arg0)+0x2F8));
    if (temp_r27 != 0) {
        fn_802D6A9C();
        if (fn_802D800C(temp_r27) != 0) {
            var_r29_2 = -var_r29_2;
        }
    }
    if (var_r29_2 < 0) {
        (*(u32*)((char*)(arg0)+0x2FC)) = (s16) ((*(u32*)((char*)(arg0)+0x2FA)) - 0x4000);
    } else {
        (*(u32*)((char*)(arg0)+0x2FC)) = (s16) ((*(u32*)((char*)(arg0)+0x2FA)) + 0x4000);
    }
    temp_r5 = ((u32) (*(u32*)((char*)(arg0)+0x2FA)) >> 2U) & 0x3FF8;
    var_r27 = arg0;
    var_r29_3 = 0;
    sp10 = (*(u32*)((char*)(arg0)+0x14));
    temp_f31 = *(&lbl_8052EBC0 + temp_r5) * lbl_8053EC70;
    temp_r3 = (*(u32*)((char*)(arg0)+0x2F4));
    temp_f30 = (*(u32*)((char*)((&lbl_8052EBC0 + temp_r5))+0x4)) * lbl_8053EC70;
    sp8 += (f32) temp_r3 * temp_f31;
    spC += (f32) temp_r3 * temp_f30;
loop_31:
    if (var_r29_3 < (s32) (*(u32*)((char*)(arg0)+0x2A8))) {
        temp_r28 = (*(u32*)((char*)(arg0)+0x2EC)) == 0;
        fn_801F856C();
        (*(u32*)((char*)(var_r27)+0x2AC)) = fn_801F9484(0x46424F42, (*(u32*)((char*)(arg0)+0x4)), &sp8, temp_r28, -1, -1);
        fn_801F856C();
        fn_801F666C((*(u32*)((char*)(var_r27)+0x2AC)));
        fn_801BD8C0(&sp8, (*(u32*)((char*)(arg0)+0x2FC)));
        var_r27 += 4;
        var_r29_3 += 1;
        sp8 += temp_f31;
        spC += temp_f30;
        goto loop_31;
    }
}

/* --- auto_fn_801BD640_text.s --- */



void *fn_801BD640(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    fn_801D0F40();
    (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A3F90;
    (*(u32*)((char*)(arg0)+0x2A8)) = 0;
    (*(u32*)((char*)(arg0)+0x2EC)) = 0;
    (*(u32*)((char*)(arg0)+0x2F0)) = 0;
    (*(u32*)((char*)(arg0)+0x2F4)) = 0;
    (*(u32*)((char*)(arg0)+0x2F8)) = 0;
    (*(u32*)((char*)(arg0)+0x2FA)) = 0;
    (*(u32*)((char*)(arg0)+0x2FC)) = 0;
    return arg0;
}

/* --- auto_fn_801BD69C_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804C7970;










void fn_801BD69C(void) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804C7970);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804C7970 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804C7970 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804C7970 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804C7970 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804C7970 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804C7970 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804C7970 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804C7970 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_801BD8C0_text.s --- */
u32 fn_800EF008(u32, s16, u32, s32);                      /* extern */
u32 fn_8013CB44(s32, void *, u32, u32, u32);                /* extern */
s16 fn_801CB7CC(s32, f32);                          /* extern */

void fn_801BD8C0(void *arg0, void *arg1, s32 arg2) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    f32 temp_f1;
    s16 temp_r30;
    s32 var_r29;
    char *var_r31;

    temp_f1 = (*(u32*)((char*)(arg1)+0x4));
    (*(u32*)((char*)(arg0)+0xC)) = (f32) (*(u32*)((char*)(arg1)+0x0));
    (*(u32*)((char*)(arg0)+0x10)) = temp_f1;
    (*(u32*)((char*)(arg0)+0x14)) = (f32) (*(u32*)((char*)(arg1)+0x8));
    var_r31 = arg0;
    temp_r30 = fn_801CB7CC(arg2, temp_f1);
    var_r29 = 0;
    do {
        fn_8013CB44((*(u32*)((char*)(var_r31)+0x2A8)), arg1, 0, 0, 1);
        if (var_r29 == 0) {
            fn_800EF008(0, temp_r30, 0, (*(u32*)((char*)(var_r31)+0x2A8)) + 0x68);
        }
        var_r29 += 1;
        var_r31 += 4;
    } while (var_r29 < 2);
}

/* --- auto_fn_801BD978_text.s --- */
u32 fn_80158B5C(s32, s32, s32, s32 *, u32, f32);        /* extern */
extern void *lbl_8053AB10;
extern f32 lbl_8053EC8C;

void fn_801BD978(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s8 spF;
    s8 spE;
    s8 spD;
    s8 spC;
    s32 sp8;

    spC = 0;
    spD = 0;
    spE = 0;
    spF = 0x80;
    sp8 = (s32) spC;
    fn_80158B5C((*(u32*)((char*)(lbl_8053AB10)+0x2C)), (*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, &sp8, 0, lbl_8053EC8C);
}

/* --- auto_fn_801BD9D0_text.s --- */

s8 fn_801F2B7C(s32, u32, u32);                          /* extern */
extern f32 lbl_8053EC90;

void fn_801BD9D0(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    (*(u32*)((char*)(arg0)+0x240)) = fn_801F2B7C((*(u32*)((char*)(arg0)+0x114)), -1, 1);
    if ((u32) (*(u32*)((char*)(arg0)+0x90)) == 0U) {
        fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x54D, 1, 1, 0, 0, 1, lbl_8053EC90);
    }
}

/* --- auto_fn_801BDA40_text.s --- */


extern u16 lbl_8053EC88;

extern f32 lbl_8053EC94;
extern f32 lbl_8053EC98;
extern f32 lbl_8053EC9C;

void fn_801BDA40(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 var_r29;
    u16 *var_r31;
    char *var_r30;

    fn_801D0ED0();
    (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053EC94;
    var_r30 = arg0;
    (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053EC94;
    var_r29 = 0;
    var_r31 = &lbl_8053EC88;
    (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053EC98;
    (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053EC98;
    (*(u32*)((char*)(arg0)+0x70)) = (f32) lbl_8053EC90;
    (*(u32*)((char*)(arg0)+0x74)) = (f32) lbl_8053EC90;
    (*(u32*)((char*)(arg0)+0x78)) = (f32) lbl_8053EC9C;
    (*(u32*)((char*)(arg0)+0x7C)) = (f32) lbl_8053EC9C;
    (*(u32*)((char*)(arg0)+0x80)) = (f32) lbl_8053EC90;
    (*(u32*)((char*)(arg0)+0x84)) = (f32) lbl_8053EC90;
    (*(u32*)((char*)(arg0)+0x88)) = (f32) lbl_8053EC9C;
    (*(u32*)((char*)(arg0)+0x8C)) = (f32) lbl_8053EC9C;
    (*(u32*)((char*)(arg0)+0xB0)) = 0;
    (*(u32*)((char*)(arg0)+0x98)) = 2;
    (*(u32*)((char*)(arg0)+0x194)) = 1;
    (*(u32*)((char*)(arg0)+0x114)) = 2;
    do {
        var_r29 += 1;
        (*(u32*)((char*)(var_r30)+0x2A8)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, *var_r31, 0, 0, 0, 0, 1, lbl_8053EC90);
        var_r31 += 2;
        var_r30 += 4;
    } while (var_r29 < 2);
}

/* --- auto_fn_801BDB2C_text.s --- */




extern char lbl_804A4038;


void *fn_801BDB2C(void *arg0, s16 arg1) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 var_r30;
    char *var_r31;

    if (arg0 != NULL) {
        var_r31 = arg0;
        var_r30 = 0;
        (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A4038;
        do {
            fn_801EE434((*(u32*)((char*)(var_r31)+0x2A8)));
            var_r30 += 1;
            var_r31 += 4;
        } while (var_r30 < 2);
        if (arg0 != NULL) {
            (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A4808;
            if (((arg0 + 0x270) != NULL) && ((arg0 + 0x294) != NULL)) {
                (*(u32*)((char*)(arg0)+0x294)) = (u32)&lbl_8049CC34;
            }
            dtor_801F593C(arg0, 0);
        }
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_801BDBF0_text.s --- */



void *fn_801BDBF0(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    fn_801D0F40();
    (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A4038;
    (*(u32*)((char*)(arg0)+0x2A8)) = 0;
    (*(u32*)((char*)(arg0)+0x2AC)) = 0;
    return arg0;
}

/* --- auto_fn_801BDC38_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804C7A70;










void fn_801BDC38(void) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804C7A70);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804C7A70 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804C7A70 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804C7A70 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804C7A70 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804C7A70 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804C7A70 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804C7A70 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804C7A70 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_801BDE5C_text.s --- */



extern char lbl_804A40E0;


void *fn_801BDE5C(void *arg0, s16 arg1) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 temp_cr0_eq;

    temp_cr0_eq = arg0 == NULL;
    if (temp_cr0_eq == 0) {
        (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A40E0;
        if (temp_cr0_eq == 0) {
            (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A4808;
            if (((arg0 + 0x270) != NULL) && ((arg0 + 0x294) != NULL)) {
                (*(u32*)((char*)(arg0)+0x294)) = (u32)&lbl_8049CC34;
            }
            dtor_801F593C(arg0, 0);
        }
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_801BDEEC_text.s --- */
u32 fn_8013AC90(f32 *, char *, u32, u32, u32, f32);            /* extern */
u32 fn_801F06F0(void *, char *, u32, char *, u32, f32, f32);    /* extern */
extern char lbl_804693D8;

extern u8 lbl_8053AC08;
extern char lbl_8053AC0C;
extern f32 lbl_8053ECA0;
extern f32 lbl_8053ECA4;
extern f32 lbl_8053ECA8;
extern f32 lbl_8053ECAC;
extern f32 lbl_8053ECB0;

void fn_801BDEEC(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 sp4C;
    s32 sp48;
    s32 sp44;
    s8 sp42;
    s8 sp41;
    s8 sp40;
    s32 sp3C;
    s8 sp3A;
    s8 sp39;
    s8 sp38;
    s8 sp37;
    s8 sp36;
    s8 sp35;
    s8 sp34;
    s8 sp33;
    s8 sp32;
    s8 sp31;
    s8 sp30;
    s32 sp2C;
    s32 sp28;                                       /* compiler-managed */
    s32 sp24;
    u32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    u32 var_r6;
    f32 temp_f1;
    f32 temp_f4;
    s32 temp_r0_2;
    u8 temp_r0;
    u8 temp_r3;
    u8 temp_r3_2;
    u8 temp_r4;
    u8 temp_r4_2;
    u8 temp_r5;
    u8 temp_r5_2;
    u8 temp_r6;
    u8 temp_r7;
    u8 temp_r8;
    u8 var_r10;

    var_r10 = 0;
    sp24 = -1;
    sp28 = -1;
loop_2:
    if (var_r10 < 0x10U) {
        temp_r7 = var_r10 + 5;
        temp_r5 = var_r10 + 1;
        *(&sp14 + var_r10) = var_r10;
        temp_r3 = var_r10 + 2;
        *(&sp14 + temp_r5) = temp_r5;
        temp_r4 = var_r10 + 3;
        temp_r8 = var_r10 + 4;
        *(&sp14 + temp_r3) = temp_r3;
        temp_r6 = temp_r7;
        temp_r5_2 = var_r10 + 6;
        *(&sp14 + temp_r4) = temp_r4;
        temp_r3_2 = var_r10 + 7;
        temp_r4_2 = temp_r5_2;
        *(&sp14 + temp_r8) = temp_r8;
        temp_r0 = temp_r3_2;
        var_r10 += 8;
        *(&sp14 + temp_r6) = temp_r7;
        *(&sp14 + temp_r4_2) = temp_r5_2;
        *(&sp14 + temp_r0) = temp_r3_2;
        goto loop_2;
    }
    sp24 = -1;
    sp28 = 0;
    sp2C = 0;
    sp30 = 0;
    sp31 = 0;
    sp32 = 0;
    sp33 = 1;
    sp34 = 1;
    sp35 = 0;
    sp36 = 0;
    sp37 = 0;
    sp38 = 0;
    sp39 = 0;
    sp3A = 1;
    sp3C = 3;
    sp40 = 1;
    sp41 = 0;
    sp42 = 0;
    sp44 = -1;
    sp48 = 0;
    sp4C = 2;
    if ((s32) (*(u32*)((char*)(arg0)+0x248)) == 2) {
        sp28 = 0x80;
        unksp29 = 0x80;
        unksp2A = 0x80;
    }
    fn_801F06F0(arg0, &lbl_804693D8, 0x13C, &sp14, -1, lbl_8053ECA0, lbl_8053ECA0);
    if (!((*(u32*)((char*)(arg0)+0x230)) & 0x2000)) {
        if ((s8) lbl_8053AC08 == 0) {
            (*(u32*)((char*)&lbl_8053AC0C+0x0)) = 0xFF;
            (*(u32*)((char*)&lbl_8053AC0C+0x1)) = 0xFF;
            (*(u32*)((char*)&lbl_8053AC0C+0x2)) = 0xFF;
            (*(u32*)((char*)&lbl_8053AC0C+0x3)) = 0xFF;
            lbl_8053AC08 = 1;
        }
        temp_r0_2 = ((u32) (*(u32*)((char*)(arg0)+0x2A8)) >> 2U) & 0x3FF8;
        temp_f1 = (*(u32*)((char*)(arg0)+0x10));
        var_r6 = 0;
        temp_f4 = lbl_8053ECA4 + ((lbl_8053ECA8 * (*(u32*)((char*)((&lbl_8052EBC0 + temp_r0_2))+0x4))) + temp_f1);
        sp10 = (*(u32*)((char*)(arg0)+0x14));
        sp8 = (lbl_8053ECAC * *(&lbl_8052EBC0 + temp_r0_2)) + (*(u32*)((char*)(arg0)+0xC));
        spC = temp_f4;
        M2C_ERROR(/* unknown instruction: cror eq, gt, eq */);
        if (temp_f4 == (lbl_8053ECA4 + temp_f1)) {
            var_r6 = 1;
        }
        fn_8013AC90(&sp8, &lbl_8053AC0C, 0, var_r6, 0, lbl_8053ECB0);
    }
}

/* --- auto_fn_801BE0F4_text.s --- */

u32 fn_801F4F28(void *);                              /* extern */


void fn_801BE0F4(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x70, 0, 0, 0, 0, 1, lbl_8053ECA0);
    fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x71, 0, 0, 0, 0, 1, lbl_8053ECA0);
    fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x72, 0, 0, 0, 0, 1, lbl_8053ECA0);
    fn_801F4F28(arg0);
}

/* --- auto_fn_801BE19C_text.s --- */
u8 fn_801CEBD0();                                   /* extern */

s32 fn_801F285C(void *, u32, u32, u32, s32);              /* extern */
u32 fn_801F3128(void *, char *);                         /* extern */
u8 fn_80238548(s32, s32, char *, u32);                   /* extern */
u32 fn_8023B6CC(s32);                                 /* extern */
u8 fn_8023E854(s32);                                /* extern */

u8 fn_801BE19C(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    u32 sp8;
    s32 var_r30;
    u8 var_r31;

    var_r31 = 0;
    if ((s32) (*(u32*)((char*)(arg0)+0x248)) == 2) {
        var_r30 = 0;
        do {
            if (var_r30 == fn_801F285C(arg0, 0, 0, 1, var_r30)) {
                fn_8023B6CC(var_r30);
                if (fn_8023E854(var_r30) == 0) {
                    fn_801F3128(arg0, &sp8);
                    if (fn_80238548(var_r30, (*(u32*)((char*)(arg0)+0x114)), &sp8, 0xA) != 0) {
                        var_r31 = 1;
                    }
                }
            }
            var_r30 += 1;
        } while (var_r30 < 4);
        if (var_r31 != 0) {
            fn_801F0E34(arg0, 0x4000C, 0);
        }
    } else {
        var_r31 = fn_801CEBD0();
    }
    return var_r31;
}

/* --- auto_fn_801BE284_text.s --- */
u32 fn_801F2DB4(s32, u32, u32);                           /* extern */

void fn_801BE284(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 var_r4;

    if ((u16) (*(u32*)((char*)(arg0)+0x2AA)) != 0) {
        var_r4 = 0x4E554C4C;
    } else {
        var_r4 = (*(u32*)((char*)(arg0)+0x1A0));
    }
    fn_801F2DB4(var_r4, 0x5357424D, 0);
}

/* --- auto_03_801BE2CC_text.s --- */
void fn_801BE2CC(void) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;

}

/* --- auto_fn_801BE2D0_text.s --- */
u32 fn_801CE2BC();                                    /* extern */
u8 *fn_8020D58C(f32, f32, f32, f32);                /* extern */
u32 fn_8020D8C0(void *, f32 *, s32, s32, u8 *);       /* extern */
u32 fn_80239914(f32 *, s32, s32, f32, f32, f32, f32); /* extern */
extern f32 lbl_8053ECB4;

void fn_801BE2D0(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    f32 sp24;
    f32 sp20;
    f32 sp1C;
    f32 sp18;
    f32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    f32 temp_f1_2;
    f32 temp_f1_3;
    f32 temp_f1_4;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f3;
    f32 temp_f3_2;
    f32 temp_f4;
    f32 temp_f4_2;
    s32 temp_r30;
    s32 temp_r31;
    u16 temp_r3;
    u8 *temp_r3_2;

    fn_801CE2BC();
    temp_r3 = (*(u32*)((char*)(arg0)+0x2AA));
    if (temp_r3 != 0) {
        (*(u32*)((char*)(arg0)+0x2AA)) = (u16) (temp_r3 - 1);
    }
    temp_f4 = (*(u32*)((char*)(arg0)+0x10));
    temp_f1 = (*(u32*)((char*)(arg0)+0xC));
    temp_f3 = temp_f4 + lbl_8053ECB4;
    temp_f2 = temp_f1 + lbl_8053ECB4;
    temp_f1_2 = temp_f1 - lbl_8053ECB4;
    sp14 = temp_f3;
    sp8 = temp_f1_2;
    spC = temp_f4 - lbl_8053ECB4;
    sp10 = temp_f2;
    fn_80239914(&sp8, (*(u32*)((char*)(arg0)+0x4)), (*(u32*)((char*)(arg0)+0x198)), temp_f1_2, temp_f2, temp_f3, temp_f4);
    if ((u16) (*(u32*)((char*)(arg0)+0x2AA)) == 0) {
        temp_f4_2 = (*(u32*)((char*)(arg0)+0x10));
        temp_f1_3 = (*(u32*)((char*)(arg0)+0xC));
        temp_f3_2 = temp_f4_2 + lbl_8053ECB4;
        temp_f2_2 = temp_f1_3 + lbl_8053ECB4;
        temp_f1_4 = temp_f1_3 - lbl_8053ECB4;
        sp24 = temp_f3_2;
        sp18 = temp_f1_4;
        sp1C = temp_f4_2 - lbl_8053ECB4;
        sp20 = temp_f2_2;
        temp_r31 = (*(u32*)((char*)(arg0)+0x198));
        temp_r30 = (*(u32*)((char*)(arg0)+0x4));
        temp_r3_2 = fn_8020D58C(temp_f1_4, temp_f2_2, temp_f3_2, temp_f4_2);
        fn_8020D8C0(temp_r3_2 + ((*temp_r3_2 * 0x784) + 4), &sp18, temp_r30, temp_r31, temp_r3_2);
    }
}

/* --- auto_fn_801BE3BC_text.s --- */
f32 fn_80093340(char *, void *, char *, f32, f32, f32);   /* extern */
u32 fn_801BE6C4(void *, u32);                           /* extern */
u8 fn_801D08B4(void *, s32, void *, f32);           /* extern */

f32 *fn_8023E724(s32, f32, f32);                    /* extern */



extern char lbl_80534C00;



extern f32 lbl_8053ECB8;
extern f32 lbl_8053ECBC;
extern f32 lbl_8053ECC0;
extern f32 lbl_8053ECC4;

void fn_801BE3BC(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    f32 temp_f29;
    f32 temp_f2;
    f32 temp_f30;
    f32 temp_f3;
    s16 temp_r29;
    s32 temp_r0;
    s32 temp_r0_2;
    s32 temp_r27;
    s32 temp_r27_2;
    s32 var_r27;
    s32 var_r28;
    u32 temp_r3;
    char *temp_r4;

    if ((*(u32*)((char*)(arg0)+0x230)) & 0x2000) {
        temp_r27 = (*(u32*)((char*)(arg0)+0x2B0));
        if (temp_r27 != 0) {
            fn_802D6A9C();
            if (fn_802D800C(temp_r27) != 0) {
                (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) & 0xFFFFDFFF);
                fn_801BE6C4(arg0, 0);
            }
        }
    }
    if (!((*(u32*)((char*)(arg0)+0x230)) & 0x2000)) {
        temp_r27_2 = (*(u32*)((char*)(arg0)+0x2B4));
        if (temp_r27_2 != 0) {
            fn_802D6A9C();
            if (fn_802D800C(temp_r27_2) != 0) {
                (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) | 0x2000);
            }
        }
    }
    temp_r3 = (*(u32*)((char*)(arg0)+0x230)) & 0x2000;
    if (temp_r3 != 0) {
        fn_801BE6C4(arg0, 1);
        return;
    }
    if ((s32) (*(u32*)((char*)(arg0)+0x108)) > 0) {
        temp_r0 = (*(u32*)((char*)(arg0)+0x248));
        switch (temp_r0) {                          /* irregular */
        case 0:
            if ((s32) (*(u32*)((char*)(arg0)+0x24C)) >= (s32) (*(u32*)((char*)(arg0)+0x250))) {
                fn_801BE6C4(arg0, 1);
                return;
            }
            break;
        case 1:
            if (temp_r3 == 0) {
                fn_801F0E34(arg0, 0x400C1, 0);
            }
            (*(u32*)((char*)(arg0)+0x2A8)) = (s16) ((*(u32*)((char*)(arg0)+0x2A8)) + 0x100);
            if ((s32) (*(u32*)((char*)(arg0)+0x24C)) >= 0x1E) {
                temp_r0_2 = ((u32) (*(u32*)((char*)(arg0)+0x2A8)) >> 2U) & 0x3FF8;
                temp_r4 = &lbl_8052EBC0 + temp_r0_2;
                temp_f3 = (*(u32*)((char*)(temp_r4)+0x4));
                var_r27 = -1;
                var_r28 = 0;
                temp_f30 = lbl_8053ECBC;
                temp_r29 = (s16) (fn_80093340(&lbl_80534C00, temp_r4, &lbl_8052EBC0, lbl_8053ECAC * *(&lbl_8052EBC0 + temp_r0_2), lbl_8053ECA8 * temp_f3, temp_f3) * lbl_8053ECB8);
loop_24:
                if ((fn_801D08B4(arg0, var_r28, arg0 + 0xC, temp_f30 * (f32) (*(u32*)((char*)(arg0)+0x2AC))) != 0) && (temp_f2 = fn_8023E724(*(u32*)((char*)((var_r28))+0x4)), temp_f29 = temp_f2 - (lbl_8053ECA4 + (*(u32*)((char*)(arg0)+0x10))), M2C_ERROR(/* unknown instruction: cror eq, lt, eq */), (((lbl_8053ECC0 * fabs((f32) (s16) (temp_r29 - (s32) (fn_80093340(&lbl_80534C00, (void *) (*fn_8023E724(var_r28, lbl_8053ECA4, temp_f2) - (*(u32*)((char*)(arg0)+0xC))), (char *) temp_f29) * lbl_8053ECB8)))) == lbl_8053ECC4) != 0))) {
                    var_r27 = var_r28;
                } else {
                    var_r28 += 1;
                    if (var_r28 < 4) {
                        goto loop_24;
                    }
                }
                if (var_r27 >= 0) {
                    fn_801BE6C4(arg0, 2);
                    return;
                }
            }
            break;
        case 2:
            if ((s32) (*(u32*)((char*)(arg0)+0x24C)) >= 0xF) {
                fn_801BE6C4(arg0, 3);
                return;
            }
            break;
        case 3:
            if ((s32) (*(u32*)((char*)(arg0)+0x24C)) >= (s32) (*(u32*)((char*)(arg0)+0x250))) {
                fn_801BE6C4(arg0, 1);
            }
            break;
        }
    }
}

/* --- auto_fn_801BE6C4_text.s --- */

u32 fn_801BE86C(void *);                              /* extern */








void fn_801BE6C4(void *arg0, s32 arg1) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    f32 sp10;
    f32 spC;
    f32 sp8;
    u32 var_r30;
    f32 temp_f1;
    f32 temp_f4;
    s32 temp_r0;

    switch (arg1) {                                 /* irregular */
    case 0:
        (*(u32*)((char*)(arg0)+0x250)) = (s32) (fn_801CD664(1) + 0x5A);
        break;
    case 2:
        temp_r0 = ((u32) (*(u32*)((char*)(arg0)+0x2A8)) >> 2U) & 0x3FF8;
        temp_f1 = (*(u32*)((char*)(arg0)+0x10));
        var_r30 = 0;
        temp_f4 = lbl_8053ECA4 + ((lbl_8053ECA8 * (*(u32*)((char*)((&lbl_8052EBC0 + temp_r0))+0x4))) + temp_f1);
        sp10 = (*(u32*)((char*)(arg0)+0x14));
        sp8 = (lbl_8053ECAC * *(&lbl_8052EBC0 + temp_r0)) + (*(u32*)((char*)(arg0)+0xC));
        spC = temp_f4;
        M2C_ERROR(/* unknown instruction: cror eq, gt, eq */);
        if (temp_f4 == (lbl_8053ECA4 + temp_f1)) {
            var_r30 = 1;
        }
        fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp8, 0x1C, 0, var_r30, 0, 0, 1, lbl_8053ECA0);
        fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp8, 0x1D, 0, var_r30, 0, 0, 1, lbl_8053ECA0);
        fn_801F0E34(arg0, 0x30062, 0);
        (*(u32*)((char*)(arg0)+0x2AA)) = 0x3CU;
        break;
    case 3:
        (*(u32*)((char*)(arg0)+0x250)) = (s32) (fn_801CD664(1) + 0x5A);
        fn_801BE86C(arg0);
        fn_801F0E34(arg0, 0x30063, 0);
        break;
    }
    (*(u32*)((char*)(arg0)+0x24C)) = 0;
    (*(u32*)((char*)(arg0)+0x248)) = arg1;
    if ((u16) (*(u32*)((char*)(arg0)+0x2AA)) != 0) {
        (*(u32*)((char*)(arg0)+0xB0)) = 0x40002;
        return;
    }
    (*(u32*)((char*)(arg0)+0xB0)) = 0x40004;
}

/* --- auto_fn_801BE86C_text.s --- */
void *fn_801F666C(s32);                             /* extern */



extern f32 lbl_80539D44;



extern f32 lbl_8053ECD8;
extern f32 lbl_8053ECDC;
extern f32 lbl_8053ECE0;
extern f32 lbl_8053ECE4;
extern f32 lbl_8053ECE8;

f32 fn_801BE86C(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    f32 sp1C;
    f32 sp18;
    f32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    f32 temp_f3;
    f32 temp_f3_2;
    f32 temp_f5;
    f32 var_f1;
    f32 var_f4;
    f32 var_f5;
    f32 var_f6;
    s16 var_r4;
    s32 temp_r0;
    s32 temp_r0_2;
    s32 temp_r3;
    s32 temp_ret;
    char *temp_r30;
    char *temp_r3_2;
    char *temp_ret_2;

    temp_f5 = (*(u32*)((char*)(arg0)+0x14));
    temp_r30 = &lbl_8052EBC0 + 4;
    temp_r0 = ((u32) (*(u32*)((char*)(arg0)+0x2A8)) >> 2U) & 0x3FF8;
    sp1C = temp_f5;
    temp_f1 = *(&lbl_8052EBC0 + temp_r0);
    temp_f3 = lbl_8053ECA4 + ((lbl_8053ECA8 * *(temp_r30 + temp_r0)) + (*(u32*)((char*)(arg0)+0x10)));
    sp18 = temp_f3;
    sp14 = (lbl_8053ECAC * temp_f1) + (*(u32*)((char*)(arg0)+0xC));
    fn_801F856C(&lbl_8052EBC0, temp_f1, lbl_8053ECAC, temp_f3, lbl_8053ECA4, temp_f5);
    temp_ret = fn_801F9484(0x4C4E424D, (*(u32*)((char*)(arg0)+0x4)), &sp14, (*(u32*)((char*)(arg0)+0x198)), -1, -1);
    var_f1 = (f32) temp_ret;
    temp_r3 = temp_ret;
    if (temp_r3 >= 0) {
        fn_801F856C();
        temp_ret_2 = fn_801F666C(temp_r3);
        var_f1 = (f32) temp_ret_2;
        temp_r3_2 = temp_ret_2;
        if (temp_r3_2 != NULL) {
            var_r4 = 0;
            M2C_ERROR(/* unknown instruction: cror eq, gt, eq */);
            if (sp18 == (lbl_8053ECA4 + (*(u32*)((char*)(arg0)+0x10)))) {
                var_r4 = 1;
            }
            (*(u32*)((char*)(temp_r3_2)+0x94)) = var_r4;
            temp_r0_2 = ((u32) (*(u32*)((char*)(arg0)+0x2A8)) >> 2U) & 0x3FF8;
            var_f5 = lbl_8053ECA8 * *(temp_r30 + temp_r0_2);
            var_f4 = lbl_8053ECAC * *(&lbl_8052EBC0 + temp_r0_2);
            var_f6 = (var_f4 * var_f4) + (var_f5 * var_f5);
            M2C_ERROR(/* unknown instruction: cror eq, lt, eq */);
            if (var_f6 != (lbl_8053ECD8 * lbl_80539D44)) {
                M2C_ERROR(/* unknown instruction: cror eq, lt, eq */);
                if (var_f6 == lbl_8053ECDC) {

                } else {
                    temp_f3_2 = (f32) __frsqrte(var_f6);
                    var_f6 = lbl_8053ECE0 * temp_f3_2 * -((var_f6 * (temp_f3_2 * temp_f3_2)) - lbl_8053ECE4);
                }
                var_f4 *= var_f6;
                var_f5 *= var_f6;
            }
            sp10 = lbl_8053ECDC;
            sp8 = var_f4 * lbl_8053ECE8;
            spC = var_f5 * lbl_8053ECE8;
            var_f1 = M2C_ERROR(/* psq_l unimplemented */);
            (*(u32*)((char*)(temp_r3_2)+0x44)) = (f32) lbl_8053ECDC;
        }
    }
    return var_f1;
}

/* --- auto_fn_801BEA08_text.s --- */





extern f32 lbl_8053ECEC;
extern f32 lbl_8053ECF0;
extern f32 lbl_8053ECF4;
extern f32 lbl_8053ECF8;

void fn_801BEA08(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    u8 var_r0;

    fn_801D0ED0();
    var_r0 = (u8) (*(u32*)((char*)(arg0)+0x90));
    if (var_r0 > 0xFU) {
        var_r0 = 0xF;
    } else if (var_r0 < 1U) {
        var_r0 = 1;
    }
    (*(u32*)((char*)(arg0)+0x2AC)) = var_r0;
    (*(u32*)((char*)(arg0)+0x2B0)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x16U) & 0x1F);
    (*(u32*)((char*)(arg0)+0x2B4)) = (u32) ((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x1BU);
    if ((s32) (*(u32*)((char*)(arg0)+0x2B0)) != 0) {
        (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) | 0x2000);
    }
    (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_8053ECEC;
    (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8053ECF0;
    (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8053ECB4;
    (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8053ECB4;
    (*(u32*)((char*)(arg0)+0x70)) = (f32) lbl_8053ECEC;
    (*(u32*)((char*)(arg0)+0x74)) = (f32) lbl_8053ECF4;
    (*(u32*)((char*)(arg0)+0x78)) = (f32) lbl_8053ECB4;
    (*(u32*)((char*)(arg0)+0x7C)) = (f32) lbl_8053ECB4;
    (*(u32*)((char*)(arg0)+0x80)) = (f32) lbl_8053ECA0;
    (*(u32*)((char*)(arg0)+0x84)) = (f32) lbl_8053ECA0;
    (*(u32*)((char*)(arg0)+0x88)) = (f32) lbl_8053ECF8;
    (*(u32*)((char*)(arg0)+0x8C)) = (f32) lbl_8053ECF8;
    (*(u32*)((char*)(arg0)+0x98)) = 2;
    (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) | 0x180);
    (*(u32*)((char*)(arg0)+0x2A8)) = fn_801CD664(0x10000, lbl_8053ECA0, lbl_8053ECF4, lbl_8053ECB4, lbl_8053ECEC);
    (*(u32*)((char*)(arg0)+0x248)) = 0;
    (*(u32*)((char*)(arg0)+0x24C)) = 0;
    (*(u32*)((char*)(arg0)+0x250)) = (s32) (fn_801CD664(1) + 0x5A);
    (*(u32*)((char*)(arg0)+0x254)) = (f32) lbl_8053ECDC;
    (*(u32*)((char*)(arg0)+0x258)) = (f32) lbl_8053ECDC;
    if ((u16) (*(u32*)((char*)(arg0)+0x2AA)) != 0) {
        (*(u32*)((char*)(arg0)+0xB0)) = 0x40002;
        return;
    }
    (*(u32*)((char*)(arg0)+0xB0)) = 0x40004;
}

/* --- auto_fn_801BEB44_text.s --- */



void *fn_801BEB44(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    fn_801D0F40();
    (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A40E0;
    (*(u32*)((char*)(arg0)+0x2A8)) = 0;
    (*(u32*)((char*)(arg0)+0x2AA)) = 0;
    (*(u32*)((char*)(arg0)+0x2AC)) = 0;
    (*(u32*)((char*)(arg0)+0x2B0)) = 0;
    (*(u32*)((char*)(arg0)+0x2B4)) = 0;
    return arg0;
}

/* --- auto_fn_801BEB98_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804C7B70;










void fn_801BEB98(void) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804C7B70);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804C7B70 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804C7B70 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804C7B70 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804C7B70 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804C7B70 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804C7B70 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804C7B70 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804C7B70 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_801BEDBC_text.s --- */


extern f32 lbl_8053ED00;

void fn_801BEDBC(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    if (((u8) (*(u32*)((char*)(arg0)+0x11C)) != 0) && !((*(u32*)((char*)(arg0)+0x230)) & 0x2000)) {
        fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x1E, 0, -1, 0, 0, 1, lbl_8053ED00);
        fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x1F, 0, 0, 0, 0, 1, lbl_8053ED00);
        fn_801F0E34(arg0, 0x30061, 0);
        (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) | 0x2000);
    }
}

/* --- auto_fn_801BEE6C_text.s --- */
void *fn_8020D58C();                                /* extern */
u8 fn_8020D6AC(void *, s32, s32, s32, u32, void *);   /* extern */

u8 fn_802265DC(s32, s32, u32);                        /* extern */

s32 fn_801BEE6C(void *arg0, s32 arg1, s32 arg2) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    s32 temp_r31;
    s32 var_r30;
    u16 temp_r3;
    char *temp_r3_2;

    temp_r3 = fn_8022461C(arg2);
    if ((s32) temp_r3 < 0xD) {
        if ((s32) temp_r3 != 3) {
            goto block_5;
        }
        goto block_4;
    }
    if ((s32) temp_r3 < 0xF) {
block_4:
        return 0;
    }
block_5:
    var_r30 = 1;
    if (fn_802265DC(arg2, arg1, 0) == 0) {
        temp_r31 = (*(u32*)((char*)(arg0)+0x90));
        temp_r3_2 = fn_8020D58C();
        if (fn_8020D6AC(temp_r3_2 + (((*(u32*)((char*)(temp_r3_2)+0x1)) * 0x784) + 4), arg1, arg2, temp_r31, 0, temp_r3_2) == 0) {
            var_r30 = 0;
        }
    }
    return var_r30;
}

/* --- auto_fn_801BEF40_text.s --- */

u32 fn_8013CAA4(u32, f32, f32, f32);                  /* extern */


u8 fn_801CCC78(f32 *, s32);                         /* extern */


u32 fn_801F2B7C(void *, s32, u32, u32);                   /* extern */
u32 fn_802A20F0(s32, f32 *, u32, s32, u32, u32);            /* extern */


extern s32 lbl_8053AC98;

extern f32 lbl_8053ED04;
extern f32 lbl_8053ED08;
extern f32 lbl_8053ED0C;

void fn_801BEF40(void *arg0) {
    s32 unksp1B;
    s32 unksp29;
    s32 unksp2A;
    f32 sp40;
    f32 sp3C;
    f32 sp38;
    f32 sp34;
    f32 sp30;
    f32 sp2C;
    f32 sp28;
    f32 sp24;
    f32 sp20;
    f32 sp1C;
    f32 sp18;
    f32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    f32 temp_f1_2;
    f32 temp_f1_3;
    f32 temp_f1_4;
    f32 temp_f1_5;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f2_3;
    f32 temp_f2_4;
    f32 temp_f2_5;
    f32 temp_f3;
    f32 temp_f3_2;
    f32 temp_f3_3;
    f32 temp_f3_4;
    s32 temp_r29;
    s32 temp_r3;
    s32 var_r29;
    s32 var_r30;
    u16 var_r6;
    u8 var_r0;
    char *var_r3;

    if ((*(u32*)((char*)(arg0)+0x230)) & 0x2000) {
        fn_801EE434((*(u32*)((char*)(arg0)+0x2A8)));
        (*(u32*)((char*)(arg0)+0x2A8)) = 0U;
        (*(u32*)((char*)(arg0)+0x11C)) = 0;
        return;
    }
    (*(u32*)((char*)(arg0)+0x24C)) = (s32) ((*(u32*)((char*)(arg0)+0x24C)) + 1);
    if ((s32) (*(u32*)((char*)(arg0)+0x24C)) < 0) {
        (*(u32*)((char*)(arg0)+0x24C)) = 0;
    }
    if (!((*(u32*)((char*)(arg0)+0x230)) & 0x400)) {
        (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) | 0x400);
        ((u32(*)())(*(void**)((char*)(unk0)+0x54)))(arg0);
        return;
    }
    M2C_ERROR(/* unknown instruction: ps_add $f0, $f1, $f0 */);
    M2C_ERROR(/* unknown instruction: ps_add $f0, $f1, $f0 */);
    if ((u32) (*(u32*)((char*)(arg0)+0x2A8)) != 0U) {
        var_r6 = 1;
        if ((s32) (*(u32*)((char*)(arg0)+0x24C)) < 2) {
            var_r6 = (*(u32*)((char*)(arg0)+0x94));
        }
        fn_8013CB44(arg0 + 0xC, 0, var_r6, 1);
        fn_8013CAA4((*(u32*)((char*)(arg0)+0x2A8)), lbl_8053ED08 * (lbl_8053ED0C * (f32) (s16) (fn_80093340(&lbl_80534C00, (*(u32*)((char*)(arg0)+0x3C)), (*(u32*)((char*)(arg0)+0x40))) * lbl_8053ED04)), lbl_8053ED0C, lbl_8053ED08);
    }
    temp_r29 = (*(u32*)((char*)(arg0)+0x4));
    temp_r3 = fn_802D6A9C();
    if (temp_r29 < 8) {
        var_r3 = temp_r3 + 0xCC;
    } else {
        var_r3 = temp_r3 + 0xDC;
    }
    temp_f2 = (*(u32*)((char*)(arg0)+0xC));
    var_r0 = 0;
    M2C_ERROR(/* unknown instruction: cror eq, gt, eq */);
    if (temp_f2 == (*(u32*)((char*)(var_r3)+0x0))) {
        temp_f1 = (*(u32*)((char*)(arg0)+0x10));
        M2C_ERROR(/* unknown instruction: cror eq, gt, eq */);
        if ((temp_f1 == (*(u32*)((char*)(var_r3)+0x4))) && (temp_f2 < (*(u32*)((char*)(var_r3)+0x8))) && (temp_f1 < (*(u32*)((char*)(var_r3)+0xC)))) {
            var_r0 = 1;
        }
    }
    if (var_r0 == 0) {
        (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) | 0x2000);
        return;
    }
    temp_f1_2 = (*(u32*)((char*)(arg0)+0xC));
    temp_f2_2 = (*(u32*)((char*)(arg0)+0x10)) + (*(u32*)((char*)(arg0)+0x84));
    temp_f3 = (*(u32*)((char*)(arg0)+0x14));
    sp3C = temp_f2_2;
    sp38 = temp_f1_2 + (*(u32*)((char*)(arg0)+0x80));
    sp40 = temp_f3;
    if ((((u32(*)())(*(void**)((char*)(unk0)+0x4C)))(arg0, (*(u32*)((char*)(arg0)+0x4)), &sp38, temp_f1_2, temp_f2_2, temp_f3) != 0) || (temp_f1_3 = (*(u32*)((char*)(arg0)+0xC)), temp_f2_3 = (*(u32*)((char*)(arg0)+0x10)) + (*(u32*)((char*)(arg0)+0x84)), temp_f3_2 = (*(u32*)((char*)(arg0)+0x14)), sp30 = temp_f2_3, sp2C = temp_f1_3 + (*(u32*)((char*)(arg0)+0x88)), sp34 = temp_f3_2, ((((u32(*)())(*(void**)((char*)(unk0)+0x4C)))(arg0, (*(u32*)((char*)(arg0)+0x4)), &sp2C, temp_f1_3, temp_f2_3, temp_f3_2) == 0) == 0)) || (temp_f1_4 = (*(u32*)((char*)(arg0)+0xC)), temp_f2_4 = (*(u32*)((char*)(arg0)+0x10)) + (*(u32*)((char*)(arg0)+0x8C)), temp_f3_3 = (*(u32*)((char*)(arg0)+0x14)), sp24 = temp_f2_4, sp20 = temp_f1_4 + (*(u32*)((char*)(arg0)+0x80)), sp28 = temp_f3_3, ((((u32(*)())(*(void**)((char*)(unk0)+0x4C)))(arg0, (*(u32*)((char*)(arg0)+0x4)), &sp20, temp_f1_4, temp_f2_4, temp_f3_3) == 0) == 0)) || (temp_f1_5 = (*(u32*)((char*)(arg0)+0xC)), temp_f2_5 = (*(u32*)((char*)(arg0)+0x10)) + (*(u32*)((char*)(arg0)+0x8C)), temp_f3_4 = (*(u32*)((char*)(arg0)+0x14)), sp18 = temp_f2_5, sp14 = temp_f1_5 + (*(u32*)((char*)(arg0)+0x88)), sp1C = temp_f3_4, ((((u32(*)())(*(void**)((char*)(unk0)+0x4C)))(arg0, (*(u32*)((char*)(arg0)+0x4)), &sp14, temp_f1_5, temp_f2_5, temp_f3_4) == 0) == 0))) {
        var_r29 = 0;
        sp10 = (*(u32*)((char*)(arg0)+0x14));
        sp8 = (*(u32*)((char*)(arg0)+0xC)) + (*(u32*)((char*)(arg0)+0x80));
        do {
            var_r30 = 0;
            spC = (*(u32*)((char*)(arg0)+0x10)) + (*(u32*)((char*)(arg0)+0x84));
loop_26:
            if (fn_801CCC78(&sp8, (*(u32*)((char*)(arg0)+0x4))) != 0) {
                fn_802A20F0(lbl_8053AC98, &sp8, -1, (*(u32*)((char*)(arg0)+0x4)), 0, 0);
            }
            var_r30 += 1;
            spC += (*(u32*)((char*)(arg0)+0x8C)) - (*(u32*)((char*)(arg0)+0x84));
            if (var_r30 < 2) {
                goto loop_26;
            }
            var_r29 += 1;
            sp8 += (*(u32*)((char*)(arg0)+0x88)) - (*(u32*)((char*)(arg0)+0x80));
        } while (var_r29 < 2);
        fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x1E, 0, -1, 0, 0, 1, lbl_8053ED00);
        fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x1F, 0, 0, 0, 0, 1, lbl_8053ED00);
        fn_801F0E34(arg0, 0x30061, 0);
        (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x230)) | 0x2000);
        return;
    }
    fn_801F2B7C(arg0, (*(u32*)((char*)(arg0)+0x114)), -1, 1);
}

