/* Auto-generated by tools/m2c_batch.py */
/* Address range: 0x802E7B04 – 0x802ED140 */
#include "nonmatch.h"
#include "_ps_emu.h"

/* --- auto_fn_802E7B04_text.s --- */
u32 fn_802D6A9C();                                    /* extern */
u8 fn_802D7544(s32);                                /* extern */

void fn_802E7B04(void *arg0) {
    (*(u32*)((char*)(arg0)+0x230)) = (s32) ((*(u32*)((char*)(arg0)+0x90)) & 0xFFF);
    (*(u32*)((char*)(arg0)+0x234)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0xCU) & 0xFFF);
    (*(u32*)((char*)(arg0)+0x238)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x18U) & 1);
    (*(u32*)((char*)(arg0)+0x23C)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x19U) & 1);
    fn_802D6A9C();
    if (fn_802D7544((*(u32*)((char*)(arg0)+0x16C))) != 0) {
        (*(u32*)((char*)(arg0)+0x23C)) = 0;
        (*(u32*)((char*)(arg0)+0x238)) = 0;
    }
    ((u32(*)())(*(void**)((char*)(unk0)+0x14)))(arg0);
}







/* --- auto_fn_802E7B90_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */
u32 fn_80028974(char *);                                 /* extern */
void fn_80021A6C();
void fn_80021AC0();
void fn_80021B14();
void fn_80021B68();
void fn_80021BBC();
void fn_80021C10();
void fn_80021C64();
void fn_80021CB8();
void fn_80021D0C();
extern char lbl_804B21AC;
extern char lbl_804B21BC;
extern char lbl_804B21CC;
extern char lbl_804B21DC;
extern char lbl_804B21EC;
extern char lbl_804B21FC;
extern char lbl_804B220C;
extern char lbl_804B221C;
extern char lbl_804B222C;
extern char lbl_804D52A8;
extern u8 lbl_8053A2AC;
extern u8 lbl_8053A2AD;
extern u8 lbl_8053A2AE;
extern u8 lbl_8053A2AF;
extern u8 lbl_8053A2B0;
extern u8 lbl_8053A2B1;
extern u8 lbl_8053A2B2;
extern u8 lbl_8053A2B3;
extern u8 lbl_8053A2B4;

void fn_802E7B90(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D52A8);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D52A8 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D52A8 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D52A8 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D52A8 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D52A8 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D52A8 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D52A8 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D52A8 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_03_802E7DB4_text.s --- */
void fn_802E7DB4(void) {

}

/* --- auto_fn_802E7DB8_text.s --- */
u32 fn_8013CC50(s32, char *, u32, u32, u32, u32, u32, u32, f32);     /* extern */
void fn_801EE434(void *arg0);                                    /* extern */
u32 fn_801F0E34(void *, u32, u32);                        /* extern */
void fn_801F34DC(void *arg0);                              /* extern */
void *fn_801F666C(s32);                             /* extern */
s32 fn_801F78F4(u32, s32);                            /* extern */
u32 fn_801F856C();                                    /* extern */
u32 fn_802C5284(void *);                              /* extern */
extern f32 lbl_80541260;
extern f32 lbl_80541264;
extern f32 lbl_80541268;
extern f32 lbl_8054126C;

s32 fn_802E7DB8(void *arg0) {
    f32 sp1C;
    f32 sp10;
    u32 sp8;
    f32 temp_f1;
    f32 temp_f28;
    f32 temp_f29;
    f32 temp_f2;
    f32 temp_f30;
    f32 temp_f31;
    f32 temp_f3;
    f32 var_f0;
    f32 var_f1;
    f32 var_f2;
    f32 var_f3;
    s32 temp_cr0_lt;
    s32 temp_r29;
    s32 temp_r3;
    s32 var_r28;
    u8 var_r0;
    char *temp_r3_2;

    temp_f3 = (*(u32*)((char*)(arg0)+0x10));
    var_r28 = -1;
    temp_f2 = (*(u32*)((char*)(arg0)+0xC));
    (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_80541260;
    (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_80541260;
    (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_80541264;
    (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_80541264;
    temp_f31 = (*(u32*)((char*)(arg0)+0x60)) + temp_f2;
    temp_f30 = (*(u32*)((char*)(arg0)+0x64)) + temp_f3;
    temp_f29 = (*(u32*)((char*)(arg0)+0x68)) + temp_f2;
    temp_f28 = (*(u32*)((char*)(arg0)+0x6C)) + temp_f3;
loop_1:
    fn_801F856C();
    temp_r3 = fn_801F78F4(0x4B455930, var_r28);
    temp_r29 = temp_r3;
    temp_cr0_lt = temp_r29 < 0;
    var_r28 = temp_r29;
    if (temp_cr0_lt != 0) {
        return 0;
    }
    fn_801F856C();
    temp_r3_2 = fn_801F666C(temp_r29);
    if ((temp_r3_2 != NULL) && ((s32) (*(u32*)((char*)(temp_r3_2)+0x280)) == 6)) {
        temp_f1 = (*(u32*)((char*)(temp_r3_2)+0x14));
        sp1C = temp_f1;
        if (temp_f1 == lbl_80541268) {
            var_f0 = (*(u32*)((char*)(temp_r3_2)+0x60)) + sp14;
            var_f2 = (*(u32*)((char*)(temp_r3_2)+0x68)) + sp14;
            var_f1 = (*(u32*)((char*)(temp_r3_2)+0x64)) + sp18;
            var_f3 = (*(u32*)((char*)(temp_r3_2)+0x6C)) + sp18;
            M2C_ERROR(/* unknown instruction: cror eq, lt, eq */);
            if (var_f0 == temp_f31) {
                var_f0 = temp_f31;
            }
            M2C_ERROR(/* unknown instruction: cror eq, lt, eq */);
            if (var_f1 == temp_f30) {
                var_f1 = temp_f30;
            }
            M2C_ERROR(/* unknown instruction: cror eq, gt, eq */);
            if (var_f2 == temp_f29) {
                var_f2 = temp_f29;
            }
            M2C_ERROR(/* unknown instruction: cror eq, gt, eq */);
            if (var_f3 == temp_f28) {
                var_f3 = temp_f28;
            }
            var_r0 = 0;
            M2C_ERROR(/* unknown instruction: cror eq, gt, eq */);
            if (var_f2 == var_f0) {
                M2C_ERROR(/* unknown instruction: cror eq, gt, eq */);
                if (var_f3 == var_f1) {
                    var_r0 = 1;
                }
            }
            if (var_r0 != 0) {
                (*(u32*)((char*)(arg0)+0x244)) = 1;
                (*(u32*)((char*)(arg0)+0x24C)) = 0x14;
                sp10 = sp1C;
                if ((u32) (*(u32*)((char*)(arg0)+0x230)) != 0U) {
                    fn_801EE434();
                }
                if ((u32) (*(u32*)((char*)(arg0)+0x234)) != 0U) {
                    fn_801EE434();
                }
                if ((u32) (*(u32*)((char*)(arg0)+0x238)) != 0U) {
                    fn_801EE434();
                }
                if ((u32) (*(u32*)((char*)(arg0)+0x23C)) != 0U) {
                    fn_801EE434();
                }
                if ((u32) (*(u32*)((char*)(arg0)+0x240)) != 0U) {
                    fn_801EE434();
                }
                (*(u32*)((char*)(arg0)+0x230)) = 0U;
                (*(u32*)((char*)(arg0)+0x234)) = 0U;
                (*(u32*)((char*)(arg0)+0x238)) = 0U;
                (*(u32*)((char*)(arg0)+0x23C)) = 0U;
                (*(u32*)((char*)(arg0)+0x240)) = 0U;
                fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp8, 0x85, 0, 0, 0, 0, 1, lbl_8054126C);
                fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp8, 0x86, 0, 0, 0, 0, 1, lbl_8054126C);
                fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp8, 0x87, 0, 0, 0, 0, 1, lbl_8054126C);
                fn_801F0E34(arg0, 0x30069, 0);
                fn_802C5284(temp_r3_2);
                (*(u32*)((char*)(temp_r3_2)+0x11C)) = 0;
                fn_801F34DC(arg0);
                return 1;
            }
            goto loop_1;
        }
    }
    goto loop_1;
}

/* --- auto_fn_802E80A0_text.s --- */
u8 fn_8013CB44(void *arg0, void *arg1, s32 arg2, s32 arg3, u8 arg4);           /* extern */
f32 *fn_8013CC50(s32, void *, u32, u32, u32, u32, u32, f32, f32); /* extern */
void *fn_801F666C(s32);                             /* extern */


void *fn_8023E7B0(s32);                             /* extern */
extern f32 lbl_80539D38;


extern f64 lbl_80541270;
extern f64 lbl_80541278;
extern f64 lbl_80541280;
extern f32 lbl_80541288;

f32 fn_802E80A0(void *arg0) {
    f32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 *temp_r3_5;
    f32 *temp_r3_6;
    f32 *temp_ret_2;
    f32 *temp_ret_3;
    f32 *temp_ret_4;
    f32 temp_f1_4;
    f32 temp_f2;
    f32 temp_f4;
    f32 var_f1;
    f32 var_f4;
    f64 temp_f1;
    f64 temp_f1_2;
    f64 temp_f1_3;
    s32 temp_r3_2;
    s32 temp_ret;
    s32 var_r0;
    s32 var_r0_2;
    s32 var_r27;
    s32 var_r30;
    s32 var_r31;
    s8 temp_r27;
    char *temp_r3;
    char *temp_r3_3;
    char *temp_r3_4;

    var_r31 = -1;
    var_r30 = -1;
    var_r27 = -1;
loop_1:
    fn_801F856C();
    temp_ret = fn_801F78F4(0x4B455930, var_r27);
    var_f1 = (f32) temp_ret;
    var_r27 = temp_ret;
    if (var_r27 >= 0) {
        fn_801F856C();
        temp_r3 = fn_801F666C(var_r27);
        if ((temp_r3 != NULL) && ((s32) (*(u32*)((char*)(temp_r3)+0x280)) == 6) && ((s32) (*(u32*)((char*)(temp_r3)+0x240)) != 0)) {
            sp14 = (*(u32*)((char*)(temp_r3)+0x14));
            temp_f4 = sp10 - (*(u32*)((char*)(arg0)+0x10));
            temp_f2 = spC - (*(u32*)((char*)(arg0)+0xC));
            var_f4 = (temp_f2 * temp_f2) + (temp_f4 * temp_f4);
            if (var_f4 > lbl_80541268) {
                temp_f1 = __frsqrte(var_f4);
                temp_f1_2 = lbl_80541270 * temp_f1 * -(((f64) var_f4 * (temp_f1 * temp_f1)) - lbl_80541278);
                temp_f1_3 = lbl_80541270 * temp_f1_2 * -(((f64) var_f4 * (temp_f1_2 * temp_f1_2)) - lbl_80541278);
                var_f4 = (f32) ((f64) var_f4 * (lbl_80541270 * temp_f1_3 * -(((f64) var_f4 * (temp_f1_3 * temp_f1_3)) - lbl_80541278)));
            } else if (var_f4 < (f32) lbl_80541280) {
                var_f4 = lbl_80539D38;
            } else {
                sp8 = var_f4;
                temp_r3_2 = (s32) sp8 & 0x7F800000;
                switch (temp_r3_2) {                /* irregular */
                case 0x7F800000:
                    if ((s32) sp8 & 0x7FFFFF) {
                        var_r0 = 1;
                    } else {
                        var_r0 = 2;
                    }
                    break;
                case 0x0:
                    if ((s32) sp8 & 0x7FFFFF) {
                        var_r0 = 5;
                    } else {
                        var_r0 = 3;
                    }
                    break;
                default:
                    var_r0 = 4;
                    break;
                }
                if (var_r0 == 1) {
                    var_f4 = lbl_80539D38;
                }
            }
            var_r0_2 = (s32) var_f4;
            if (var_r0_2 > 0x40) {
                var_r0_2 = 0x40;
            }
            if (var_r30 < 0) {
                var_r30 = var_r0_2;
                var_r31 = var_r27;
            } else if (var_r0_2 < var_r30) {
                var_r30 = var_r0_2;
                var_r31 = var_r27;
            }
        }
        goto loop_1;
    }
    if (var_r31 >= 0) {
        fn_801F856C();
        temp_r3_3 = fn_801F666C(var_r31);
        var_f1 = M2C_ERROR(/* psq_l unimplemented */);
        temp_r27 = (0x40 - var_r30) * 4;
        sp14 = (*(u32*)((char*)(temp_r3_3)+0x14));
        if ((f32 *) (*(u32*)((char*)(arg0)+0x238)) == NULL) {
            temp_ret_2 = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), (void *)0x314, 0, 2, 0, 0, 1, lbl_8054126C);
            var_f1 = (f32) temp_ret_2;
            (*(u32*)((char*)(arg0)+0x238)) = temp_ret_2;
        }
        if ((f32 *) (*(u32*)((char*)(arg0)+0x23C)) == NULL) {
            temp_ret_3 = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x312, 0, 0, 0, 0, 1e-45f, lbl_8054126C);
            var_f1 = (f32) temp_ret_3;
            (*(u32*)((char*)(arg0)+0x23C)) = temp_ret_3;
        }
        if ((f32 *) (*(u32*)((char*)(arg0)+0x240)) == NULL) {
            temp_ret_4 = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x313, 0, 0, 0, 0, 1e-45f, lbl_8054126C);
            var_f1 = (f32) temp_ret_4;
            (*(u32*)((char*)(arg0)+0x240)) = temp_ret_4;
        }
        if ((f32 *) (*(u32*)((char*)(arg0)+0x238)) != NULL) {
            if ((u8) (*(u32*)((char*)(temp_r3_3)+0xC4)) != 0) {
                temp_r3_4 = fn_8023E7B0((*(u32*)((char*)(temp_r3_3)+0xC8)));
                spC = (*(u32*)((char*)(temp_r3_4)+0x0));
                sp10 = (*(u32*)((char*)(temp_r3_4)+0x4));
                sp14 = (*(u32*)((char*)(temp_r3_4)+0x8));
                var_f1 = fn_8013CB44((*(u32*)((char*)(arg0)+0x238)), &spC, -1, 3, 1e-45f);
            } else {
                temp_f1_4 = sp14;
                sp14 = temp_f1_4 + lbl_80541288;
                var_f1 = fn_8013CB44(&spC, NULL, 0, 1, temp_f1_4);
            }
            (*(u32*)((char*)((*(u32*)((char*)(arg0)+0x238)))+0xBB)) = temp_r27;
        }
        temp_r3_5 = (*(u32*)((char*)(arg0)+0x23C));
        if (temp_r3_5 != NULL) {
            (*(u32*)((char*)(temp_r3_5)+0xBB)) = temp_r27;
        }
        temp_r3_6 = (*(u32*)((char*)(arg0)+0x240));
        if (temp_r3_6 != NULL) {
            (*(u32*)((char*)(temp_r3_6)+0xBB)) = temp_r27;
        }
    }
    return var_f1;
}

/* --- auto_fn_802E83DC_text.s --- */
void fn_80134DE4(void *arg0, s32 arg1, s32 arg2);                           /* extern */
void *fn_8013CC50(s32, f32 *, u32, u32, u32, u32, u32, u32, f32, f32, f32); /* extern */

u32 fn_801F0D20(u32);                                   /* extern */


void *fn_801F666C(s32);                             /* extern */

u32 fn_801F9484(u32, s32, char *, s32, u32, u32);              /* extern */
s32 fn_8023AF14(f32 *, s32, u32, f32, f32, f32, f32, f32, f32); /* extern */
u8 fn_8023B0F4(s32, f32 *, s32, u32, f32);            /* extern */
u32 fn_8023EE28(s32);                                 /* extern */
s32 fn_8023EEB4(s32);                               /* extern */
s32 fn_8023EF50(s32);                               /* extern */

u8 fn_802D46D8(s32, u32, u32);                          /* extern */
void *fn_802D6A9C();                                /* extern */
u32 fn_802E7DB8(void *);                              /* extern */
u32 fn_802E80A0(void *);                              /* extern */
u32 fn_8043D67C(s32, u32, s32, u32);                      /* extern */
extern char lbl_8046F270;
extern s32 lbl_8053AAF8;
extern s32 lbl_8053AED0;




extern f32 lbl_8054128C;
extern f32 lbl_80541290;
extern f32 lbl_80541294;
extern f32 lbl_80541298;
extern f32 lbl_8054129C;
extern f32 lbl_805412A0;

void fn_802E83DC(void *arg0) {
    f32 sp38;
    f32 sp34;
    f32 sp30;
    f32 sp2C;
    f32 sp28;
    u32 sp20;
    f32 sp1C;
    f32 sp18;
    f32 sp14;
    f32 sp10;
    f32 sp8;
    f32 temp_f0;
    f32 temp_f0_2;
    f32 temp_f0_3;
    f32 temp_f0_4;
    f32 temp_f0_5;
    f32 temp_f0_6;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f30;
    f32 temp_f31;
    f32 temp_f3;
    f32 temp_f3_2;
    f32 temp_f4;
    f32 temp_f4_2;
    f32 temp_f5;
    f32 temp_f6;
    s32 temp_r0;
    s32 temp_r29;
    s32 temp_r29_2;
    s32 temp_r29_3;
    s32 temp_r3_2;
    s32 temp_r4;
    s32 temp_r4_2;
    s32 var_r31;
    char *temp_r3;
    char *temp_r5;
    char *temp_r5_2;
    char *temp_r5_3;
    char *temp_r5_4;
    char *temp_r5_5;

    temp_r0 = (*(u32*)((char*)(arg0)+0x244));
    switch (temp_r0) {                              /* irregular */
    case 0:
        (*(u32*)((char*)(arg0)+0x80)) = (f32) lbl_8054128C;
        (*(u32*)((char*)(arg0)+0x84)) = (f32) lbl_8054128C;
        (*(u32*)((char*)(arg0)+0x88)) = (f32) lbl_80541290;
        (*(u32*)((char*)(arg0)+0x8C)) = (f32) lbl_80541290;
        sp2C = (*(u32*)((char*)(arg0)+0x80));
        sp30 = (*(u32*)((char*)(arg0)+0x84));
        sp34 = (*(u32*)((char*)(arg0)+0x88));
        sp38 = (*(u32*)((char*)(arg0)+0x8C));
        temp_f31 = (*(u32*)((char*)(arg0)+0xC));
        temp_f30 = (*(u32*)((char*)(arg0)+0x10));
        temp_f6 = sp2C + temp_f31;
        sp2C = temp_f6;
        sp30 += temp_f30;
        sp34 += temp_f31;
        sp38 += temp_f30;
        (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_80541294;
        (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_80541294;
        (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_80541298;
        (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_80541298;
        temp_f0 = (*(u32*)((char*)(arg0)+0x60));
        sp2C = temp_f0;
        temp_f4 = temp_f0 + temp_f31;
        temp_f0_2 = (*(u32*)((char*)(arg0)+0x64));
        sp30 = temp_f0_2;
        temp_f3 = temp_f0_2 + temp_f30;
        temp_f0_3 = (*(u32*)((char*)(arg0)+0x68));
        sp34 = temp_f0_3;
        temp_f2 = temp_f0_3 + temp_f31;
        temp_f5 = (*(u32*)((char*)(arg0)+0x6C));
        sp38 = temp_f5;
        sp2C = temp_f4;
        sp30 = temp_f3;
        sp34 = temp_f2;
        sp38 = temp_f5 + temp_f30;
        (*(u32*)((char*)(arg0)+0x250)) = fn_8023AF14(&sp2C, (*(u32*)((char*)(arg0)+0x4)), 0, lbl_80541268, temp_f2, temp_f3, temp_f4, temp_f5, temp_f6);
        if ((s32) (*(u32*)((char*)(arg0)+0x250)) >= 0) {
            if ((void *) (*(u32*)((char*)(arg0)+0x234)) == NULL) {
                temp_f3_2 = (*(u32*)((char*)(arg0)+0x14));
                temp_f2_2 = (*(u32*)((char*)(arg0)+0x10));
                sp14 = (*(u32*)((char*)(arg0)+0xC));
                sp18 = temp_f2_2;
                sp1C = temp_f3_2;
                (*(u32*)((char*)(arg0)+0x234)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp14, 0x2A7, 1, 0, 0, 0, 1, lbl_8054126C, temp_f2_2, temp_f3_2);
                fn_80134DE4(lbl_8053AAF8, 9, 0);
                if (((s32) fn_802D6A9C(*(u32*)((char*)(())+0x4)) == 1) && ((s32) fn_802D6A9C(*(u32*)((char*)(())+0x8)) == 1)) {
                    fn_802D6A9C();
                    if (fn_802D46D8((*(u32*)((char*)(arg0)+0x250)), 0x24E, 0) == 0) {
                        fn_8043D67C(lbl_8053AED0, 0x24E, (*(u32*)((char*)(arg0)+0x250)), 0);
                        fn_802D6A9C();
                        fn_802D46D8((*(u32*)((char*)(arg0)+0x250)), 0x24E, 1);
                    }
                }
            }
            fn_801F0E34(arg0, 0x30050, 0);
        } else {
            if ((void *) (*(u32*)((char*)(arg0)+0x230)) != NULL) {
                fn_801EE434();
                (*(u32*)((char*)(arg0)+0x230)) = NULL;
            }
            if ((void *) (*(u32*)((char*)(arg0)+0x234)) != NULL) {
                fn_801EE434();
                (*(u32*)((char*)(arg0)+0x234)) = NULL;
            }
        }
        fn_802E7DB8(arg0);
        if ((s32) (*(u32*)((char*)(arg0)+0x244)) != 1) {
            var_r31 = 0;
            (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_80541260;
            (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_8054129C;
            (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_80541264;
            (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_805412A0;
            temp_f0_4 = (*(u32*)((char*)(arg0)+0x60));
            sp2C = temp_f0_4;
            temp_f0_5 = (*(u32*)((char*)(arg0)+0x64));
            sp30 = temp_f0_5;
            temp_f0_6 = (*(u32*)((char*)(arg0)+0x68));
            sp34 = temp_f0_6;
            temp_f4_2 = (*(u32*)((char*)(arg0)+0x6C));
            sp38 = temp_f4_2;
            sp2C = temp_f0_4 + temp_f31;
            sp30 = temp_f0_5 + temp_f30;
            sp34 = temp_f0_6 + temp_f31;
            sp38 = temp_f4_2 + temp_f30;
loop_20:
            if ((fn_8023B0F4(var_r31, &sp2C, (*(u32*)((char*)(arg0)+0x4)), 0, lbl_80541268) == 1) && ((u32) (fn_8023EEB4(var_r31) + 0xB4BB0000) == 0x5930U) && (temp_r29 = fn_8023EF50(var_r31), fn_801F856C(), temp_r3 = fn_801F666C(temp_r29), ((temp_r3 == NULL) == 0)) && ((s32) (*(u32*)((char*)(temp_r3)+0x280)) == 6)) {
                sp28 = (*(u32*)((char*)(temp_r3)+0x14));
                (*(u32*)((char*)(arg0)+0x244)) = 1;
                (*(u32*)((char*)(arg0)+0x24C)) = 0x14;
                temp_r29_2 = (*(u32*)((char*)(arg0)+0x4));
                if (temp_r29_2 >= 8) {
                    fn_801F856C();
                    fn_801F9484(0x4B4D5249, temp_r29_2, &sp20, 0, -1, -1);
                } else {
                    sp10 = sp28;
                    if ((void *) (*(u32*)((char*)(arg0)+0x230)) != NULL) {
                        fn_801EE434();
                    }
                    if ((void *) (*(u32*)((char*)(arg0)+0x234)) != NULL) {
                        fn_801EE434();
                    }
                    if ((void *) (*(u32*)((char*)(arg0)+0x238)) != NULL) {
                        fn_801EE434();
                    }
                    if ((void *) (*(u32*)((char*)(arg0)+0x23C)) != NULL) {
                        fn_801EE434();
                    }
                    if ((void *) (*(u32*)((char*)(arg0)+0x240)) != NULL) {
                        fn_801EE434();
                    }
                    (*(u32*)((char*)(arg0)+0x230)) = NULL;
                    (*(u32*)((char*)(arg0)+0x234)) = NULL;
                    (*(u32*)((char*)(arg0)+0x238)) = NULL;
                    (*(u32*)((char*)(arg0)+0x23C)) = NULL;
                    (*(u32*)((char*)(arg0)+0x240)) = NULL;
                    fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp8, 0x85, 0, 0, 0, 0, 1, lbl_8054126C);
                    fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp8, 0x86, 0, 0, 0, 0, 1, lbl_8054126C);
                    fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp8, 0x87, 0, 0, 0, 0, 1, lbl_8054126C);
                    fn_801F0E34(arg0, 0x30069, 0);
                }
                fn_802C5284(temp_r3);
                fn_8023EE28(var_r31);
                fn_801F34DC(arg0);
            } else {
                var_r31 += 1;
                if (var_r31 < 4) {
                    goto loop_20;
                }
            }
        }
        fn_802E80A0(arg0);
        return;
    case 1:
        temp_r4 = (*(u32*)((char*)(arg0)+0x24C));
        if (temp_r4 == 0) {
            (*(u32*)((char*)(arg0)+0x24C)) = 2;
            fn_801F0E34((void *)0x3004F, 0);
            (*(u32*)((char*)(arg0)+0x244)) = 2;
            return;
        }
        (*(u32*)((char*)(arg0)+0x24C)) = (s32) (temp_r4 - 1);
        return;
    case 2:
        (*(u32*)((char*)(arg0)+0x24C)) = (s32) ((*(u32*)((char*)(arg0)+0x24C)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x24C)) == 0) {
            temp_r4_2 = (*(u32*)((char*)(arg0)+0x90));
            temp_r3_2 = temp_r4_2 & 0xFFFFFF00;
            temp_r29_3 = temp_r3_2 | *(&lbl_8046F270 + ((*(u32*)((char*)(arg0)+0x248)) * 4));
            fn_801F856C(temp_r3_2, temp_r4_2);
            fn_801F9484(0x43495243, (*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, temp_r29_3, -1, -1);
            (*(u32*)((char*)(arg0)+0x244)) = 3;
            (*(u32*)((char*)(arg0)+0x24C)) = 0x3C;
            return;
        }
        return;
    case 3:
        (*(u32*)((char*)(arg0)+0x24C)) = (s32) ((*(u32*)((char*)(arg0)+0x24C)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x24C)) == 0) {
            fn_801F0D20(3);
            temp_r5 = (*(u32*)((char*)(arg0)+0x230));
            if (temp_r5 != NULL) {
                (*(u32*)((char*)(temp_r5)+0xF4)) = (s32) ((*(u32*)((char*)(temp_r5)+0xF4)) | 1);
                (*(u32*)((char*)(temp_r5)+0x24)) = 1;
                (*(u32*)((char*)(arg0)+0x230)) = NULL;
            }
            temp_r5_2 = (*(u32*)((char*)(arg0)+0x234));
            if (temp_r5_2 != NULL) {
                (*(u32*)((char*)(temp_r5_2)+0xF4)) = (s32) ((*(u32*)((char*)(temp_r5_2)+0xF4)) | 1);
                (*(u32*)((char*)(temp_r5_2)+0x24)) = 1;
                (*(u32*)((char*)(arg0)+0x234)) = NULL;
            }
            temp_r5_3 = (*(u32*)((char*)(arg0)+0x238));
            if (temp_r5_3 != NULL) {
                (*(u32*)((char*)(temp_r5_3)+0xF4)) = (s32) ((*(u32*)((char*)(temp_r5_3)+0xF4)) | 1);
                (*(u32*)((char*)(temp_r5_3)+0x24)) = 1;
                (*(u32*)((char*)(arg0)+0x238)) = NULL;
            }
            temp_r5_4 = (*(u32*)((char*)(arg0)+0x23C));
            if (temp_r5_4 != NULL) {
                (*(u32*)((char*)(temp_r5_4)+0xF4)) = (s32) ((*(u32*)((char*)(temp_r5_4)+0xF4)) | 1);
                (*(u32*)((char*)(temp_r5_4)+0x24)) = 1;
                (*(u32*)((char*)(arg0)+0x23C)) = NULL;
            }
            temp_r5_5 = (*(u32*)((char*)(arg0)+0x240));
            if (temp_r5_5 != NULL) {
                (*(u32*)((char*)(temp_r5_5)+0xF4)) = (s32) ((*(u32*)((char*)(temp_r5_5)+0xF4)) | 1);
                (*(u32*)((char*)(temp_r5_5)+0x24)) = 1;
                (*(u32*)((char*)(arg0)+0x240)) = NULL;
            }
            (*(u32*)((char*)(arg0)+0x11C)) = 0;
        }
        break;
    }
}

/* --- auto_fn_802E8A64_text.s --- */
u32 dtor_80084580(void *);                            /* extern */
u32 dtor_801F593C(void *, u32);                         /* extern */

extern char lbl_804A9FB0;

void *fn_802E8A64(void *arg0, s16 arg1) {
    if (arg0 != NULL) {
        (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A9FB0;
        if ((u32) (*(u32*)((char*)(arg0)+0x230)) != 0U) {
            fn_801EE434();
        }
        if ((u32) (*(u32*)((char*)(arg0)+0x234)) != 0U) {
            fn_801EE434();
        }
        if ((u32) (*(u32*)((char*)(arg0)+0x238)) != 0U) {
            fn_801EE434();
        }
        if ((u32) (*(u32*)((char*)(arg0)+0x23C)) != 0U) {
            fn_801EE434();
        }
        if ((u32) (*(u32*)((char*)(arg0)+0x240)) != 0U) {
            fn_801EE434();
        }
        dtor_801F593C(arg0, 0);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_802E8B18_text.s --- */

u8 fn_802D75BC(s32);                                /* extern */
void fn_802E8B18(void *arg0) {
    u32 mode;
    u32 check;

    mode = *(u32 *)((char *)arg0 + 0x90) & 7;
    *(u32 *)((char *)arg0 + 0x248) = mode;
    *(u32 *)((char *)arg0 + 0x24C) = 0;
    *(u32 *)((char *)arg0 + 0x264) = 0;
    *(u32 *)((char *)arg0 + 0x254) = 0;
    *(u32 *)((char *)arg0 + 0x268) = 0;
    *(u32 *)((char *)arg0 + 0x258) = 0;
    *(u32 *)((char *)arg0 + 0x26C) = 0;
    *(u32 *)((char *)arg0 + 0x25C) = 0;
    *(u32 *)((char *)arg0 + 0x270) = 0;
    *(u32 *)((char *)arg0 + 0x260) = 0;
    *(u32 *)((char *)arg0 + 0x230) = 0;
    *(u32 *)((char *)arg0 + 0x234) = 0;
    *(u32 *)((char *)arg0 + 0x238) = 0;
    *(u32 *)((char *)arg0 + 0x23C) = 0;
    *(u32 *)((char *)arg0 + 0x240) = 0;
    fn_802D6A9C(mode);
    if (fn_802D75BC(*(u32 *)((char *)arg0 + 0x16C)) == 0) {
        *(u32 *)((char *)arg0 + 0x244) = 0;
        return;
    }
    check = *(u32 *)((char *)arg0 + 0x248);
    if ((check == 0) || (check == 3)) {
        *(u32 *)((char *)arg0 + 0x244) = 1;
        *(u32 *)((char *)arg0 + 0x24C) = 0x14;
        return;
    }
    *(u32 *)((char *)arg0 + 0x11C) = 0;
}


/* --- auto_fn_802E8BD8_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D53A8;










void fn_802E8BD8(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D53A8);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D53A8 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D53A8 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D53A8 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D53A8 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D53A8 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D53A8 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D53A8 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D53A8 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802E8DFC_text.s --- */


extern char lbl_804AA008;

char **fn_802E8DFC(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804AA008;
        dtor_801F593C(0, &lbl_804AA008);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_03_802E8E5C_text.s --- */
void fn_802E8E5C(void) {

}

/* --- auto_fn_802E8E60_text.s --- */

u8 fn_802D7F40(s32);                                /* extern */

void fn_802E8E60(void *arg0) {
    fn_802D6A9C();
    if (fn_802D7F40(((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x16U) & 0x1F) != 0) {
        ((u32(*)())(*(void**)((char*)(unk0)+0x30)))(arg0, 0xFF, 1);
    }
}







/* --- auto_fn_802E8EBC_text.s --- */
void fn_802E8EBC(void **arg0) {
    ((u32(*)())(*(void**)((char*)((*arg0))+0x14)))();
}

/* --- auto_fn_802E8EE8_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D54A8;










void fn_802E8EE8(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D54A8);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D54A8 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D54A8 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D54A8 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D54A8 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D54A8 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D54A8 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D54A8 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D54A8 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802E910C_text.s --- */


extern char lbl_804AA060;

char **fn_802E910C(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804AA060;
        dtor_801F593C(0, &lbl_804AA060);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_03_802E916C_text.s --- */
void fn_802E916C(void) {

}

/* --- auto_fn_802E9170_text.s --- */

u32 fn_802D7F84(s32, u32);                              /* extern */
u8 fn_802D800C(s32);                                /* extern */

void fn_802E9170(void *arg0) {
    s32 temp_r31;

    fn_802D6A9C();
    if (fn_802D800C(((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x16U) & 0x1F) != 0) {
        temp_r31 = ((u32(*)())(*(void**)((char*)(unk0)+0x3C)))(arg0);
        fn_802D6A9C();
        fn_802D7F84(temp_r31, 1);
    }
}

/* --- auto_fn_802E91D8_text.s --- */
void fn_802E91D8(void **arg0) {
    ((u32(*)())(*(void**)((char*)((*arg0))+0x14)))();
}

/* --- auto_fn_802E9204_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D55A8;










void fn_802E9204(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D55A8);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D55A8 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D55A8 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D55A8 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D55A8 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D55A8 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D55A8 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D55A8 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D55A8 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802E9428_text.s --- */


extern char lbl_804AA0FC;

char **fn_802E9428(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804AA0FC;
        dtor_801F593C(0, &lbl_804AA0FC);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_03_802E9488_text.s --- */
void fn_802E9488(void) {

}

/* --- auto_fn_802E948C_text.s --- */
s32 fn_802E948C(void *arg0, s32 arg1, f32 farg0) {
    f32 temp_f0;
    f32 temp_f3;

    temp_f3 = (*(u32*)((char*)(arg0)+0x270));
    if (temp_f3 == farg0) {
        return 0;
    }
    temp_f0 = fabs(temp_f3 - farg0) / (f32) arg1;
    if (temp_f3 < farg0) {
        (*(u32*)((char*)(arg0)+0x278)) = temp_f0;
    } else {
        (*(u32*)((char*)(arg0)+0x278)) = (f32) -temp_f0;
    }
    (*(u32*)((char*)(arg0)+0x274)) = farg0;
    return 1;
}

/* --- auto_fn_802E94F4_text.s --- */
f32 fn_80047090(char *);                               /* extern */
f32 fn_80093340(char *, f32, f32, f32);                /* extern */
u32 fn_8030C7C4(void *, f32 *, f32);                  /* extern */
extern char lbl_8052EBC0;
extern char lbl_80534C00;
extern void *lbl_8053AB10;
extern f32 lbl_805412EC;
extern f32 lbl_805412F8;
extern f32 lbl_805412FC;
extern f32 lbl_80541300;
extern f32 lbl_80541304;
extern f32 lbl_80541308;
extern f32 lbl_8054130C;
extern f32 lbl_80541310;
extern f32 lbl_80541314;

void fn_802E94F4(void *arg0) {
    f32 sp30;
    u32 sp28;
    f32 sp24;
    f32 sp20;
    f32 sp1C;
    f32 sp18;
    f32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    f32 temp_f1_2;
    f32 temp_f1_3;
    f32 temp_f1_4;
    f32 temp_f1_5;
    f32 temp_f1_6;
    f32 temp_f1_7;
    f32 temp_f1_8;
    f32 temp_f1_9;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f2_3;
    f32 temp_f2_4;
    f32 temp_f2_5;
    f32 temp_f2_6;
    f32 temp_f30;
    f32 temp_f31;
    f32 temp_f3;
    f32 temp_f3_2;
    f32 temp_f3_3;
    f32 temp_f3_4;
    f32 temp_f4;
    f32 temp_f5;
    f32 temp_f6;
    f32 temp_f7;
    f32 var_f29;
    s32 temp_r0;
    char *temp_r4;

    temp_f30 = (*(u32*)((char*)(arg0)+0x248));
    temp_f31 = (*(u32*)((char*)(arg0)+0x244));
    if ((u8) (*(u32*)((char*)(arg0)+0x298)) != 0) {
        (*(u32*)((char*)(arg0)+0x250)) = temp_f31;
        (*(u32*)((char*)(arg0)+0x254)) = temp_f30;
    } else {
        sp30 = (*(u32*)((char*)((*(u32*)((char*)(arg0)+0x240)))+0x44));
        temp_f2 = (*(u32*)((char*)(arg0)+0x250)) - temp_f31;
        temp_f1 = (*(u32*)((char*)(arg0)+0x254)) - temp_f30;
        var_f29 = (temp_f2 * temp_f2) + (temp_f1 * temp_f1);
        M2C_ERROR(/* unknown instruction: cror eq, lt, eq */);
        if (var_f29 == lbl_805412EC) {

        } else {
            temp_f3 = (f32) __frsqrte(var_f29);
            var_f29 *= lbl_805412FC * temp_f3 * -((var_f29 * (temp_f3 * temp_f3)) - lbl_80541300);
        }
        temp_f1_2 = fn_80047090(&sp28);
        M2C_ERROR(/* unknown instruction: cror eq, lt, eq */);
        if (var_f29 == (lbl_80541304 * temp_f1_2)) {
            (*(u32*)((char*)(arg0)+0x250)) = temp_f31;
            (*(u32*)((char*)(arg0)+0x254)) = temp_f30;
            (*(u32*)((char*)(arg0)+0x298)) = 1U;
        } else {
            M2C_ERROR(/* unknown instruction: cror eq, lt, eq */);
            if (var_f29 == (lbl_80541308 * temp_f1_2)) {
                temp_f1_3 = (*(u32*)((char*)(arg0)+0x250));
                (*(u32*)((char*)(arg0)+0x250)) = (f32) ((lbl_805412FC * ((*(u32*)((char*)(arg0)+0x244)) - temp_f1_3)) + temp_f1_3);
                temp_f1_4 = (*(u32*)((char*)(arg0)+0x254));
                (*(u32*)((char*)(arg0)+0x254)) = (f32) ((lbl_805412FC * ((*(u32*)((char*)(arg0)+0x248)) - temp_f1_4)) + temp_f1_4);
            } else if ((lbl_8054130C * var_f29) < lbl_80541310) {
                temp_f1_5 = (*(u32*)((char*)(arg0)+0x250));
                (*(u32*)((char*)(arg0)+0x250)) = (f32) ((lbl_8054130C * ((*(u32*)((char*)(arg0)+0x244)) - temp_f1_5)) + temp_f1_5);
                temp_f1_6 = (*(u32*)((char*)(arg0)+0x254));
                (*(u32*)((char*)(arg0)+0x254)) = (f32) ((lbl_8054130C * ((*(u32*)((char*)(arg0)+0x248)) - temp_f1_6)) + temp_f1_6);
            } else {
                temp_f3_2 = (*(u32*)((char*)(arg0)+0x248));
                temp_r0 = ((u32) (s32) (fn_80093340(&lbl_80534C00, temp_f3_2 - (*(u32*)((char*)(arg0)+0x254)), (*(u32*)((char*)(arg0)+0x244)) - (*(u32*)((char*)(arg0)+0x250)), temp_f3_2) * lbl_80541314) >> 2U) & 0x3FF8;
                (*(u32*)((char*)(arg0)+0x250)) = (f32) ((lbl_80541310 * (*(u32*)((char*)((&lbl_8052EBC0 + temp_r0))+0x4))) + (*(u32*)((char*)(arg0)+0x250)));
                (*(u32*)((char*)(arg0)+0x254)) = (f32) ((lbl_80541310 * *(&lbl_8052EBC0 + temp_r0)) + (*(u32*)((char*)(arg0)+0x254)));
            }
        }
    }
    temp_f3_3 = (*(u32*)((char*)(arg0)+0x250));
    temp_f2_2 = (*(u32*)((char*)(arg0)+0x254));
    temp_f5 = temp_f3_3 + lbl_805412EC;
    sp8 = temp_f3_3;
    temp_f4 = temp_f2_2 + lbl_805412F8;
    spC = temp_f2_2;
    sp10 = temp_f5;
    temp_f7 = (f32) temp_f5;
    sp14 = temp_f4;
    temp_r4 = (*(u32*)((char*)(lbl_8053AB10)+0x24));
    temp_f6 = (*(u32*)((char*)(arg0)+0x268));
    sp18 = (*(u32*)((char*)(temp_r4)+0x164));
    sp20 = (*(u32*)((char*)(temp_r4)+0x16C));
    sp1C = (*(u32*)((char*)(temp_r4)+0x168));
    sp24 = (*(u32*)((char*)(temp_r4)+0x170));
    sp8 = temp_f5;
    temp_f3_4 = (sp20 - sp18) * lbl_805412FC;
    spC = temp_f4;
    temp_f1_7 = (sp24 - sp1C) * lbl_805412FC;
    M2C_ERROR(/* unknown instruction: cror eq, gt, eq */);
    if ((temp_f7 + temp_f3_4) == temp_f6) {
        sp10 = temp_f6 - temp_f3_4;
    } else {
        temp_f2_3 = (*(u32*)((char*)(arg0)+0x260));
        M2C_ERROR(/* unknown instruction: cror eq, lt, eq */);
        if ((temp_f7 - temp_f3_4) == temp_f2_3) {
            sp10 = temp_f2_3 + temp_f3_4;
        }
    }
    temp_f2_4 = (*(u32*)((char*)(arg0)+0x26C));
    M2C_ERROR(/* unknown instruction: cror eq, gt, eq */);
    if ((sp14 + temp_f1_7) == temp_f2_4) {
        sp14 = temp_f2_4 - temp_f1_7;
    } else {
        temp_f2_5 = (*(u32*)((char*)(arg0)+0x264));
        M2C_ERROR(/* unknown instruction: cror eq, lt, eq */);
        if ((sp14 - temp_f1_7) == temp_f2_5) {
            sp14 = temp_f2_5 + temp_f1_7;
        }
    }
    temp_f2_6 = (*(u32*)((char*)(arg0)+0x270));
    if (temp_f2_6 != (*(u32*)((char*)(arg0)+0x274))) {
        (*(u32*)((char*)(arg0)+0x270)) = (f32) (temp_f2_6 + (*(u32*)((char*)(arg0)+0x278)));
        if ((*(u32*)((char*)(arg0)+0x278)) < lbl_805412EC) {
            temp_f1_8 = (*(u32*)((char*)(arg0)+0x274));
            if ((*(u32*)((char*)(arg0)+0x270)) < temp_f1_8) {
                (*(u32*)((char*)(arg0)+0x270)) = temp_f1_8;
            }
        } else {
            temp_f1_9 = (*(u32*)((char*)(arg0)+0x274));
            if ((*(u32*)((char*)(arg0)+0x270)) > temp_f1_9) {
                (*(u32*)((char*)(arg0)+0x270)) = temp_f1_9;
            }
        }
    }
    fn_8030C7C4((*(u32*)((char*)(lbl_8053AB10)+0x24)), &sp10, (f32) (s32) (*(u32*)((char*)(arg0)+0x270)));
}

/* --- auto_fn_802E9884_text.s --- */

u32 fn_802D9CB0();                                    /* extern */

s32 fn_802E9884(void *arg0, void *arg1) {
    s32 temp_r0;
    s32 temp_r0_2;
    s32 temp_r0_3;
    s32 temp_r0_4;
    s32 temp_r0_5;
    s32 temp_r3;
    s32 temp_r3_2;
    s32 temp_r4;
    s32 temp_r4_3;
    s32 temp_r4_4;
    s32 temp_r4_6;
    s32 temp_r4_7;
    s32 temp_r5;
    s32 temp_r5_2;
    s32 temp_r6_2;
    u32 temp_r6;
    u32 temp_r7;
    u8 temp_r4_2;
    u8 temp_r4_5;

    temp_r4 = (s32) (*(u32*)((char*)(arg1)+0x0));
    temp_r7 = (u32) temp_r4 >> 0x1FU;
    temp_r6 = (temp_r4 << 0x17) - temp_r7;
    temp_r6_2 = ((temp_r6 << 9) | (temp_r6 >> 0x17U)) + temp_r7;
    temp_r0 = ((s32) (*(u32*)((char*)(arg1)+0x4)) % 384) - 0x1E;
    if ((u8) (*(u32*)((char*)(arg0)+0x297)) == 0) {
        temp_r4_2 = *(*(u32*)((char*)(arg0)+0x290));
        if (temp_r4_2 == 0xFF) {
            (*(u32*)((char*)(arg0)+0x23C)) = 7;
            return 0;
        }
        switch ((s32) temp_r4_2) {                  /* switch 1; irregular */
        case 0:                                     /* switch 1 */
            temp_r4_3 = (s32) ((s32) (*(u32*)((char*)(arg0)+0x270)) * 3) / 4;
            if ((s32) (temp_r0 - ((s32) (((u32) temp_r4_3 >> 0x1FU) + temp_r4_3) >> 1)) < 0x10) {
                return 1;
            }
            goto block_39;
        case 1:                                     /* switch 1 */
            temp_r4_4 = (s32) ((s32) (*(u32*)((char*)(arg0)+0x270)) * 3) / 4;
            if ((s32) (temp_r0 + ((s32) (((u32) temp_r4_4 >> 0x1FU) + temp_r4_4) >> 1)) > 0x170) {
                return 1;
            }
            goto block_39;
        case 2:                                     /* switch 1 */
            temp_r3 = (s32) (*(u32*)((char*)(arg0)+0x270));
            if ((s32) (temp_r6_2 - ((s32) (((u32) temp_r3 >> 0x1FU) + temp_r3) >> 1)) < 0x10) {
                return 1;
            }
            goto block_39;
        case 3:                                     /* switch 1 */
            temp_r3_2 = (s32) (*(u32*)((char*)(arg0)+0x270));
            if ((s32) (temp_r6_2 + ((s32) (((u32) temp_r3_2 >> 0x1FU) + temp_r3_2) >> 1)) > 0x1F0) {
                return 1;
            }
            goto block_39;
        }
    } else {
        temp_r4_5 = (*(u32*)((char*)(arg0)+0x28D));
        switch ((s32) temp_r4_5) {                  /* switch 2; irregular */
        case 0:                                     /* switch 2 */
            temp_r5 = (s32) ((s32) (*(u32*)((char*)(arg0)+0x270)) * 3) / 4;
            temp_r0_2 = temp_r0 + ((s32) (((u32) temp_r5 >> 0x1FU) + temp_r5) >> 1);
            if ((temp_r0_2 < 0x170) && (temp_r0_2 > 0x160)) {
                (*(u32*)((char*)(arg0)+0x297)) = 0U;
            }
            break;
        case 1:                                     /* switch 2 */
            temp_r5_2 = (s32) ((s32) (*(u32*)((char*)(arg0)+0x270)) * 3) / 4;
            temp_r0_3 = temp_r0 - ((s32) (((u32) temp_r5_2 >> 0x1FU) + temp_r5_2) >> 1);
            if ((temp_r0_3 > 0x20) && (temp_r0_3 < 0x30)) {
                (*(u32*)((char*)(arg0)+0x297)) = 0U;
            }
            break;
        case 2:                                     /* switch 2 */
            temp_r4_6 = (s32) (*(u32*)((char*)(arg0)+0x270));
            temp_r0_4 = temp_r6_2 + ((s32) (((u32) temp_r4_6 >> 0x1FU) + temp_r4_6) >> 1);
            if ((temp_r0_4 < 0x1F0) && (temp_r0_4 > 0x1E0)) {
                (*(u32*)((char*)(arg0)+0x297)) = 0U;
            }
            break;
        case 3:                                     /* switch 2 */
            temp_r4_7 = (s32) (*(u32*)((char*)(arg0)+0x270));
            temp_r0_5 = temp_r6_2 - ((s32) (((u32) temp_r4_7 >> 0x1FU) + temp_r4_7) >> 1);
            if ((temp_r0_5 > 0x10) && (temp_r0_5 < 0x20)) {
                (*(u32*)((char*)(arg0)+0x297)) = 0U;
            }
            break;
        }
        if ((u8) (*(u32*)((char*)(arg0)+0x297)) == 0) {
            fn_802D6A9C();
            fn_802D9CB0();
        }
block_39:
        return 0;
    }
}

/* --- auto_fn_802E9B6C_text.s --- */
/*
Decompilation failure in function fn_802E9B6C:

Found bctr instruction at auto_fn_802E9B6C_text.s line 59, but the corresponding jump table is not provided.

Please include it in the input .s file(s), or in an additional file.

*/

/* --- auto_fn_802EACC8_text.s --- */
void *fn_802D6A9C();                                /* extern */
s8 fn_8044B80C(s32, u8);                            /* extern */
u32 fn_80458FF0(s32, u32, u32, u32, u32, f32);                /* extern */
extern s32 lbl_8053AF30;
extern s32 lbl_8053AF80;

extern f32 lbl_80541318;

void fn_802EACC8(void *arg0) {
    (*(u32*)((char*)(arg0)+0x284)) = (s32) fn_802D6A9C(*(u32*)((char*)(())+0x4));
    (*(u32*)((char*)(arg0)+0x280)) = (s32) fn_802D6A9C(*(u32*)((char*)(())+0x8));
    (*(u32*)((char*)(arg0)+0x23C)) = 0;
    (*(u32*)((char*)(arg0)+0x230)) = 0;
    (*(u32*)((char*)(arg0)+0x28D)) = 0;
    (*(u32*)((char*)(arg0)+0x298)) = 0;
    (*(u32*)((char*)(arg0)+0x240)) = 0;
    (*(u32*)((char*)(arg0)+0x294)) = 0U;
    (*(u32*)((char*)(arg0)+0x295)) = 0;
    (*(u32*)((char*)(arg0)+0x299)) = 1;
    (*(u32*)((char*)(arg0)+0x270)) = (f32) lbl_80541318;
    (*(u32*)((char*)(arg0)+0x274)) = (f32) lbl_80541318;
    (*(u32*)((char*)(arg0)+0x278)) = (f32) lbl_805412EC;
    fn_80458FF0(lbl_8053AF80, 0x01000028, 1, 0, 0, lbl_80541318);
    (*(u32*)((char*)(arg0)+0x234)) = 0;
    (*(u32*)((char*)(arg0)+0x231)) = 0;
    (*(u32*)((char*)(arg0)+0x29A)) = fn_8044B80C(lbl_8053AF30, (*(u32*)((char*)(arg0)+0x294)));
}

/* --- auto_fn_802EAD78_text.s --- */
u32 __register_global_object(char *, char *, void *);       /* extern */



















extern char lbl_804D56A8;









extern f32 lbl_80541338;
extern f32 lbl_8054133C;
extern f32 lbl_80541340;
extern f32 lbl_80541344;
extern f32 lbl_80541348;
extern f32 lbl_8054134C;
extern f32 lbl_80541350;
extern f32 lbl_80541354;
extern f32 lbl_80541358;
extern f32 lbl_8054135C;
extern f32 lbl_80541360;
extern f32 lbl_80541364;
extern f32 lbl_80541368;
extern f32 lbl_8054136C;
extern f32 lbl_80541370;
extern f32 lbl_80541374;
extern f32 lbl_80541378;
extern f32 lbl_8054137C;
extern f32 lbl_80541380;
extern f32 lbl_80541384;
extern f32 lbl_80541388;
extern f32 lbl_8054138C;
extern f32 lbl_80541390;
extern f32 lbl_80541394;
extern f32 lbl_80541398;
extern f32 lbl_8054139C;
extern f32 lbl_805413A0;
extern f32 lbl_805413A4;
extern f32 lbl_805413A8;
extern f32 lbl_805413AC;

void fn_802EAD78(void) {
    char *temp_r3;

    temp_r3 = &lbl_804D56A8 + 0x88;
    (*(u32*)((char*)&lbl_804D56A8+0x0)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x4)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x8)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0xC)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x10)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x14)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x18)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x1C)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x20)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x24)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x28)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x2C)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x30)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x34)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x38)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x3C)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x40)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x44)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x48)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x4C)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x50)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x54)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x58)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x5C)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x60)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x64)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x68)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x6C)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x70)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x74)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x78)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x7C)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x80)) = (f32) lbl_80541338;
    (*(u32*)((char*)&lbl_804D56A8+0x84)) = (f32) lbl_8054133C;
    (*(u32*)((char*)&lbl_804D56A8+0x88)) = (f32) lbl_80541340;
    (*(u32*)((char*)(temp_r3)+0x4)) = (f32) lbl_80541344;
    (*(u32*)((char*)(temp_r3)+0x8)) = (f32) lbl_80541348;
    (*(u32*)((char*)(temp_r3)+0xC)) = (f32) lbl_8054134C;
    (*(u32*)((char*)(temp_r3)+0x10)) = (f32) lbl_80541350;
    (*(u32*)((char*)(temp_r3)+0x14)) = (f32) lbl_8054134C;
    (*(u32*)((char*)(temp_r3)+0x18)) = (f32) lbl_80541354;
    (*(u32*)((char*)(temp_r3)+0x1C)) = (f32) lbl_80541358;
    (*(u32*)((char*)(temp_r3)+0x20)) = (f32) lbl_8054135C;
    (*(u32*)((char*)(temp_r3)+0x24)) = (f32) lbl_80541360;
    (*(u32*)((char*)(temp_r3)+0x28)) = (f32) lbl_80541364;
    (*(u32*)((char*)(temp_r3)+0x2C)) = (f32) lbl_80541368;
    (*(u32*)((char*)(temp_r3)+0x30)) = (f32) lbl_8054136C;
    (*(u32*)((char*)(temp_r3)+0x34)) = (f32) lbl_80541370;
    (*(u32*)((char*)(temp_r3)+0x38)) = (f32) lbl_80541374;
    (*(u32*)((char*)(temp_r3)+0x3C)) = (f32) lbl_80541378;
    (*(u32*)((char*)(temp_r3)+0x40)) = (f32) lbl_8054137C;
    (*(u32*)((char*)(temp_r3)+0x44)) = (f32) lbl_80541380;
    (*(u32*)((char*)(temp_r3)+0x48)) = (f32) lbl_80541374;
    (*(u32*)((char*)(temp_r3)+0x4C)) = (f32) lbl_80541384;
    (*(u32*)((char*)(temp_r3)+0x50)) = (f32) lbl_80541374;
    (*(u32*)((char*)(temp_r3)+0x54)) = (f32) lbl_80541388;
    (*(u32*)((char*)(temp_r3)+0x58)) = (f32) lbl_80541374;
    (*(u32*)((char*)(temp_r3)+0x5C)) = (f32) lbl_8054138C;
    (*(u32*)((char*)(temp_r3)+0x60)) = (f32) lbl_80541374;
    (*(u32*)((char*)(temp_r3)+0x64)) = (f32) lbl_80541390;
    (*(u32*)((char*)(temp_r3)+0x68)) = (f32) lbl_80541394;
    (*(u32*)((char*)(temp_r3)+0x6C)) = (f32) lbl_80541398;
    (*(u32*)((char*)(temp_r3)+0x70)) = (f32) lbl_8054139C;
    (*(u32*)((char*)(temp_r3)+0x74)) = (f32) lbl_805413A0;
    (*(u32*)((char*)(temp_r3)+0x78)) = (f32) lbl_80541374;
    (*(u32*)((char*)(temp_r3)+0x7C)) = (f32) lbl_805413A4;
    (*(u32*)((char*)(temp_r3)+0x80)) = (f32) lbl_805413A8;
    (*(u32*)((char*)(temp_r3)+0x84)) = (f32) lbl_805413AC;
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D56A8 + 0x110);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D56A8 + 0x11C);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D56A8 + 0x128);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D56A8 + 0x134);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D56A8 + 0x140);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D56A8 + 0x14C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D56A8 + 0x158);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D56A8 + 0x164);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D56A8 + 0x170);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802EB21C_text.s --- */


extern char lbl_804AA178;

char **fn_802EB21C(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804AA178;
        dtor_801F593C(0, &lbl_804AA178);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_802EB27C_text.s --- */
s32 fn_801597B8();                                  /* extern */
u32 fn_801597C0(s32);                                 /* extern */
s32 fn_801F666C(s32);                               /* extern */


s32 fn_802EB27C(void *arg0) {
    s32 temp_r30;
    s32 temp_r3;
    s32 var_r28;
    s32 var_r29;
    char *var_r31;

    var_r31 = arg0;
    var_r29 = 0;
    var_r28 = 0;
    do {
        temp_r30 = (*(u32*)((char*)(var_r31)+0x24C));
        if (temp_r30 >= 0) {
            fn_801F856C();
            temp_r3 = fn_801F666C(temp_r30);
            if ((temp_r3 != 0) && (fn_801597B8() == 3)) {
                fn_801597C0(temp_r3);
                var_r29 = 1;
            }
        }
        var_r28 += 1;
        var_r31 += 4;
    } while (var_r28 < 4);
    return var_r29;
}

/* --- auto_fn_802EB314_text.s --- */
s32 fn_80138A30(void *);                            /* extern */

s32 fn_801CD664(u32);                                 /* extern */
s32 fn_801F6058(s32 arg0, s32 arg1);                               /* extern */


s32 fn_8022F3DC(s32);                               /* extern */
u8 fn_8022F514(s32);                                /* extern */
u8 fn_8023077C();                                   /* extern */
u8 fn_802308E0(s32);                                /* extern */
u32 fn_80230FD0(s32, u32);                              /* extern */
s32 fn_8023DE58(s32 arg0);                          /* extern */
void *fn_8023E724(s32);                             /* extern */
u32 fn_802A3948(s32, void *, u32, s32, u32);              /* extern */
s32 fn_802D4C10(s32, u16);                          /* extern */

u32 fn_802D7D00(s32, s32, u32);                         /* extern */
u32 fn_8037AE30(s32);                                 /* extern */
extern char lbl_8050EC80;
extern char lbl_80529DEC;
extern void *lbl_8053AAF8;
extern s32 lbl_8053AC98;
extern s32 lbl_8053AD70;
extern f32 lbl_805413B0;
extern f32 lbl_805413B4;
extern f32 lbl_805413B8;
extern f32 lbl_805413BC;

s32 fn_802EB314(void *arg0) {
    f32 sp34;
    f32 sp28;
    f32 sp24;
    f32 sp20;
    f32 sp1C;
    f32 sp18;
    f32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f2_3;
    f32 temp_f30;
    f32 temp_f31;
    f32 temp_f3;
    f32 temp_f3_2;
    s32 temp_r0;
    s32 temp_r0_2;
    s32 temp_r0_3;
    s32 temp_r0_4;
    s32 temp_r0_5;
    s32 temp_r26;
    s32 temp_r27;
    s32 temp_r27_2;
    s32 temp_r27_3;
    s32 temp_r27_4;
    s32 temp_r27_5;
    s32 temp_r27_6;
    s32 temp_r27_7;
    s32 temp_r27_8;
    s32 temp_r28;
    s32 temp_r28_2;
    s32 temp_r28_3;
    s32 temp_r28_4;
    s32 temp_r28_5;
    s32 temp_r28_6;
    s32 temp_r28_7;
    s32 temp_r30;
    s32 temp_r3;
    s32 temp_r4;
    s32 temp_r4_2;
    s32 temp_r4_3;
    s32 temp_r4_4;
    s32 temp_r4_5;
    s32 var_r26;
    s32 var_r26_2;
    s32 var_r30;
    s32 var_r31;
    u32 var_r0;
    u8 var_r27;

    var_r26 = 0;
    var_r27 = 0;
    if ((u8) (*(u32*)((char*)(lbl_8053AAF8)+0x7E)) == 1) {
        if (fn_802308E0((*(u32*)((char*)(arg0)+0x240))) == 1) {
            var_r27 = 1;
        }
    } else if (fn_8023077C() == 1) {
        fn_8037AE30(lbl_8053AD70);
        var_r27 = 1;
    }
    if (var_r27 == 1) {
        if ((u8) (*(u32*)((char*)(lbl_8053AAF8)+0x7E)) == 1) {
            if (((s32) (*(u32*)((char*)&lbl_80529DEC+0x118)) < 0) || ((s32) (*(u32*)((char*)&lbl_80529DEC+0x118)) > 7)) {
                var_r0 = 0;
            } else if (((s32) (*(u32*)((char*)&lbl_80529DEC+0x11C)) < 0) || ((s32) (*(u32*)((char*)&lbl_80529DEC+0x11C)) > 3)) {
                var_r0 = 0;
            } else {
                temp_r4 = (1 << ((*(u32*)((char*)&lbl_80529DEC+0x11C)) + ((*(u32*)((char*)&lbl_80529DEC+0x118)) * 4))) & (*(u32*)((char*)((&lbl_8050EC80 + ((*(u32*)((char*)&lbl_8050EC80+0x10)) * 0xC8)))+0x28));
                var_r0 = (u32) (-temp_r4 | temp_r4) >> 0x1FU;
            }
            if (((s32) var_r0 != 0) && ((temp_r0 = (*(u32*)((char*)(arg0)+0x234)), ((temp_r0 > 2) == 0)) || (temp_r0 == 0x2F))) {
                temp_r30 = fn_80138A30();
                fn_801F856C();
                if ((s32) (*(u32*)((char*)(arg0)+0x240)) == fn_801F6058(temp_r30 - 1)) {
                    var_r26_2 = 0x14;
                    if (fn_80138A30(lbl_8053AAF8) == 3) {
                        var_r26_2 = 0x1E;
                    } else if (fn_80138A30(lbl_8053AAF8) == 4) {
                        var_r26_2 = 0x32;
                    }
                    if (fn_801CD664(0x64) <= var_r26_2) {
                        (*(u32*)((char*)(arg0)+0x234)) = 0x20;
                    }
                }
            }
        }
        temp_f30 = lbl_805413B0;
        var_r30 = 0;
        temp_f31 = lbl_805413B4;
        var_r31 = 0;
        do {
            temp_f2 = fn_8023E724(*(u32*)((char*)((var_r30))+0x8));
            sp28 = temp_f2;
            sp20 = temp_f30 + sp2C;
            sp24 = sp30 - temp_f31;
            sp28 = temp_f2;
            temp_r28 = (*(u32*)((char*)(arg0)+0x234));
            sp34 = temp_f2;
            if (temp_r28 >= 0x30) {
                if ((u8) (*(u32*)((char*)(lbl_8053AAF8)+0x7E)) == 1) {
                    if (fn_8022F514(var_r30) == 1) {
                        if ((s32) (*(u32*)((char*)(arg0)+0x248)) == fn_8022F3DC(var_r30)) {
                            temp_r0_2 = (*(u32*)((char*)(arg0)+0x240));
                            if (var_r30 == temp_r0_2) {
                                temp_r27 = (*(u32*)((char*)(arg0)+0x234)) + (var_r31 + (temp_r0_2 << 0x1A));
                                temp_r28_2 = fn_8023DE58(var_r30);
                                fn_801F856C();
                                fn_801F9484(0x494D5550, temp_r28_2, &sp20, temp_r27, -1, -1);
                            } else {
                                temp_r4_2 = var_r31 + (temp_r0_2 << 0x1A);
                                temp_r28_3 = (*(u32*)((char*)(arg0)+0x234)) + (temp_r4_2 + 0x10000000);
                                temp_r27_2 = fn_8023DE58(var_r30, temp_r4_2);
                                fn_801F856C();
                                fn_801F9484(0x494D5550, temp_r27_2, &sp20, temp_r28_3, -1, -1);
                            }
                        }
                    } else if (var_r30 == (s32) (*(u32*)((char*)(arg0)+0x248))) {
                        temp_r0_3 = (*(u32*)((char*)(arg0)+0x240));
                        if (var_r30 == temp_r0_3) {
                            temp_r28_4 = (*(u32*)((char*)(arg0)+0x234)) + (var_r31 + (temp_r0_3 << 0x1A));
                            temp_r27_3 = fn_8023DE58(var_r30);
                            fn_801F856C();
                            fn_801F9484(0x494D5550, temp_r27_3, &sp20, temp_r28_4, -1, -1);
                        } else {
                            temp_r4_3 = var_r31 + (temp_r0_3 << 0x1A);
                            temp_r28_5 = (*(u32*)((char*)(arg0)+0x234)) + (temp_r4_3 + 0x10000000);
                            temp_r27_4 = fn_8023DE58(var_r30, temp_r4_3);
                            fn_801F856C();
                            fn_801F9484(0x494D5550, temp_r27_4, &sp20, temp_r28_5, -1, -1);
                        }
                    }
                } else {
                    temp_r26 = (*(u32*)((char*)(arg0)+0x240));
                    if (var_r30 == temp_r26) {
                        temp_r27_5 = fn_8023DE58(var_r30);
                        fn_801F856C();
                        fn_801F9484(0x494D5550, temp_r27_5, &sp20, temp_r28 + (var_r31 + (temp_r26 << 0x1A)), -1, -1);
                    } else {
                        temp_r27_6 = fn_8023DE58(var_r30);
                        fn_801F856C();
                        fn_801F9484(0x494D5550, temp_r27_6, &sp20, temp_r28 + (var_r31 + (temp_r26 << 0x1A) + 0x10000000), -1, -1);
                    }
                }
            } else if ((fn_8022F514(var_r30) == 1) && ((s32) (*(u32*)((char*)(arg0)+0x248)) == fn_8022F3DC(var_r30))) {
                temp_r0_4 = (*(u32*)((char*)(arg0)+0x240));
                if (var_r30 == temp_r0_4) {
                    temp_r4_4 = var_r31 + (temp_r0_4 << 0x1A);
                    temp_r28_6 = (*(u32*)((char*)(arg0)+0x234)) + (temp_r4_4 + 0x800000);
                    temp_r27_7 = fn_8023DE58(var_r30, temp_r4_4);
                    fn_801F856C();
                    fn_801F9484(0x494D5550, temp_r27_7, &sp20, temp_r28_6, -1, -1);
                }
            } else if (var_r30 == (s32) (*(u32*)((char*)(arg0)+0x248))) {
                temp_r0_5 = (*(u32*)((char*)(arg0)+0x240));
                if (var_r30 == temp_r0_5) {
                    temp_r4_5 = var_r31 + (temp_r0_5 << 0x1A);
                    temp_r28_7 = (*(u32*)((char*)(arg0)+0x234)) + (temp_r4_5 + 0x800000);
                    temp_r27_8 = fn_8023DE58(var_r30, temp_r4_5);
                    fn_801F856C();
                    fn_801F9484(0x494D5550, temp_r27_8, &sp20, temp_r28_7, -1, -1);
                }
            }
            var_r30 += 1;
            var_r31 += 0x01000000;
        } while (var_r30 < 4);
        if ((s32) (*(u32*)((char*)(arg0)+0x238)) == 0) {
            fn_80230FD0((*(u32*)((char*)(arg0)+0x240)), 0x20013);
            fn_802A3948(lbl_8053AC98, arg0 + 0x25C, 0, (*(u32*)((char*)(arg0)+0x4)), 0x10);
            fn_802D6A9C();
            temp_r3 = fn_802D4C10((*(u32*)((char*)(arg0)+0x4)), (u16) (*(u32*)((char*)(arg0)+0x23C)));
            if (temp_r3 != -1) {
                fn_802D6A9C();
                fn_802D7D00((*(u32*)((char*)(arg0)+0x4)), temp_r3, 1);
            }
            temp_f3 = lbl_805413B8 + (*(u32*)((char*)(arg0)+0x260));
            temp_f2_2 = lbl_805413B8 + (*(u32*)((char*)(arg0)+0x25C));
            sp1C = lbl_805413BC;
            sp14 = temp_f2_2;
            sp18 = temp_f3;
            fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp14, 0xD0, 0, 0, 0, 0, 1, lbl_805413B0, temp_f2_2, temp_f3);
            temp_f3_2 = lbl_805413B8 + (*(u32*)((char*)(arg0)+0x260));
            temp_f2_3 = lbl_805413B8 + (*(u32*)((char*)(arg0)+0x25C));
            sp10 = lbl_805413BC;
            sp8 = temp_f2_3;
            spC = temp_f3_2;
            fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp8, 0xD1, 0, 1, 0, 0, 1, lbl_805413B0, temp_f2_3, temp_f3_2);
        }
        var_r26 = 1;
    }
    return var_r26;
}

/* --- auto_03_802EB908_text.s --- */
void fn_802EB908(void) {

}

/* --- auto_fn_802EB90C_text.s --- */


s32 fn_8022EA0C(s32);                               /* extern */


u32 fn_8022FEB8(f32 *, s32, s32, u32, u32, f32, f32, f32, f32); /* extern */
s32 fn_80230CFC(s32);                               /* extern */


void *fn_8023E724(s32);                             /* extern */
u8 fn_8023EFEC(s32);                                /* extern */

u16 fn_802F9908(s32, s32, s32);                     /* extern */
u32 fn_80309D6C(s32, s32, u32);                       /* extern */
s32 fn_8030AAF4(s32);                               /* extern */
extern void *lbl_8053AB10;
extern s32 lbl_8053AD30;



extern f32 lbl_805413C0;
extern f32 lbl_805413C4;
extern f32 lbl_805413C8;
extern f32 lbl_805413CC;
extern f32 lbl_805413D0;
extern f32 lbl_805413D4;
extern f32 lbl_805413D8;
extern f32 lbl_805413DC;
extern f32 lbl_805413E0;
extern f32 lbl_805413E4;

void fn_802EB90C(void *arg0) {
    f32 sp2C;
    f32 sp28;
    f32 sp24;
    f32 sp20;
    f32 sp1C;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f0;
    f32 temp_f0_2;
    f32 temp_f0_3;
    f32 temp_f0_4;
    f32 temp_f0_5;
    f32 temp_f0_6;
    f32 temp_f1;
    f32 temp_f1_2;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f2_3;
    f32 temp_f30;
    f32 temp_f30_2;
    f32 temp_f31;
    f32 temp_f31_2;
    f32 temp_f3;
    f32 temp_f3_2;
    f32 temp_f4;
    f32 temp_f4_2;
    f32 temp_f5;
    s32 temp_r0;
    s32 temp_r0_2;
    s32 temp_r0_3;
    s32 temp_r26;
    s32 temp_r27;
    s32 temp_r29;
    s32 temp_r29_2;
    s32 temp_r4;
    s32 temp_r4_2;
    s32 var_r29;
    s32 var_r31;
    u8 var_r26;
    char *var_r30;

    temp_f30 = (*(u32*)((char*)(arg0)+0x10));
    temp_f31 = (*(u32*)((char*)(arg0)+0xC));
    temp_r29 = (*(u32*)((char*)(arg0)+0x4));
    if ((u8) (*(u32*)((char*)((fn_802D6A9C() + 0x10000 + temp_r29))+0x31DF)) != 0) {
        (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_805413C0;
        (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_805413C4;
        (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_805413C8;
        (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_805413CC;
    } else {
        (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_805413D0;
        (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_805413BC;
        (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_805413D4;
        (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_805413CC;
    }
    temp_f0 = (*(u32*)((char*)(arg0)+0x60));
    sp20 = temp_f0;
    temp_f4 = temp_f0 + temp_f31;
    temp_f0_2 = (*(u32*)((char*)(arg0)+0x64));
    sp24 = temp_f0_2;
    temp_f3 = temp_f0_2 + temp_f30;
    temp_f0_3 = (*(u32*)((char*)(arg0)+0x68));
    sp28 = temp_f0_3;
    temp_f2 = temp_f0_3 + temp_f31;
    temp_f5 = (*(u32*)((char*)(arg0)+0x6C));
    sp2C = temp_f5;
    sp20 = temp_f4;
    sp24 = temp_f3;
    sp28 = temp_f2;
    sp2C = temp_f5 + temp_f30;
    (*(u32*)((char*)(arg0)+0x240)) = fn_8023AF14(&sp20, (*(u32*)((char*)(arg0)+0x4)), 0, lbl_805413BC, temp_f2, temp_f3, temp_f4, temp_f5);
    temp_r0 = (*(u32*)((char*)(arg0)+0x230));
    switch (temp_r0) {                              /* irregular */
    case 0:
        if (fn_802F9908((*(u32*)((char*)(lbl_8053AB10)+0x20)), (*(u32*)((char*)(arg0)+0x4)), (*(u32*)((char*)(arg0)+0x23C))) == 0x30) {
            (*(u32*)((char*)(arg0)+0x230)) = 1;
            return;
        }
    case 4:
        return;
    case 1:
        var_r26 = 0;
        if ((s32) (*(u32*)((char*)(arg0)+0x240)) >= 0) {
            temp_r29_2 = (*(u32*)((char*)(arg0)+0x4));
            if ((u8) (*(u32*)((char*)((fn_802D6A9C() + 0x10000 + temp_r29_2))+0x31DF)) != 0) {
                if ((fn_80230CFC((*(u32*)((char*)(arg0)+0x240))) == 3) || (fn_80230CFC((*(u32*)((char*)(arg0)+0x240))) == 0) || (fn_80230CFC((*(u32*)((char*)(arg0)+0x240))) == 1)) {
                    var_r26 = 1;
                }
            } else if (fn_80230CFC((*(u32*)((char*)(arg0)+0x240))) == 3) {
                var_r26 = 1;
            }
            if (var_r26 == 1) {
                (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_805413D8;
                (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_805413DC;
                (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_805413E0;
                (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_805413E4;
                temp_f0_4 = (*(u32*)((char*)(arg0)+0x60));
                sp20 = temp_f0_4;
                temp_f3_2 = temp_f0_4 + temp_f31;
                temp_f0_5 = (*(u32*)((char*)(arg0)+0x64));
                sp24 = temp_f0_5;
                temp_f2_2 = temp_f0_5 + temp_f30;
                temp_f0_6 = (*(u32*)((char*)(arg0)+0x68));
                sp28 = temp_f0_6;
                temp_f1 = temp_f0_6 + temp_f31;
                temp_f4_2 = (*(u32*)((char*)(arg0)+0x6C));
                sp2C = temp_f4_2;
                sp20 = temp_f3_2;
                sp24 = temp_f2_2;
                sp28 = temp_f1;
                sp2C = temp_f4_2 + temp_f30;
                fn_8022FEB8(&sp20, (*(u32*)((char*)(arg0)+0x4)), (*(u32*)((char*)(arg0)+0x198)), 1, 1, temp_f1, temp_f2_2, temp_f3_2, temp_f4_2);
            }
            (*(u32*)((char*)(arg0)+0x248)) = (s32) (*(u32*)((char*)(arg0)+0x240));
            if (fn_8022F514((*(u32*)((char*)(arg0)+0x240))) != 0) {
                (*(u32*)((char*)(arg0)+0x248)) = fn_8022F3DC((*(u32*)((char*)(arg0)+0x240)));
            }
            if ((var_r26 == 1) && (fn_8023EFEC((*(u32*)((char*)(arg0)+0x240))) == 0) && ((s32) (*(u32*)((char*)(arg0)+0x240)) == fn_8022EA0C((*(u32*)((char*)(arg0)+0x240)))) && (fn_80309D6C(lbl_8053AD30, fn_8030AAF4((*(u32*)((char*)(arg0)+0x248))), 0x100) != 0U) && (((u32(*)())(*(void**)((char*)(unk0)+0x54)))(arg0) != 0)) {
                (*(u32*)((char*)(arg0)+0x11C)) = 0;
                return;
            }
        }
        break;
    case 2:
        (*(u32*)((char*)(arg0)+0x240)) = (s32) (*(u32*)((char*)(arg0)+0x244));
        (*(u32*)((char*)(arg0)+0x248)) = (s32) (*(u32*)((char*)(arg0)+0x240));
        if (fn_8022F514((*(u32*)((char*)(arg0)+0x240))) != 0) {
            (*(u32*)((char*)(arg0)+0x248)) = fn_8022F3DC((*(u32*)((char*)(arg0)+0x240)));
        }
        temp_f31_2 = lbl_805413B0;
        var_r30 = arg0;
        temp_f30_2 = lbl_805413B4;
        var_r29 = 0;
        var_r31 = 0;
        do {
            temp_f2_3 = fn_8023E724(*(u32*)((char*)((var_r29))+0x8));
            temp_f1_2 = temp_f31_2 + sp14;
            sp10 = temp_f2_3;
            sp1C = temp_f2_3;
            sp8 = temp_f1_2;
            spC = sp18 - temp_f30_2;
            sp10 = temp_f2_3;
            if (fn_8022F514(var_r29, temp_f1_2, temp_f2_3, M2C_ERROR(/* psq_l unimplemented */)) == 1) {
                temp_r0_2 = (*(u32*)((char*)(arg0)+0x244));
                if (var_r29 == temp_r0_2) {
                    temp_r4 = (*(u32*)((char*)(arg0)+0x234));
                    temp_r27 = fn_8023DE58(var_r29, temp_r4);
                    fn_801F856C();
                    (*(u32*)((char*)(var_r30)+0x24C)) = fn_801F9484(0x494D5550, temp_r27, &sp8, (temp_r0_2 << 0x1A) + 0x80000000 + (var_r31 + temp_r4), -1, -1);
                }
            } else {
                temp_r0_3 = (*(u32*)((char*)(arg0)+0x244));
                if (var_r29 == temp_r0_3) {
                    temp_r4_2 = (*(u32*)((char*)(arg0)+0x234));
                    temp_r26 = fn_8023DE58(var_r29, temp_r4_2);
                    fn_801F856C();
                    (*(u32*)((char*)(var_r30)+0x24C)) = fn_801F9484(0x494D5550, temp_r26, &sp8, (temp_r0_3 << 0x1A) + 0x80000000 + (var_r31 + temp_r4_2), -1, -1);
                }
            }
            var_r29 += 1;
            var_r31 += 0x01000000;
            var_r30 += 4;
        } while (var_r29 < 4);
        if ((s32) (*(u32*)((char*)(arg0)+0x238)) != 1) {
            (*(u32*)((char*)(arg0)+0x11C)) = 0;
            return;
        }
        (*(u32*)((char*)(arg0)+0x230)) = 4;
        return;
    case 3:
        (*(u32*)((char*)(arg0)+0x240)) = (s32) (*(u32*)((char*)(arg0)+0x244));
        (*(u32*)((char*)(arg0)+0x248)) = (s32) (*(u32*)((char*)(arg0)+0x240));
        if (fn_8022F514((*(u32*)((char*)(arg0)+0x240))) != 0) {
            (*(u32*)((char*)(arg0)+0x248)) = fn_8022F3DC((*(u32*)((char*)(arg0)+0x240)));
        }
        if (((u32(*)())(*(void**)((char*)(unk0)+0x54)))(arg0) != 0) {
            (*(u32*)((char*)(arg0)+0x11C)) = 0;
        }
        break;
    }
}

/* --- auto_fn_802EBDCC_text.s --- */
s32 fn_80226BC4(f32 *, s32, f32);                   /* extern */
u8 fn_802D49A8(s32, u16);                           /* extern */









extern f32 lbl_805413E8;

void fn_802EBDCC(void *arg0) {
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    f32 temp_f1_2;
    f32 temp_f2;
    s32 temp_r0;
    s32 temp_r0_2;
    s32 temp_r30;

    (*(u32*)((char*)(arg0)+0x234)) = (s32) (u8) (*(u32*)((char*)(arg0)+0x90));
    (*(u32*)((char*)(arg0)+0x238)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 8U) & 0xF);
    (*(u32*)((char*)(arg0)+0x244)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0xCU) & 0xF);
    if ((s32) (*(u32*)((char*)(arg0)+0x244)) >= 4) {
        (*(u32*)((char*)(arg0)+0x244)) = -1;
    }
    temp_r0 = (*(u32*)((char*)(arg0)+0x234));
    if (((temp_r0 >= 0x1A) && (temp_r0 < 0x20)) || ((temp_r0 >= 0x26) && (temp_r0 < 0x2A)) || ((temp_r0 >= 0x3B) && (temp_r0 < 0x40)) || (temp_r0 >= 0x4B) || ((temp_r0 == 0x2E) && ((s32) (*(u32*)((char*)(arg0)+0x4)) >= 8))) {
        (*(u32*)((char*)(arg0)+0x234)) = 0;
    }
    (*(u32*)((char*)(arg0)+0x264)) = (f32) (*(u32*)((char*)(arg0)+0x14));
    temp_f2 = (*(u32*)((char*)(arg0)+0xC));
    (*(u32*)((char*)(arg0)+0xC)) = (f32) (temp_f2 + lbl_805413B8);
    temp_f1 = (*(u32*)((char*)(arg0)+0x10));
    (*(u32*)((char*)(arg0)+0x10)) = (f32) (temp_f1 + lbl_805413B4);
    temp_r30 = (*(u32*)((char*)(arg0)+0x4));
    if ((u8) (*(u32*)((char*)((fn_802D6A9C(temp_f1, temp_f2) + 0x10000 + temp_r30))+0x31DF)) != 0) {
        (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_805413C0;
        (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_805413E8;
        (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_805413C8;
        (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_805413CC;
    } else {
        (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_805413D0;
        (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_805413BC;
        (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_805413D4;
        (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_805413CC;
    }
    temp_f1_2 = (*(u32*)((char*)(arg0)+0x260));
    sp8 = (*(u32*)((char*)(arg0)+0x25C));
    spC = temp_f1_2;
    (*(u32*)((char*)(arg0)+0x23C)) = fn_80226BC4(&sp8, (*(u32*)((char*)(arg0)+0x4)), temp_f1_2);
    fn_802D6A9C();
    if (fn_802D49A8((*(u32*)((char*)(arg0)+0x4)), (u16) (*(u32*)((char*)(arg0)+0x23C))) == 1) {
        (*(u32*)((char*)(arg0)+0x11C)) = 0;
    }
    temp_r0_2 = (*(u32*)((char*)(arg0)+0x238));
    if (temp_r0_2 == 0) {
        (*(u32*)((char*)(arg0)+0x230)) = 0;
    } else if (temp_r0_2 == 2) {
        (*(u32*)((char*)(arg0)+0x230)) = 3;
    } else {
        (*(u32*)((char*)(arg0)+0x230)) = 2;
    }
    (*(u32*)((char*)(arg0)+0x248)) = -1;
    (*(u32*)((char*)(arg0)+0x24C)) = -1;
    (*(u32*)((char*)(arg0)+0x250)) = -1;
    (*(u32*)((char*)(arg0)+0x254)) = -1;
    (*(u32*)((char*)(arg0)+0x258)) = -1;
}

/* --- auto_fn_802EBFB0_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D58B8;










void fn_802EBFB0(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D58B8);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D58B8 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D58B8 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D58B8 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D58B8 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D58B8 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D58B8 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D58B8 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D58B8 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802EC1D4_text.s --- */


extern char lbl_804AA1D0;

char **fn_802EC1D4(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804AA1D0;
        dtor_801F593C(0, &lbl_804AA1D0);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_03_802EC234_text.s --- */
void fn_802EC234(void) {

}

/* --- auto_fn_802EC238_text.s --- */

void fn_801F35AC(void *arg0);                              /* extern */




extern char lbl_8046F450;
extern void *lbl_8053AAF8;
extern void *lbl_8053AF80;
extern f32 lbl_805413F0;

void fn_802EC238(void *arg0) {
    s32 temp_cr0_lt;
    s32 temp_r0;
    s32 temp_r0_2;
    s32 temp_r30;
    s32 temp_r30_2;
    s32 temp_r3;
    s32 var_r29;
    s32 var_r30;

    temp_r0 = (*(u32*)((char*)(arg0)+0x230));
    switch (temp_r0) {                              /* switch 1; irregular */
    case 0:                                         /* switch 1 */
        if (((u32(*)())(*(void**)((char*)(unk0)+0x34)))() != 0) {
            (*(u32*)((char*)(arg0)+0x230)) = 1;
            (*(u32*)((char*)(arg0)+0x24C)) = 1;
            return;
        }
        return;
    case 1:                                         /* switch 1 */
        (*(u32*)((char*)(arg0)+0x24C)) = (s32) ((*(u32*)((char*)(arg0)+0x24C)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x24C)) == 0) {
            var_r30 = 0;
            if ((s32) (*(u32*)((char*)(arg0)+0x240)) == 1) {
                var_r29 = -1;
loop_12:
                fn_801F856C();
                temp_r3 = fn_801F78F4((*(u32*)((char*)(arg0)+0x250)), var_r29);
                temp_cr0_lt = temp_r3 < 0;
                var_r29 = temp_r3;
                if (temp_cr0_lt == 0) {
                    var_r30 += 1;
                    if (var_r30 >= 0x1E) {
                        (*(u32*)((char*)(arg0)+0x248)) = (s32) (*(u32*)((char*)(arg0)+0x23C));
                        (*(u32*)((char*)(arg0)+0x230)) = 4;
                        return;
                    }
                    goto loop_12;
                }
                goto block_15;
            }
block_15:
            temp_r30 = (*(u32*)((char*)(arg0)+0x4));
            if (temp_r30 >= 8) {
                fn_801F856C();
                fn_801F9484(0x4B4D5249, temp_r30, arg0 + 0xC, 3, -1, -1);
            } else {
                fn_8013CC50(temp_r30, arg0 + 0xC, 0x35C, 1, 1, 0, 0, 1, lbl_805413F0);
            }
            goto block_18;
        }
block_18:
        (*(u32*)((char*)(arg0)+0x230)) = 2;
        (*(u32*)((char*)(arg0)+0x24C)) = 2;
        return;
    case 2:                                         /* switch 1 */
        (*(u32*)((char*)(arg0)+0x24C)) = (s32) ((*(u32*)((char*)(arg0)+0x24C)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x24C)) == 0) {
            temp_r30_2 = *(&lbl_8046F450 + ((*(u32*)((char*)(arg0)+0x234)) * 4));
            fn_801F856C(&lbl_8046F450);
            fn_801F9484((*(u32*)((char*)(arg0)+0x250)), (*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, temp_r30_2, -1, -1);
            if (((u32) ((*(u32*)((char*)(lbl_8053AF80)+0x58)) + 0xFF000000) != 0x21U) && ((u8) (*(u32*)((char*)(lbl_8053AAF8)+0x7F)) == 1) && ((s32) (*(u32*)((char*)(arg0)+0x244)) == 0)) {
                fn_80458FF0(0x01000021, 1, 0);
            }
            (*(u32*)((char*)(arg0)+0x24C)) = (s32) (*(u32*)((char*)(arg0)+0x238));
            (*(u32*)((char*)(arg0)+0x248)) = (s32) ((*(u32*)((char*)(arg0)+0x248)) - 1);
            if ((s32) (*(u32*)((char*)(arg0)+0x248)) == 0) {
                temp_r0_2 = (*(u32*)((char*)(arg0)+0x240));
                switch (temp_r0_2) {                /* switch 2; irregular */
                case 0:                             /* switch 2 */
                    fn_801F35AC(arg0);
                    return;
                case 1:                             /* switch 2 */
                    (*(u32*)((char*)(arg0)+0x248)) = (s32) (*(u32*)((char*)(arg0)+0x23C));
                    (*(u32*)((char*)(arg0)+0x230)) = 4;
                    return;
                }
            } else {
                (*(u32*)((char*)(arg0)+0x230)) = 1;
                return;
            }
        }
        break;
    case 4:                                         /* switch 1 */
        if (((u32(*)())(*(void**)((char*)(unk0)+0x34)))() == 0) {
            (*(u32*)((char*)(arg0)+0x230)) = 0;
        }
        break;
    }
}

/* --- auto_03_802EC4A8_text.s --- */
extern char lbl_8046F398;

void fn_802EC4A8(void *arg0) {
    (*(u32*)((char*)(arg0)+0x234)) = (s32) ((*(u32*)((char*)(arg0)+0x90)) & 0x7F);
    (*(u32*)((char*)(arg0)+0x250)) = (s32) *(&lbl_8046F398 + ((*(u32*)((char*)(arg0)+0x234)) * 4));
    (*(u32*)((char*)(arg0)+0x238)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 7U) & 0x1FF);
    (*(u32*)((char*)(arg0)+0x23C)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x10U) & 0xF);
    (*(u32*)((char*)(arg0)+0x240)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x14U) & 0xF);
    (*(u32*)((char*)(arg0)+0x244)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x18U) & 1);
    (*(u32*)((char*)(arg0)+0x248)) = (s32) (*(u32*)((char*)(arg0)+0x23C));
    (*(u32*)((char*)(arg0)+0x24C)) = 1;
    (*(u32*)((char*)(arg0)+0x230)) = 0;
}

/* --- auto_fn_802EC518_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D59B8;










void fn_802EC518(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D59B8);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D59B8 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D59B8 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D59B8 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D59B8 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D59B8 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D59B8 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D59B8 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D59B8 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802EC73C_text.s --- */


extern char lbl_804AA228;

char **fn_802EC73C(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804AA228;
        dtor_801F593C(0, &lbl_804AA228);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_03_802EC79C_text.s --- */
void fn_802EC79C(void) {

}

/* --- auto_fn_802EC7A0_text.s --- */
extern void *lbl_8053AB10;

void fn_802EC7A0(void *arg0) {
    s32 temp_r0;
    u8 var_r4;
    char *temp_r3;
    char *temp_r3_2;
    char *temp_r3_3;

    temp_r0 = (*(u32*)((char*)(arg0)+0x230));
    switch (temp_r0) {                              /* irregular */
    case 0:
        if (((u32(*)())(*(void**)((char*)(unk0)+0x34)))() != 0) {
            temp_r3 = (*(u32*)((char*)(lbl_8053AB10)+0x24));
            if ((u8) (*(u32*)((char*)(temp_r3)+0x7F4)) == 0) {
                (*(u32*)((char*)(temp_r3)+0x7F5)) = 1;
            }
            var_r4 = 0;
            temp_r3_2 = (*(u32*)((char*)(lbl_8053AB10)+0x24));
            if ((u8) (*(u32*)((char*)(temp_r3_2)+0x7F4)) == 0) {
                var_r4 = 1;
                (*(u32*)((char*)(temp_r3_2)+0x7F5)) = 1;
            }
            if (var_r4 == 1) {
                (*(u32*)((char*)(arg0)+0x230)) = 1;
                (*(u32*)((char*)(arg0)+0x238)) = (s32) (*(u32*)((char*)(arg0)+0x234));
                return;
            }
        } else {
            return;
        }
        break;
    case 1:
        temp_r3_3 = (*(u32*)((char*)(lbl_8053AB10)+0x24));
        if ((u8) (*(u32*)((char*)(temp_r3_3)+0x7F4)) == 0) {
            (*(u32*)((char*)(temp_r3_3)+0x7F5)) = 1;
        }
        (*(u32*)((char*)(arg0)+0x238)) = (s32) ((*(u32*)((char*)(arg0)+0x238)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x238)) == 0) {
            (*(u32*)((char*)(arg0)+0x11C)) = 0;
        }
        break;
    }
}

/* --- auto_03_802EC894_text.s --- */
void fn_802EC894(void *arg0) {
    (*(u32*)((char*)(arg0)+0x234)) = (s32) ((*(u32*)((char*)(arg0)+0x90)) & 0xFFF);
    (*(u32*)((char*)(arg0)+0x238)) = 0;
    (*(u32*)((char*)(arg0)+0x230)) = 0;
}

/* --- auto_fn_802EC8B0_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D5AB8;










void fn_802EC8B0(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D5AB8);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D5AB8 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D5AB8 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D5AB8 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D5AB8 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D5AB8 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D5AB8 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D5AB8 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D5AB8 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_03_802ECAD4_text.s --- */
void fn_802ECAD4(void) {

}

/* --- auto_fn_802ECAD8_text.s --- */
u32 fn_80136798(void *, u32, u32);                        /* extern */

void *fn_8013CC50(s32, void *, u32, u32, u32, u32, u32, u32, f32); /* extern */
u32 fn_80230534(u32);                                   /* extern */

void *fn_802D6A9C();                                /* extern */
u32 fn_802D9FF4(s32, s32);                            /* extern */
extern void *lbl_8053AAF8;
extern void *lbl_8053AB10;
extern f32 lbl_805413F8;
extern f32 lbl_805413FC;

void fn_802ECAD8(void *arg0) {
    s32 spC;
    s32 sp8;
    f32 temp_f1;
    s32 temp_r3_2;
    s32 temp_r3_4;
    u32 temp_r31;
    char *temp_r3;
    char *temp_r3_3;
    char *temp_r3_5;
    char *temp_r5;

    temp_r3 = (*(u32*)((char*)(lbl_8053AB10)+0x24));
    (*(u32*)((char*)(arg0)+0x244)) = (f32) -(*(u32*)((char*)(temp_r3)+0x10));
    temp_f1 = -(*(u32*)((char*)(temp_r3)+0x20));
    (*(u32*)((char*)(arg0)+0x248)) = temp_f1;
    (*(u32*)((char*)(arg0)+0x24C)) = (f32) lbl_805413F8;
    fn_8013CB44((*(u32*)((char*)(arg0)+0x234)), arg0 + 0x244, 1, 1, 1, temp_f1);
    temp_r3_2 = (*(u32*)((char*)(arg0)+0x240));
    if (temp_r3_2 != 0) {
        (*(u32*)((char*)(arg0)+0x240)) = (s32) (temp_r3_2 - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x240)) == 0) {
            fn_80230534(0);
            temp_r31 = (*(u32*)((char*)(arg0)+0x90));
            fn_802D6A9C();
            fn_802D9FF4((temp_r31 >> 8U) & 0xF, (temp_r31 >> 0xCU) & 0xF);
            fn_80136798(lbl_8053AAF8, 0xD, 0);
        }
    } else {
        if ((s32) (*(u32*)((char*)(lbl_8053AAF8)+0x4C)) != 0xB) {
            spC = 0x50079;
            temp_r3_3 = (*(u32*)((char*)(arg0)+0x230));
            ((u32(*)())(*(void**)((char*)(unk8)+0x14)))(temp_r3_3, &spC);
        }
        if (((s32) (*(u32*)((char*)(arg0)+0x250)) == 0) && ((u8) fn_802D6A9C(*(u32*)((char*)(())+0xC9)) != 0)) {
            (*(u32*)((char*)(arg0)+0x250)) = 1;
            temp_r5 = (*(u32*)((char*)(arg0)+0x234));
            (*(u32*)((char*)(temp_r5)+0xF4)) = (s32) ((*(u32*)((char*)(temp_r5)+0xF4)) | 1);
            (*(u32*)((char*)(temp_r5)+0x24)) = 1;
            (*(u32*)((char*)(arg0)+0x234)) = NULL;
            temp_r3_4 = (*(u32*)((char*)(arg0)+0x23C));
            if (temp_r3_4 & 1) {
                (*(u32*)((char*)(arg0)+0x234)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0x244, 0x3E9, 1, 1, 0, 0, 1, lbl_805413FC);
            } else if (temp_r3_4 & 2) {
                (*(u32*)((char*)(arg0)+0x234)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0x244, 0x3E8, 1, 1, 0, 0, 1, lbl_805413FC);
            } else if (temp_r3_4 & 4) {
                (*(u32*)((char*)(arg0)+0x234)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0x244, 0x3E7, 1, 1, 0, 0, 1, lbl_805413FC);
            } else {
                (*(u32*)((char*)(arg0)+0x234)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0x244, 0x3EA, 1, 1, 0, 0, 1, lbl_805413FC);
            }
            (*(u32*)((char*)(arg0)+0x240)) = 0x64;
            fn_8023077C();
            sp8 = 0x400B9;
            temp_r3_5 = (*(u32*)((char*)(arg0)+0x230));
            ((u32(*)())(*(void**)((char*)(unk8)+0x14)))(temp_r3_5, &sp8);
        }
    }
}

/* --- auto_fn_802ECD0C_text.s --- */



extern char lbl_804AA280;

void *fn_802ECD0C(void *arg0, s16 arg1) {
    s32 temp_cr0_eq;
    char *temp_r3;

    if (arg0 != NULL) {
        (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804AA280;
        if ((u32) (*(u32*)((char*)(arg0)+0x234)) != 0U) {
            fn_801EE434();
        }
        temp_r3 = (*(u32*)((char*)(arg0)+0x230));
        temp_cr0_eq = temp_r3 == NULL;
        if ((temp_cr0_eq == 0) && (temp_cr0_eq == 0)) {
            ((u32(*)())(*(void**)((char*)(unk8)+0x30)))(1);
        }
        dtor_801F593C(arg0, 0);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_802ECDA4_text.s --- */
s32 fn_80084370(u32);                                 /* extern */

u32 fn_804578F4(u32, u32, u32);                             /* extern */
extern void *lbl_8053AB10;



void fn_802ECDA4(void *arg0) {
    s32 temp_r3_2;
    s32 temp_r3_3;
    char *temp_r3;

    (*(u32*)((char*)(arg0)+0x23C)) = (s32) ((*(u32*)((char*)(arg0)+0x90)) & 0xF);
    (*(u32*)((char*)(arg0)+0x254)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 4U) & 0xF);
    temp_r3 = (*(u32*)((char*)(lbl_8053AB10)+0x24));
    (*(u32*)((char*)(arg0)+0x244)) = (f32) -(*(u32*)((char*)(temp_r3)+0x10));
    (*(u32*)((char*)(arg0)+0x248)) = (f32) -(*(u32*)((char*)(temp_r3)+0x20));
    (*(u32*)((char*)(arg0)+0x24C)) = (f32) lbl_805413F8;
    temp_r3_2 = (*(u32*)((char*)(arg0)+0x23C));
    if (temp_r3_2 & 1) {
        (*(u32*)((char*)(arg0)+0x234)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0x244, 0x3E6, 1, 1, 0, 0, 1, lbl_805413FC);
    } else if (temp_r3_2 & 2) {
        (*(u32*)((char*)(arg0)+0x234)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0x244, 0x3E5, 1, 1, 0, 0, 1, lbl_805413FC);
    } else if (temp_r3_2 & 4) {
        (*(u32*)((char*)(arg0)+0x234)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0x244, 0x3E4, 1, 1, 0, 0, 1, lbl_805413FC);
    } else {
        (*(u32*)((char*)(arg0)+0x234)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), arg0 + 0x244, 0x3EB, 1, 1, 0, 0, 1, lbl_805413FC);
    }
    (*(u32*)((char*)(arg0)+0x240)) = 0;
    (*(u32*)((char*)(arg0)+0x250)) = 0;
    temp_r3_3 = fn_80084370(0x5C);
    if (temp_r3_3 != 0) {
        fn_804578F4(0, 0, 8);
    }
    (*(u32*)((char*)(arg0)+0x230)) = temp_r3_3;
}

/* --- auto_fn_802ECF1C_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D5BB8;










void fn_802ECF1C(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D5BB8);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D5BB8 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D5BB8 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D5BB8 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D5BB8 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D5BB8 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D5BB8 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D5BB8 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D5BB8 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802ED140_text.s --- */
void fn_80134FBC(void *arg0, s8 arg1);                              /* extern */
void *fn_801F856C();                                /* extern */
void fn_802AC09C(void *arg0);                                    /* extern */
u32 fn_80458658(s32, u32);                              /* extern */



void fn_802ED140(void *arg0) {
    s32 temp_r31;
    s32 var_r29;
    s32 var_r30;
    char *temp_r3;

    temp_r31 = fn_801F856C(*(u32*)((char*)(())+0x1008));
    var_r29 = 0;
    var_r30 = 0;
loop_5:
    if (var_r29 < temp_r31) {
        temp_r3 = *(fn_801F856C() + (var_r30 + 8));
        if ((temp_r3 != NULL) && ((u32) ((*(u32*)((char*)(temp_r3)+0x1A0)) + 0xB6AC0000) == 0x4D53U)) {
            fn_802AC09C();
        }
        var_r30 += 4;
        var_r29 += 1;
        goto loop_5;
    }
    fn_80134FBC(lbl_8053AAF8, 0);
    fn_80458658(lbl_8053AF80, 0);
    (*(u32*)((char*)(arg0)+0x11C)) = 0;
}

