/* Auto-generated by tools/m2c_batch.py */
/* Address range: 0x801FFD1C – 0x80200A0C */
#include "nonmatch.h"

/* --- auto_fn_801FFD1C_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AE7D8;

char **fn_801FFD1C(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AE7D8;
    return arg0;
}

/* --- auto_fn_801FFD58_text.s --- */
u32 fn_80066FFC(void *, char *, u32, u32, u32);                /* extern */
u32 fn_801F5AE0();                                    /* extern */
void fn_8003B2CC();
extern u32 lbl_804AE4B0;

char **fn_801FFD58(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AE4B0;
    fn_80066FFC(arg0 + 0x264, &fn_8003B2CC, 0, 0xC, 4);
    fn_80066FFC(arg0 + 0x294, &fn_8003B2CC, 0, 0xC, 4);
    fn_80066FFC(arg0 + 0x2C4, &fn_8003B2CC, 0, 0xC, 4);
    fn_80066FFC(arg0 + 0x2F4, &fn_8003B2CC, 0, 0xC, 4);
    return arg0;
}

/* --- auto_fn_801FFE04_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AE338;

char **fn_801FFE04(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AE338;
    return arg0;
}

/* --- auto_fn_801FFE40_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AE780;

char **fn_801FFE40(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AE780;
    return arg0;
}

/* --- auto_fn_801FFE7C_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_8049EA88;

void *fn_801FFE7C(void *arg0) {
    fn_801F5AE0();
    arg0->unk0 = &lbl_8049EA88;
    arg0->unk230 = 0;
    arg0->unk234 = -1;
    arg0->unk238 = -1;
    arg0->unk23C = -1;
    arg0->unk240 = -1;
    arg0->unk244 = 0;
    arg0->unk248 = 0;
    arg0->unk24C = 0;
    return arg0;
}

/* --- auto_fn_801FFEE0_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AA4F0;

void *fn_801FFEE0(void *arg0) {
    fn_801F5AE0();
    arg0->unk0 = &lbl_804AA4F0;
    arg0->unk248 = -1;
    return arg0;
}

/* --- auto_fn_801FFF24_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804ACD18;

char **fn_801FFF24(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804ACD18;
    return arg0;
}

/* --- auto_fn_801FFF60_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_8049EA00;

void *fn_801FFF60(void *arg0) {
    fn_801F5AE0();
    arg0->unk0 = &lbl_8049EA00;
    arg0->unk230 = 0;
    return arg0;
}

/* --- auto_fn_801FFFA4_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_8049E9A8;

void *fn_801FFFA4(void *arg0) {
    fn_801F5AE0();
    arg0->unk0 = &lbl_8049E9A8;
    arg0->unk230 = 0;
    return arg0;
}

/* --- auto_fn_801FFFE8_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AA498;

char **fn_801FFFE8(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AA498;
    return arg0;
}

/* --- auto_fn_80200024_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804ACBF0;

char **fn_80200024(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804ACBF0;
    return arg0;
}

/* --- auto_fn_80200060_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804ACC68;

char **fn_80200060(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804ACC68;
    return arg0;
}

/* --- auto_fn_8020009C_text.s --- */
u32 fn_801EB950(s32, char *);                            /* extern */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804ACCC0;

char **fn_8020009C(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804ACCC0;
    fn_801EB950(arg0 + 0x230, &lbl_804ACCC0);
    return arg0;
}

/* --- auto_fn_802000E0_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AE2E0;

char **fn_802000E0(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AE2E0;
    return arg0;
}

/* --- auto_fn_8020011C_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AE288;

char **fn_8020011C(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AE288;
    return arg0;
}

/* --- auto_fn_80200158_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804A7C40;

char **fn_80200158(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804A7C40;
    return arg0;
}

/* --- auto_fn_80200194_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AA440;

char **fn_80200194(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AA440;
    return arg0;
}

/* --- auto_fn_802001D0_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804ACB98;

char **fn_802001D0(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804ACB98;
    return arg0;
}

/* --- auto_fn_8020020C_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AE728;

char **fn_8020020C(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AE728;
    return arg0;
}

/* --- auto_fn_80200248_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804A3948;

char **fn_80200248(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804A3948;
    return arg0;
}

/* --- auto_fn_80200284_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_8049E8F8;

void *fn_80200284(void *arg0) {
    fn_801F5AE0();
    arg0->unk0 = &lbl_8049E8F8;
    arg0->unk230 = 0;
    arg0->unk234 = 0;
    arg0->unk238 = 0;
    arg0->unk23C = 0;
    return arg0;
}

/* --- auto_fn_802002D4_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_8049CA40;

char **fn_802002D4(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_8049CA40;
    return arg0;
}

/* --- auto_fn_80200310_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_8049C9E8;

char **fn_80200310(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_8049C9E8;
    return arg0;
}

/* --- auto_fn_8020034C_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804ACB40;

char **fn_8020034C(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804ACB40;
    return arg0;
}

/* --- auto_fn_80200388_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AA3E8;

char **fn_80200388(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AA3E8;
    return arg0;
}

/* --- auto_fn_802003C4_text.s --- */
u32 fn_80066FFC(void *, char *, u32, u32, u32);                /* extern */
u32 fn_801F5AE0();                                    /* extern */
void fn_8003B2CC();
extern u32 lbl_804A38D4;

char **fn_802003C4(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804A38D4;
    fn_80066FFC(arg0 + 0x264, &fn_8003B2CC, 0, 0xC, 4);
    return arg0;
}

/* --- auto_fn_8020041C_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AABA8;

char **fn_8020041C(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AABA8;
    return arg0;
}

/* --- auto_fn_80200458_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_8049E848;

void *fn_80200458(void *arg0) {
    fn_801F5AE0();
    arg0->unk0 = &lbl_8049E848;
    arg0->unk230 = 0;
    arg0->unk234 = 0;
    arg0->unk238 = 0;
    arg0->unk23C = 0;
    arg0->unk240 = 0;
    arg0->unk244 = 0;
    return arg0;
}

/* --- auto_fn_802004B0_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AE230;

char **fn_802004B0(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AE230;
    return arg0;
}

/* --- auto_fn_802004EC_text.s --- */
u32 fn_80066FFC(void *, char *, u32, u32, u32);                /* extern */
u32 fn_801F5AE0();                                    /* extern */
void fn_80200544(void);
extern u32 lbl_804AA350;

char **fn_802004EC(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AA350;
    fn_80066FFC(arg0 + 0x27C, &fn_80200544, 0, 0x14, 4);
    return arg0;
}

/* --- auto_03_80200544_text.s --- */
void fn_80200544(void) {

}

/* --- auto_fn_80200548_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AA2D8;

char **fn_80200548(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AA2D8;
    return arg0;
}

/* --- auto_fn_80200584_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AE6D0;

char **fn_80200584(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AE6D0;
    return arg0;
}

/* --- auto_fn_802005C0_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AE678;

char **fn_802005C0(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AE678;
    return arg0;
}

/* --- auto_fn_802005FC_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AA280;

char **fn_802005FC(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AA280;
    return arg0;
}

/* --- auto_fn_80200638_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AE620;

char **fn_80200638(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AE620;
    return arg0;
}

/* --- auto_fn_80200674_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AAB40;

char **fn_80200674(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AAB40;
    return arg0;
}

/* --- auto_fn_802006B0_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804ADFE8;

char **fn_802006B0(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804ADFE8;
    return arg0;
}

/* --- auto_fn_802006EC_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AA228;

char **fn_802006EC(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AA228;
    return arg0;
}

/* --- auto_fn_80200728_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804A375C;

char **fn_80200728(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804A375C;
    return arg0;
}

/* --- auto_fn_80200764_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804A3698;

char **fn_80200764(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804A3698;
    return arg0;
}

/* --- auto_fn_802007A0_text.s --- */
u32 fn_80066FFC(void *, char *, u32, u32, u32);                /* extern */
u32 fn_801F5AE0();                                    /* extern */
void fn_8003B2CC();
extern u32 lbl_804A35AC;

char **fn_802007A0(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804A35AC;
    fn_80066FFC(arg0 + 0x288, &fn_8003B2CC, 0, 0xC, 4);
    return arg0;
}

/* --- auto_fn_802007F8_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804ACA00;

char **fn_802007F8(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804ACA00;
    return arg0;
}

/* --- auto_fn_80200834_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AA1D0;

char **fn_80200834(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AA1D0;
    return arg0;
}

/* --- auto_fn_80200870_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804A3548;

char **fn_80200870(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804A3548;
    return arg0;
}

/* --- auto_fn_802008AC_text.s --- */
u32 fn_80066FFC(void *, char *, u32, u32, u32);                /* extern */
u32 fn_801F5AE0();                                    /* extern */
void fn_8003B2CC();
extern u32 lbl_804AC9A8;

char **fn_802008AC(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AC9A8;
    fn_80066FFC(arg0 + 0x254, &fn_8003B2CC, 0, 0xC, 4);
    return arg0;
}

/* --- auto_fn_80200904_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AAAE8;

char **fn_80200904(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AAAE8;
    return arg0;
}

/* --- auto_fn_80200940_text.s --- */
u32 fn_801F5AE0();                                    /* extern */
extern u32 lbl_804AAA70;

char **fn_80200940(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AAA70;
    return arg0;
}

/* --- auto_fn_8020097C_text.s --- */
u32 fn_80066FFC(void *, char *, u32, u32, u32);                /* extern */
u32 fn_801F5AE0();                                    /* extern */
void fn_8003B2CC();
extern u32 lbl_804ADF28;

char **fn_8020097C(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804ADF28;
    fn_80066FFC(arg0 + 0x27C, &fn_8003B2CC, 0, 0xC, 3);
    fn_80066FFC(arg0 + 0x2A0, &fn_8003B2CC, 0, 0xC, 3);
    fn_80066FFC(arg0 + 0x2C4, &fn_8003B2CC, 0, 0xC, 3);
    return arg0;
}

/* --- auto_fn_80200A0C_text.s --- */
u32 fn_80066FFC(void *, char *, u32, u32, u32);                /* extern */
u32 fn_801F5AE0();                                    /* extern */
void fn_80200A80();
void fn_80200A84();
extern u32 lbl_804AC950;

char **fn_80200A0C(char **arg0) {
    fn_801F5AE0();
    *arg0 = &lbl_804AC950;
    fn_80066FFC(arg0 + 0x260, &fn_80200A84, 0, 0x18, 8);
    fn_80066FFC(arg0 + 0x320, &fn_80200A80, 0, 0x14, 4);
    return arg0;
}

