/* Auto-generated by tools/m2c_batch.py */
/* Address range: 0x802A3164 – 0x802AAC60 */
#include "nonmatch.h"
#include "_ps_emu.h"

/* --- auto_fn_802A3164_text.s --- */
void fn_801F3668(void *arg0);                              /* extern */
void **fn_801F666C(s32);                            /* extern */
void *fn_801F856C();                                /* extern */
s32 fn_801F9484(u32, s32, void *, s32, u32, u32);         /* extern */
s32 fn_80226BC4(f32 *, s32, f32, f32);              /* extern */
s32 fn_802D4C10(s32, u16);                          /* extern */
u32 fn_802D6A9C();                                    /* extern */
u32 fn_802D782C(u32);                                   /* extern */
u32 fn_802D7D00(s32, s32, u32);                         /* extern */
u16 fn_802F9908(s32, s32, s32);                     /* extern */
u32 fn_802F9974(s32, s32, s32, u32);                    /* extern */
extern void *lbl_8053AB10;
extern void *lbl_8053AC98;

s32 fn_802A3164(void *arg0, void *arg1, s32 arg3) {
    f32 sp60;
    f32 sp54;
    f32 sp50;
    f32 sp4C;
    f32 sp48;
    f32 sp44;
    f32 sp40;
    f32 sp3C;
    f32 sp38;
    f32 sp34;
    f32 sp30;
    f32 sp2C;
    f32 sp28;
    f32 sp24;
    f32 sp20;
    f32 sp1C;
    f32 sp18;
    f32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    f32 temp_f1_2;
    f32 temp_f1_3;
    f32 temp_f1_4;
    f32 temp_f1_5;
    f32 temp_f1_6;
    f32 temp_f1_7;
    f32 temp_f1_8;
    f32 temp_f1_9;
    f32 temp_f2;
    s32 temp_r26;
    s32 temp_r26_10;
    s32 temp_r26_11;
    s32 temp_r26_12;
    s32 temp_r26_13;
    s32 temp_r26_2;
    s32 temp_r26_3;
    s32 temp_r26_4;
    s32 temp_r26_5;
    s32 temp_r26_6;
    s32 temp_r26_7;
    s32 temp_r26_8;
    s32 temp_r26_9;
    s32 temp_r3;
    s32 temp_r3_11;
    s32 temp_r3_2;
    s32 temp_r3_3;
    s32 temp_r3_5;
    s32 temp_r3_6;
    s32 temp_r3_7;
    s32 temp_r3_9;
    s32 var_r24;
    s32 var_r25;
    s32 var_r30;
    u16 temp_r0;
    void **temp_r3_10;
    void **temp_r3_12;
    void **temp_r3_4;
    void **temp_r3_8;
    char *temp_r27;
    char *temp_r27_2;
    char *temp_r27_3;
    char *temp_r27_4;
    char *temp_r27_5;
    char *temp_r27_6;
    char *temp_r27_7;
    char *temp_r27_8;
    char *temp_r27_9;

    temp_f1 = (*(u32*)((char*)(arg1)+0x4));
    sp4C = temp_f1;
    sp48 = (*(u32*)((char*)(arg1)+0x0));
    (*(u32*)((char*)(arg0)+0x20)) = fn_80226BC4(&sp48, arg3, temp_f1);
    (*(u32*)((char*)(arg0)+0x24)) = fn_802F9908((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg3, (*(u32*)((char*)(arg0)+0x20)));
    var_r30 = 1;
    temp_r0 = (*(u32*)((char*)(arg0)+0x24));
    if ((temp_r0 >= 0x40U) && (temp_r0 <= 0x44U)) {
        if (temp_r0 == 0x41) {
            temp_f1_2 = (*(u32*)((char*)(arg1)+0x4));
            sp44 = temp_f1_2;
            temp_r27 = lbl_8053AC98;
            sp40 = (*(u32*)((char*)(arg1)+0x0));
            (*(u32*)((char*)(temp_r27)+0x20)) = fn_80226BC4(&sp40, arg3 & 0xFE, temp_f1_2);
            temp_r26 = (*(u32*)((char*)(temp_r27)+0x20));
            fn_802D6A9C();
            fn_802D782C(1);
            fn_802F9974((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg3, temp_r26, 0x12);
            fn_802D6A9C();
            temp_r3 = fn_802D4C10(arg3, (u16) (*(u32*)((char*)(temp_r27)+0x20)));
            if (temp_r3 != -1) {
                fn_802D6A9C();
                fn_802D7D00(arg3, temp_r3, 0);
            }
            temp_r26_2 = fn_801F856C(*(u32*)((char*)(())+0x1008));
            var_r24 = 0;
            var_r25 = 0;
loop_12:
            if (var_r24 >= temp_r26_2) {

            } else {
                temp_r27_2 = *(fn_801F856C() + (var_r25 + 8));
                if ((temp_r27_2 != NULL) && ((u32) ((*(u32*)((char*)(temp_r27_2)+0x1A0)) + 0xABBE0000) == 0x4F32U) && (arg3 == (s32) (*(u32*)((char*)(temp_r27_2)+0x4))) && (temp_f2 = (*(u32*)((char*)(temp_r27_2)+0x14)), sp60 = temp_f2, sp50 = sp58, sp54 = sp5C, (((s32) (*(u32*)((char*)(arg0)+0x20)) == fn_80226BC4(&sp50, arg3, sp58, temp_f2)) != 0))) {
                    fn_801F3668(temp_r27_2);
                } else {
                    var_r25 += 4;
                    var_r24 += 1;
                    goto loop_12;
                }
            }
        } else if (temp_r0 == 0x43) {
            temp_f1_3 = (*(u32*)((char*)(arg1)+0x4));
            sp3C = temp_f1_3;
            temp_r27_3 = lbl_8053AC98;
            sp38 = (*(u32*)((char*)(arg1)+0x0));
            (*(u32*)((char*)(temp_r27_3)+0x20)) = fn_80226BC4(&sp38, arg3 & 0xFE, temp_f1_3);
            temp_r26_3 = (*(u32*)((char*)(temp_r27_3)+0x20));
            fn_802D6A9C();
            fn_802D782C(1);
            fn_802F9974((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg3, temp_r26_3, 0x50);
            fn_802D6A9C();
            temp_r3_2 = fn_802D4C10(arg3, (u16) (*(u32*)((char*)(temp_r27_3)+0x20)));
            if (temp_r3_2 != -1) {
                fn_802D6A9C();
                fn_802D7D00(arg3, temp_r3_2, 1);
            }
        } else {
            temp_f1_4 = (*(u32*)((char*)(arg1)+0x4));
            sp34 = temp_f1_4;
            temp_r27_4 = lbl_8053AC98;
            sp30 = (*(u32*)((char*)(arg1)+0x0));
            (*(u32*)((char*)(temp_r27_4)+0x20)) = fn_80226BC4(&sp30, arg3 & 0xFE, temp_f1_4);
            temp_r26_4 = (*(u32*)((char*)(temp_r27_4)+0x20));
            fn_802D6A9C();
            fn_802D782C(1);
            fn_802F9974((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg3, temp_r26_4, 0x11);
            fn_802D6A9C();
            temp_r3_3 = fn_802D4C10(arg3, (u16) (*(u32*)((char*)(temp_r27_4)+0x20)));
            if (temp_r3_3 != -1) {
                fn_802D6A9C();
                fn_802D7D00(arg3, temp_r3_3, 1);
            }
        }
        fn_801F856C();
        temp_r26_5 = fn_801F9484(0x5455424F, arg3, arg1, (*(u32*)((char*)(arg0)+0x24)) - 0x40, -1, -1);
        fn_801F856C();
        temp_r3_4 = fn_801F666C(temp_r26_5);
        if (temp_r3_4 != NULL) {
            ((u32(*)())(*(void**)((char*)((*temp_r3_4))+0x24)))();
        }
    } else if ((temp_r0 >= 0x45U) && (temp_r0 <= 0x49U)) {
        if (temp_r0 == 0x46) {
            temp_f1_5 = (*(u32*)((char*)(arg1)+0x4));
            sp2C = temp_f1_5;
            temp_r27_5 = lbl_8053AC98;
            sp28 = (*(u32*)((char*)(arg1)+0x0));
            (*(u32*)((char*)(temp_r27_5)+0x20)) = fn_80226BC4(&sp28, arg3 & 0xFE, temp_f1_5);
            temp_r26_6 = (*(u32*)((char*)(temp_r27_5)+0x20));
            fn_802D6A9C();
            fn_802D782C(1);
            fn_802F9974((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg3, temp_r26_6, 0x14);
            fn_802D6A9C();
            temp_r3_5 = fn_802D4C10(arg3, (u16) (*(u32*)((char*)(temp_r27_5)+0x20)));
            if (temp_r3_5 != -1) {
                fn_802D6A9C();
                fn_802D7D00(arg3, temp_r3_5, 1);
            }
        } else if (temp_r0 == 0x48) {
            temp_f1_6 = (*(u32*)((char*)(arg1)+0x4));
            sp24 = temp_f1_6;
            temp_r27_6 = lbl_8053AC98;
            sp20 = (*(u32*)((char*)(arg1)+0x0));
            (*(u32*)((char*)(temp_r27_6)+0x20)) = fn_80226BC4(&sp20, arg3 & 0xFE, temp_f1_6);
            temp_r26_7 = (*(u32*)((char*)(temp_r27_6)+0x20));
            fn_802D6A9C();
            fn_802D782C(1);
            fn_802F9974((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg3, temp_r26_7, 0x52);
            fn_802D6A9C();
            temp_r3_6 = fn_802D4C10(arg3, (u16) (*(u32*)((char*)(temp_r27_6)+0x20)));
            if (temp_r3_6 != -1) {
                fn_802D6A9C();
                fn_802D7D00(arg3, temp_r3_6, 1);
            }
        } else {
            temp_f1_7 = (*(u32*)((char*)(arg1)+0x4));
            sp1C = temp_f1_7;
            temp_r27_7 = lbl_8053AC98;
            sp18 = (*(u32*)((char*)(arg1)+0x0));
            (*(u32*)((char*)(temp_r27_7)+0x20)) = fn_80226BC4(&sp18, arg3 & 0xFE, temp_f1_7);
            temp_r26_8 = (*(u32*)((char*)(temp_r27_7)+0x20));
            fn_802D6A9C();
            fn_802D782C(1);
            fn_802F9974((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg3, temp_r26_8, 0x15);
            fn_802D6A9C();
            temp_r3_7 = fn_802D4C10(arg3, (u16) (*(u32*)((char*)(temp_r27_7)+0x20)));
            if (temp_r3_7 != -1) {
                fn_802D6A9C();
                fn_802D7D00(arg3, temp_r3_7, 1);
            }
        }
        fn_801F856C();
        temp_r26_9 = fn_801F9484(0x5455424F, arg3, arg1, (*(u32*)((char*)(arg0)+0x24)) - 0x45, -1, -1);
        fn_801F856C();
        temp_r3_8 = fn_801F666C(temp_r26_9);
        if (temp_r3_8 != NULL) {
            ((u32(*)())(*(void**)((char*)((*temp_r3_8))+0x24)))();
        }
    } else if (temp_r0 == 0x4E) {
        temp_f1_8 = (*(u32*)((char*)(arg1)+0x4));
        sp14 = temp_f1_8;
        temp_r27_8 = lbl_8053AC98;
        sp10 = (*(u32*)((char*)(arg1)+0x0));
        (*(u32*)((char*)(temp_r27_8)+0x20)) = fn_80226BC4(&sp10, arg3 & 0xFE, temp_f1_8);
        temp_r26_10 = (*(u32*)((char*)(temp_r27_8)+0x20));
        fn_802D6A9C();
        fn_802D782C(1);
        fn_802F9974((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg3, temp_r26_10, 0x11);
        fn_802D6A9C();
        temp_r3_9 = fn_802D4C10(arg3, (u16) (*(u32*)((char*)(temp_r27_8)+0x20)));
        if (temp_r3_9 != -1) {
            fn_802D6A9C();
            fn_802D7D00(arg3, temp_r3_9, 1);
        }
        fn_801F856C();
        temp_r26_11 = fn_801F9484(0x5455424F, arg3, arg1, 0x80, -1, -1);
        fn_801F856C();
        temp_r3_10 = fn_801F666C(temp_r26_11);
        if (temp_r3_10 != NULL) {
            ((u32(*)())(*(void**)((char*)((*temp_r3_10))+0x24)))();
        }
    } else if (temp_r0 == 0x4F) {
        temp_f1_9 = (*(u32*)((char*)(arg1)+0x4));
        spC = temp_f1_9;
        temp_r27_9 = lbl_8053AC98;
        sp8 = (*(u32*)((char*)(arg1)+0x0));
        (*(u32*)((char*)(temp_r27_9)+0x20)) = fn_80226BC4(&sp8, arg3 & 0xFE, temp_f1_9);
        temp_r26_12 = (*(u32*)((char*)(temp_r27_9)+0x20));
        fn_802D6A9C();
        fn_802D782C(1);
        fn_802F9974((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg3, temp_r26_12, 0x11);
        fn_802D6A9C();
        temp_r3_11 = fn_802D4C10(arg3, (u16) (*(u32*)((char*)(temp_r27_9)+0x20)));
        if (temp_r3_11 != -1) {
            fn_802D6A9C();
            fn_802D7D00(arg3, temp_r3_11, 1);
        }
        fn_801F856C();
        temp_r26_13 = fn_801F9484(0x5455424F, arg3, arg1, 0x100, -1, -1);
        fn_801F856C();
        temp_r3_12 = fn_801F666C(temp_r26_13);
        if (temp_r3_12 != NULL) {
            ((u32(*)())(*(void**)((char*)((*temp_r3_12))+0x24)))();
        }
    } else {
        var_r30 = 0;
    }
    return var_r30;
}

/* --- auto_fn_802A381C_text.s --- */


extern void *lbl_8053AB10;

void fn_802A381C(void *arg1, s32 arg2, u16 arg3) {
    f32 spC;
    f32 sp8;
    f32 temp_f1;

    temp_f1 = (*(u32*)((char*)(arg1)+0x4));
    spC = temp_f1;
    sp8 = (*(u32*)((char*)(arg1)+0x0));
    fn_802F9974((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg2, fn_80226BC4(&sp8, arg2 & 0xFE, temp_f1), arg3);
}

/* --- auto_fn_802A3884_text.s --- */






extern void *lbl_8053AB10;

void fn_802A3884(void *arg0, void *arg1, s32 arg3, u16 arg4) {
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    s32 temp_r31;
    s32 temp_r3;

    temp_f1 = (*(u32*)((char*)(arg1)+0x4));
    spC = temp_f1;
    sp8 = (*(u32*)((char*)(arg1)+0x0));
    (*(u32*)((char*)(arg0)+0x20)) = fn_80226BC4(&sp8, arg3 & 0xFE, temp_f1);
    temp_r31 = (*(u32*)((char*)(arg0)+0x20));
    fn_802D6A9C();
    fn_802D782C(1);
    fn_802F9974((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg3, temp_r31, arg4);
    fn_802D6A9C();
    temp_r3 = fn_802D4C10(arg3, (u16) (*(u32*)((char*)(arg0)+0x20)));
    if (temp_r3 != -1) {
        fn_802D6A9C();
        fn_802D7D00(arg3, temp_r3, 0);
    }
}

/* --- auto_fn_802A3948_text.s --- */






extern void *lbl_8053AB10;

void fn_802A3948(void *arg0, void *arg1, s32 arg3, u16 arg4) {
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    s32 temp_r31;
    s32 temp_r3;

    temp_f1 = (*(u32*)((char*)(arg1)+0x4));
    spC = temp_f1;
    sp8 = (*(u32*)((char*)(arg1)+0x0));
    (*(u32*)((char*)(arg0)+0x20)) = fn_80226BC4(&sp8, arg3 & 0xFE, temp_f1);
    temp_r31 = (*(u32*)((char*)(arg0)+0x20));
    fn_802D6A9C();
    fn_802D782C(1);
    fn_802F9974((*(u32*)((char*)(lbl_8053AB10)+0x20)), arg3, temp_r31, arg4);
    fn_802D6A9C();
    temp_r3 = fn_802D4C10(arg3, (u16) (*(u32*)((char*)(arg0)+0x20)));
    if (temp_r3 != -1) {
        fn_802D6A9C();
        fn_802D7D00(arg3, temp_r3, 1);
    }
}

/* --- auto_fn_802A3A0C_text.s --- */
void *fn_802D6A9C();                                /* extern */
u8 *fn_802D9C4C();                                  /* extern */
u32 fn_802FA160(s32, s32, u16, u32, u32, u32);              /* extern */
extern char lbl_8046C4A8;
extern void *lbl_8053AAF8;
extern void *lbl_8053AB10;

void fn_802A3A0C(void *arg0) {
    u16 temp_r29;
    u16 temp_r6;
    u16 temp_r6_2;
    u16 temp_r6_3;
    u16 temp_r6_4;
    u16 temp_r6_5;
    u8 *temp_r3_3;
    u8 temp_r0;
    void **temp_r3;
    void **temp_r3_2;
    void **temp_r3_4;
    void **temp_r3_5;
    void **temp_r3_6;
    void **temp_r3_7;

    (*(u32*)((char*)(arg0)+0x8)) = (s32) ((*(u32*)((char*)(arg0)+0x8)) - 1);
    if ((s32) (*(u32*)((char*)(arg0)+0x8)) == 0) {
        (*(u32*)((char*)(arg0)+0x8)) = 0xA;
        (*(u32*)((char*)(arg0)+0xC)) = (s32) ((*(u32*)((char*)(arg0)+0xC)) + 2);
        if ((s32) (*(u32*)((char*)(arg0)+0xC)) >= 0x10) {
            (*(u32*)((char*)(arg0)+0xC)) = 0;
        }
        if ((s32) fn_802D6A9C(*(u32*)((char*)(())+0x40)) == 0x10) {
            temp_r3 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            temp_r6 = *(&lbl_8046C4A8 + ((*(u32*)((char*)(arg0)+0xC)) * 2));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3))+0x18)))(temp_r3, 0x53434820, &lbl_8046C4A8 + 0x170, temp_r6), temp_r6 + 0x4000, 0, 0x3800, 0x800);
        } else {
            temp_r3_2 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            temp_r29 = *(&lbl_8046C4A8 + ((*(u32*)((char*)(arg0)+0xC)) * 2));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_2))+0x18)))(temp_r3_2, 0x53434820, &lbl_8046C4A8 + 0x170, &lbl_8046C4A8), temp_r29, 0, 0x3800, 0x800);
        }
    }
    (*(u32*)((char*)(arg0)+0x18)) = (s32) ((*(u32*)((char*)(arg0)+0x18)) - 1);
    if ((s32) (*(u32*)((char*)(arg0)+0x18)) == 0) {
        (*(u32*)((char*)(arg0)+0x18)) = 0xA;
        (*(u32*)((char*)(arg0)+0x1C)) = (s32) ((*(u32*)((char*)(arg0)+0x1C)) + 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x1C)) >= 8) {
            (*(u32*)((char*)(arg0)+0x1C)) = 0;
        }
        fn_802D6A9C();
        temp_r3_3 = fn_802D9C4C();
        temp_r0 = *temp_r3_3;
        switch ((s8) temp_r0) {                     /* irregular */
        case 0x6C:
            temp_r3_4 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            temp_r6_2 = *(&lbl_8046C4A8 + ((*(u32*)((char*)(arg0)+0x1C)) * 2));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_4))+0x18)))(temp_r3_4, 0x53434820, &lbl_8046C4A8 + 0x184, temp_r6_2), temp_r6_2 + 0x2000, 0, 0x5800, 0x400);
            (*(u32*)((char*)(arg0)+0x18)) = 0x14;
            return;
        case 0x73:
        case 0x77:
            temp_r3_5 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            temp_r6_3 = *(&lbl_8046C4A8 + ((*(u32*)((char*)(arg0)+0x1C)) * 2));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_5))+0x18)))(temp_r3_5, 0x53434820, &lbl_8046C4A8 + 0x184, temp_r6_3), temp_r6_3 + 0x6000, 0, 0x1C00, 0x400);
            return;
        case 0x6B:
        case 0x76:
            if ((s32) (*(u32*)((char*)(arg0)+0x1C)) >= 4) {
                (*(u32*)((char*)(arg0)+0x1C)) = 0;
            }
            temp_r3_6 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            temp_r6_4 = *(&lbl_8046C4A8 + ((*(u32*)((char*)(arg0)+0x1C)) * 2));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_6))+0x18)))(temp_r3_6, 0x53434820, &lbl_8046C4A8 + 0x184, temp_r6_4), temp_r6_4 + 0x1000, 0, 0x5C00, 0x400);
            return;
        default:
            if (((s32) fn_802D6A9C(*(u32*)((char*)(())+0x40)) == 0x1B) || ((s32) *temp_r3_3 == 0x79)) {
                if ((s32) (*(u32*)((char*)(arg0)+0x1C)) >= 4) {
                    (*(u32*)((char*)(arg0)+0x1C)) = 0;
                }
                temp_r3_7 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
                temp_r6_5 = *(&lbl_8046C4A8 + ((*(u32*)((char*)(arg0)+0x1C)) * 4));
                fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_7))+0x18)))(temp_r3_7, 0x53434820, &lbl_8046C4A8 + 0x184, temp_r6_5), temp_r6_5 + 0x4000, 0, 0x5800, 0x800);
            }
            break;
        }
    }
}

/* --- auto_03_802A3D80_text.s --- */
void fn_802A3D80(void *arg0) {
    (*(u32*)((char*)(arg0)+0x8)) = 0xA;
    (*(u32*)((char*)(arg0)+0xC)) = 0;
    (*(u32*)((char*)(arg0)+0x10)) = 0xA;
    (*(u32*)((char*)(arg0)+0x14)) = 0;
    (*(u32*)((char*)(arg0)+0x18)) = 0xA;
    (*(u32*)((char*)(arg0)+0x1C)) = 0;
}


/* --- auto_fn_802A3DA4_text.s --- */
u32 dtor_80084580(void *);                            /* extern */
extern char lbl_804A7C98;
extern s32 lbl_8053AC98;

void *fn_802A3DA4(void *arg0, s16 arg1) {
    char *temp_r3;

    if (arg0 != NULL) {
        (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A7C98;
        lbl_8053AC98 = 0;
        temp_r3 = (*(u32*)((char*)(arg0)+0x4));
        if (temp_r3 != NULL) {
            ((u32(*)())(*(void**)((char*)(unk8)+0x30)))(1);
        }
        (*(u32*)((char*)(arg0)+0x4)) = NULL;
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_802A3E2C_text.s --- */
s32 fn_80084370(u32, char *);                            /* extern */
u32 fn_804578F4(u32, u32, u32);                             /* extern */

extern void *lbl_8053AC98;

void *fn_802A3E2C(void *arg0) {
    s32 temp_r3;

    (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A7C98;
    lbl_8053AC98 = arg0;
    temp_r3 = fn_80084370(0x5C, &lbl_804A7C98);
    if (temp_r3 != 0) {
        fn_804578F4(0, 0, 8);
    }
    (*(u32*)((char*)(arg0)+0x4)) = temp_r3;
    return arg0;
}

/* --- auto_fn_802A3E94_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */
u32 fn_80028974(char *);                                 /* extern */
void fn_80021A6C();
void fn_80021AC0();
void fn_80021B14();
void fn_80021B68();
void fn_80021BBC();
void fn_80021C10();
void fn_80021C64();
void fn_80021CB8();
void fn_80021D0C();
extern char lbl_804B21AC;
extern char lbl_804B21BC;
extern char lbl_804B21CC;
extern char lbl_804B21DC;
extern char lbl_804B21EC;
extern char lbl_804B21FC;
extern char lbl_804B220C;
extern char lbl_804B221C;
extern char lbl_804B222C;
extern char lbl_804D0968;
extern u8 lbl_8053A2AC;
extern u8 lbl_8053A2AD;
extern u8 lbl_8053A2AE;
extern u8 lbl_8053A2AF;
extern u8 lbl_8053A2B0;
extern u8 lbl_8053A2B1;
extern u8 lbl_8053A2B2;
extern u8 lbl_8053A2B3;
extern u8 lbl_8053A2B4;

void fn_802A3E94(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D0968);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D0968 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D0968 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D0968 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D0968 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D0968 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D0968 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D0968 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D0968 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802A40B8_text.s --- */

u32 dtor_801F593C(u32, char *);                            /* extern */
extern char lbl_804A7E58;

char **fn_802A40B8(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804A7E58;
        dtor_801F593C(0, &lbl_804A7E58);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_802A4118_text.s --- */
u32 fn_801F06F0(char *, u32, u32, u32, f32, f32);              /* extern */
u32 fn_803075AC(s32, s32, s32, u32, u32, u32, u32, u32);        /* extern */
extern char lbl_8046C640;
extern f32 lbl_805407A0;

void fn_802A4118(void *arg0) {
    s32 spC;
    s32 sp8;

    fn_801F06F0(&lbl_8046C640, 0x31, 0, 1, lbl_805407A0, lbl_805407A0);
    sp8 = 0;
    spC = 0;
    fn_803075AC((*(u32*)((char*)(arg0)+0x198)), (*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, 0x31, 0, 2, -1, 0);
}

/* --- auto_fn_802A4190_text.s --- */
u32 fn_801F856C();                                    /* extern */

u32 fn_80230224(s32, u32);                              /* extern */
u8 fn_802308E0(s32, f32, f32, f32);                 /* extern */
s32 fn_8023AF14(f32 *, s32, u32, f32, f32, f32, f32, f32); /* extern */
void *fn_8023E724(s32);                             /* extern */
u8 fn_8023EBB8(s32);                                /* extern */
u8 fn_8023ED8C();                                   /* extern */
u32 fn_8030C210(s32, f32 *, f32, f32);                /* extern */
u8 fn_80388EEC(s32);                                /* extern */
extern void *lbl_8053AB10;
extern f32 lbl_805407A4;
extern f32 lbl_805407A8;
extern f32 lbl_805407AC;
extern f32 lbl_805407B0;

void fn_802A4190(void *arg0) {
    f32 sp2C;
    f32 sp20;
    f32 sp1C;
    f32 sp18;
    f32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f0;
    f32 temp_f0_2;
    f32 temp_f0_3;
    f32 temp_f1;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f2_3;
    f32 temp_f3;
    f32 temp_f3_2;
    f32 temp_f4;
    f32 temp_f5;
    f32 temp_f5_2;
    f32 temp_f6;
    s32 temp_r0;
    s32 temp_r0_2;
    s32 temp_r3;

    temp_r0 = (*(u32*)((char*)(arg0)+0x230));
    temp_f6 = (*(u32*)((char*)(arg0)+0x10));
    temp_f5 = (*(u32*)((char*)(arg0)+0xC));
    switch (temp_r0) {                              /* irregular */
    case 0:
        if ((lbl_805407A4 != (*(u32*)((char*)(arg0)+0x14))) || (lbl_805407A4 != (*(u32*)((char*)(arg0)+0x44)))) {
            M2C_ERROR(/* unknown instruction: ps_add $f2, $f2, $f0 */);
            M2C_ERROR(/* unknown instruction: ps_add $f2, $f3, $f2 */);
            (*(u32*)((char*)(arg0)+0x44)) = (f32) ((*(u32*)((char*)(arg0)+0x44)) - lbl_805407A8);
            M2C_ERROR(/* unknown instruction: cror eq, lt, eq */);
            if ((*(u32*)((char*)(arg0)+0x14)) == lbl_805407A4) {
                (*(u32*)((char*)(arg0)+0x14)) = (f32) lbl_805407A4;
                (*(u32*)((char*)(arg0)+0x44)) = (f32) lbl_805407A4;
                (*(u32*)((char*)(arg0)+0x40)) = (f32) lbl_805407A4;
                (*(u32*)((char*)(arg0)+0x3C)) = (f32) lbl_805407A4;
            }
        }
        temp_f0 = (*(u32*)((char*)(arg0)+0x60));
        sp14 = temp_f0;
        temp_f4 = temp_f0 + temp_f5;
        temp_f0_2 = (*(u32*)((char*)(arg0)+0x64));
        sp18 = temp_f0_2;
        temp_f3 = temp_f0_2 + temp_f6;
        temp_f0_3 = (*(u32*)((char*)(arg0)+0x68));
        sp1C = temp_f0_3;
        temp_f2 = temp_f0_3 + temp_f5;
        temp_f5_2 = (*(u32*)((char*)(arg0)+0x6C));
        sp20 = temp_f5_2;
        sp14 = temp_f4;
        sp18 = temp_f3;
        sp1C = temp_f2;
        sp20 = temp_f5_2 + temp_f6;
        (*(u32*)((char*)(arg0)+0x238)) = fn_8023AF14(&sp14, (*(u32*)((char*)(arg0)+0x4)), 1, lbl_805407A4, temp_f2, temp_f3, temp_f4, temp_f5_2);
        if (((s32) (*(u32*)((char*)(arg0)+0x238)) >= 0) && (fn_8023ED8C() == 0) && (fn_8023EBB8((*(u32*)((char*)(arg0)+0x238))) == 0)) {
            M2C_ERROR(/* unknown instruction: cror eq, lt, eq */);
            if ((*(u32*)((char*)(arg0)+0x14)) == lbl_805407A4) {
                temp_f3_2 = fn_8023E724(*(u32*)((char*)(((*(u32*)((char*)(arg0)+0x238))))+0x8));
                temp_f2_2 = lbl_805407AC + sp24;
                sp2C = temp_f3_2;
                (*(u32*)((char*)(arg0)+0xC)) = temp_f2_2;
                (*(u32*)((char*)(arg0)+0x10)) = (f32) (sp28 - lbl_805407B0);
                if (fn_802308E0((*(u32*)((char*)(arg0)+0x238)), sp28, temp_f2_2, temp_f3_2) == 1) {
                    fn_801F856C();
                    temp_r0_2 = (*(u32*)((char*)(arg0)+0x238));
                    fn_801F9484(0x494D5550, (*(u32*)((char*)(arg0)+0x4)), arg0 + 0xC, (temp_r0_2 << 0x18) + 0x800000 + (temp_r0_2 << 0x1A) + 0x14, -1, -1);
                    (*(u32*)((char*)(arg0)+0x11C)) = 0;
                }
            }
        }
        break;
    case 1:
        if (((s32) (*(u32*)((char*)(arg0)+0x234)) == 0) && (fn_80388EEC((*(u32*)((char*)(arg0)+0x238))) != 0)) {
            fn_80230224((*(u32*)((char*)(arg0)+0x238)), 0);
            fn_80230224((*(u32*)((char*)(arg0)+0x90)) & 0xF, 0);
            (*(u32*)((char*)(arg0)+0x11C)) = 0;
        } else {
            temp_r3 = (*(u32*)((char*)(arg0)+0x234));
            if (temp_r3 != 0) {
                (*(u32*)((char*)(arg0)+0x234)) = (s32) (temp_r3 - 1);
            }
        }
        break;
    }
    if ((s32) (*(u32*)((char*)(arg0)+0x4)) < 8) {
        temp_f1 = (*(u32*)((char*)(arg0)+0xC));
        temp_f2_3 = (*(u32*)((char*)(arg0)+0x10)) - (*(u32*)((char*)(arg0)+0x14));
        sp8 = temp_f1;
        spC = temp_f2_3;
        sp10 = lbl_805407A4;
        fn_8030C210((*(u32*)((char*)(lbl_8053AB10)+0x24)), &sp8, temp_f1, temp_f2_3);
    }
}

/* --- auto_03_802A4404_text.s --- */

extern f32 lbl_805407B4;
extern f32 lbl_805407B8;

void fn_802A4404(void *arg0) {
    (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_805407B4;
    (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_805407B4;
    (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_805407B8;
    (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_805407B8;
    (*(u32*)((char*)(arg0)+0x44)) = (f32) lbl_805407A4;
    (*(u32*)((char*)(arg0)+0x230)) = 0;
}

/* --- auto_fn_802A4430_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D0A68;










void fn_802A4430(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D0A68);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D0A68 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D0A68 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D0A68 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D0A68 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D0A68 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D0A68 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D0A68 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D0A68 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802A4654_text.s --- */
u32 fn_801F0E34(void *, u32, u32, void *);                /* extern */

extern char lbl_8046C658;
extern char lbl_8046C6C8;
extern void *lbl_8053AB10;

void fn_802A4654(void *arg0) {
    f32 temp_f28;
    f32 temp_f29;
    f32 temp_f30;
    s32 var_r30;
    s32 var_r31;
    char *temp_r6;

    temp_f30 = (*(u32*)((char*)(arg0)+0xC));
    temp_f29 = (*(u32*)((char*)(arg0)+0x10));
    temp_f28 = (*(u32*)((char*)(arg0)+0x14));
    var_r30 = 0;
    var_r31 = 0;
    do {
        (*(u32*)((char*)(arg0)+0xC)) = (f32) (temp_f30 + (f32) *(&lbl_8046C658 + ((*(u32*)((char*)(arg0)+0x234)) * 0x10) + var_r31));
        temp_r6 = &lbl_8046C6C8 + ((*(u32*)((char*)(arg0)+0x234)) * 0x10);
        (*(u32*)((char*)(arg0)+0x10)) = (f32) (temp_f29 + (f32) *(temp_r6 + var_r31));
        fn_801F0E34(arg0, 0x30084, 0, temp_r6);
        fn_8030C210((*(u32*)((char*)(lbl_8053AB10)+0x24)), arg0 + 0xC);
        var_r30 += 1;
        var_r31 += 4;
    } while (var_r30 < 4);
    (*(u32*)((char*)(arg0)+0xC)) = temp_f30;
    (*(u32*)((char*)(arg0)+0x10)) = temp_f29;
    (*(u32*)((char*)(arg0)+0x14)) = temp_f28;
}

/* --- auto_fn_802A4780_text.s --- */
u32 fn_802F86CC(s32, f32 *, s32, s32, char *, f32, f32); /* extern */

extern void *lbl_8053AAF8;
extern void *lbl_8053AB10;
extern f32 lbl_805407C8;

void fn_802A4780(void *arg0) {
    s32 sp58;
    s32 sp54;
    s32 sp50;
    s8 sp4E;
    s8 sp4D;
    s8 sp4C;
    s32 sp48;
    s8 sp46;
    s8 sp45;
    s8 sp44;
    s8 sp43;
    s8 sp42;
    s8 sp41;
    s8 sp40;
    s8 sp3F;
    s8 sp3E;
    s8 sp3D;
    s8 sp3C;
    s32 sp38;
    s32 sp34;
    s32 sp30;
    u32 sp20;
    f32 sp1C;
    f32 sp18;
    f32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    s32 temp_r0;
    s32 temp_r0_3;
    s32 temp_r24;
    s32 temp_r29;
    s32 var_r27;
    s32 var_r28;
    s32 var_r28_2;
    u8 temp_r0_2;
    u8 temp_r3;
    u8 temp_r3_2;
    u8 temp_r4;
    u8 temp_r4_2;
    u8 temp_r5;
    u8 temp_r5_2;
    u8 temp_r6;
    u8 temp_r7;
    u8 temp_r8;
    u8 var_r10;
    void **temp_r3_3;
    void **temp_r3_4;
    char *var_r25;
    char *var_r27_2;

    temp_r0 = (*(u32*)((char*)(arg0)+0x230));
    if ((temp_r0 >= 2) && (temp_r0 < 9)) {
        sp30 = -1;
        var_r10 = 0;
        sp34 = -1;
loop_4:
        if (var_r10 < 0x10U) {
            temp_r7 = var_r10 + 5;
            temp_r5 = var_r10 + 1;
            *(&sp20 + var_r10) = var_r10;
            temp_r3 = var_r10 + 2;
            *(&sp20 + temp_r5) = temp_r5;
            temp_r4 = var_r10 + 3;
            temp_r8 = var_r10 + 4;
            *(&sp20 + temp_r3) = temp_r3;
            temp_r6 = temp_r7;
            temp_r5_2 = var_r10 + 6;
            *(&sp20 + temp_r4) = temp_r4;
            temp_r3_2 = var_r10 + 7;
            temp_r4_2 = temp_r5_2;
            *(&sp20 + temp_r8) = temp_r8;
            temp_r0_2 = temp_r3_2;
            var_r10 += 8;
            *(&sp20 + temp_r6) = temp_r7;
            *(&sp20 + temp_r4_2) = temp_r5_2;
            *(&sp20 + temp_r0_2) = temp_r3_2;
            goto loop_4;
        }
        var_r28 = 0;
        sp30 = -1;
        sp34 = 0;
        var_r27 = 0;
        sp38 = 0;
        sp3C = 0;
        sp3D = 0;
        sp3E = 0;
        sp3F = 1;
        sp40 = 1;
        sp41 = 0;
        sp42 = 0;
        sp43 = 0;
        sp44 = 0;
        sp45 = 0;
        sp46 = 1;
        sp48 = 3;
        sp4C = 1;
        sp4D = 0;
        sp4E = 0;
        sp50 = -1;
        sp54 = 0;
        sp58 = 2;
        do {
            sp3D = -1;
            temp_r0_3 = ((*(u32*)((char*)(arg0)+0x234)) * 0x10) + var_r28;
            temp_r29 = (*(u32*)((char*)(arg0)+0x250)) + 0x10D;
            sp1C = (*(u32*)((char*)(arg0)+0x14));
            sp18 = (*(u32*)((char*)(arg0)+0x10)) + (f32) *(&lbl_8046C658 + 0x70 + temp_r0_3);
            sp14 = (*(u32*)((char*)(arg0)+0xC)) + (f32) *(&lbl_8046C658 + temp_r0_3);
            if ((s32) (*(u32*)((char*)(arg0)+0x4)) < 8) {
                temp_r3_3 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
                fn_802F86CC((*(u32*)((char*)(lbl_8053AB10)+0x20)), &sp14, ((u32(*)())(*(void**)((char*)((*temp_r3_3))+0x18)))(temp_r3_3, 0x534F4220, &lbl_8046C658 + 0x1BC, lbl_8053AAF8), temp_r29, &sp20, lbl_805407C8, lbl_805407C8);
            }
            var_r27 += 1;
            var_r28 += 4;
        } while (var_r27 < 4);
        var_r25 = arg0;
        var_r27_2 = arg0;
        var_r28_2 = 0;
        do {
            if ((s32) (*(u32*)((char*)(var_r25)+0x254)) >= 0) {
                sp3D = -1;
                temp_r24 = (*(u32*)((char*)(arg0)+0x250)) + 0x10A;
                sp8 = (*(u32*)((char*)(var_r27_2)+0x264));
                spC = (*(u32*)((char*)(var_r27_2)+0x268));
                sp10 = (*(u32*)((char*)(var_r27_2)+0x26C));
                if ((s32) (*(u32*)((char*)(arg0)+0x4)) < 8) {
                    temp_r3_4 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
                    fn_802F86CC((*(u32*)((char*)(lbl_8053AB10)+0x20)), &sp8, ((u32(*)())(*(void**)((char*)((*temp_r3_4))+0x18)))(temp_r3_4, 0x534F4220, &lbl_8046C658 + 0x1BC, lbl_8053AAF8), temp_r24, &sp20, lbl_805407C8, lbl_805407C8);
                }
            }
            var_r28_2 += 1;
            var_r27_2 += 0xC;
            var_r25 += 4;
        } while (var_r28_2 < 4);
    }
}

/* --- auto_fn_802A4A4C_text.s --- */
/*
Decompilation failure in function fn_802A4A4C:

Found bctr instruction at auto_fn_802A4A4C_text.s line 61, but the corresponding jump table is not provided.

Please include it in the input .s file(s), or in an additional file.

*/

/* --- auto_fn_802A64E8_text.s --- */


u32 fn_800EC240(s32, u32);                            /* extern */
void *fn_8013C824();                                /* extern */
extern char lbl_804A7EB0;

char **fn_802A64E8(char **arg0, s16 arg1) {
    char **var_r31;
    s32 var_r30;

    if (arg0 != NULL) {
        var_r31 = arg0;
        var_r30 = 0;
        *arg0 = &lbl_804A7EB0;
        do {
            if ((u32) (*(u32*)((char*)(var_r31)+0x2B4)) != 0U) {
                fn_800EC240(fn_8013C824(*(u32*)((char*)(())+0xC)), (*(u32*)((char*)(var_r31)+0x2B4)));
            }
            if ((u32) (*(u32*)((char*)(var_r31)+0x2C4)) != 0U) {
                fn_800EC240(fn_8013C824(*(u32*)((char*)(())+0xC)), (*(u32*)((char*)(var_r31)+0x2C4)));
            }
            if ((u32) (*(u32*)((char*)(var_r31)+0x2D4)) != 0U) {
                fn_800EC240(fn_8013C824(*(u32*)((char*)(())+0xC)), (*(u32*)((char*)(var_r31)+0x2D4)));
            }
            if ((u32) (*(u32*)((char*)(var_r31)+0x2E4)) != 0U) {
                fn_800EC240(fn_8013C824(*(u32*)((char*)(())+0xC)), (*(u32*)((char*)(var_r31)+0x2E4)));
            }
            if ((u32) (*(u32*)((char*)(var_r31)+0x2F4)) != 0U) {
                fn_800EC240(fn_8013C824(*(u32*)((char*)(())+0xC)), (*(u32*)((char*)(var_r31)+0x2F4)));
            }
            var_r30 += 1;
            var_r31 += 4;
        } while (var_r30 < 4);
        dtor_801F593C(arg0, 0);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_802A6600_text.s --- */
u32 fn_8022ADE4();                                    /* extern */
s32 fn_80236228(s32);                               /* extern */

u32 fn_802D7440(u32);                                   /* extern */
u32 fn_802D752C(u32);                                   /* extern */
extern void *lbl_8053AAF8;
extern f32 lbl_805407D0;
extern f32 lbl_805407E0;
extern f32 lbl_805407E4;
extern f32 lbl_805407E8;

void fn_802A6600(void *arg0) {
    s32 temp_r3_2;
    s32 var_r28;
    s32 var_r29;
    u32 temp_r3;

    (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_805407E0;
    (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_805407E0;
    (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_805407E4;
    (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_805407E4;
    (*(u32*)((char*)(arg0)+0x230)) = 0;
    (*(u32*)((char*)(arg0)+0x44)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x24C)) = 9;
    (*(u32*)((char*)(arg0)+0x250)) = 0;
    (*(u32*)((char*)(arg0)+0x2A4)) = -1;
    (*(u32*)((char*)(arg0)+0x254)) = -1;
    (*(u32*)((char*)(arg0)+0x2B4)) = 0;
    (*(u32*)((char*)(arg0)+0x2C4)) = 0;
    (*(u32*)((char*)(arg0)+0x2D4)) = 0;
    (*(u32*)((char*)(arg0)+0x2E4)) = 0;
    (*(u32*)((char*)(arg0)+0x2F4)) = 0;
    (*(u32*)((char*)(arg0)+0x264)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x268)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x26C)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x2A8)) = -1;
    (*(u32*)((char*)(arg0)+0x258)) = -1;
    (*(u32*)((char*)(arg0)+0x2B8)) = 0;
    (*(u32*)((char*)(arg0)+0x2C8)) = 0;
    (*(u32*)((char*)(arg0)+0x2D8)) = 0;
    (*(u32*)((char*)(arg0)+0x2E8)) = 0;
    (*(u32*)((char*)(arg0)+0x2F8)) = 0;
    (*(u32*)((char*)(arg0)+0x270)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x274)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x278)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x2AC)) = -1;
    (*(u32*)((char*)(arg0)+0x25C)) = -1;
    (*(u32*)((char*)(arg0)+0x2BC)) = 0;
    (*(u32*)((char*)(arg0)+0x2CC)) = 0;
    (*(u32*)((char*)(arg0)+0x2DC)) = 0;
    (*(u32*)((char*)(arg0)+0x2EC)) = 0;
    (*(u32*)((char*)(arg0)+0x2FC)) = 0;
    (*(u32*)((char*)(arg0)+0x27C)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x280)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x284)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x2B0)) = -1;
    (*(u32*)((char*)(arg0)+0x260)) = -1;
    (*(u32*)((char*)(arg0)+0x2C0)) = 0;
    (*(u32*)((char*)(arg0)+0x2D0)) = 0;
    (*(u32*)((char*)(arg0)+0x2E0)) = 0;
    (*(u32*)((char*)(arg0)+0x2F0)) = 0;
    (*(u32*)((char*)(arg0)+0x300)) = 0;
    (*(u32*)((char*)(arg0)+0x288)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x28C)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x290)) = (f32) lbl_805407D0;
    (*(u32*)((char*)(arg0)+0x304)) = 0;
    (*(u32*)((char*)(arg0)+0x30C)) = 0;
    (*(u32*)((char*)(arg0)+0x310)) = 1;
    (*(u32*)((char*)(arg0)+0x238)) = (s32) ((*(u32*)((char*)(arg0)+0x90)) & 0x1F);
    (*(u32*)((char*)(arg0)+0x23C)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x11U) & 0x1F);
    (*(u32*)((char*)(arg0)+0x240)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x16U) & 0x1F);
    (*(u32*)((char*)(arg0)+0x234)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0xCU) & 0x1F);
    temp_r3 = (*(u32*)((char*)(arg0)+0x90));
    if ((temp_r3 >> 7U) & 1) {
        (*(u32*)((char*)(arg0)+0xC)) = (f32) ((*(u32*)((char*)(arg0)+0xC)) + lbl_805407E8);
    }
    if ((temp_r3 >> 7U) & 0x1F & 2) {
        (*(u32*)((char*)(arg0)+0x10)) = (f32) ((*(u32*)((char*)(arg0)+0x10)) + lbl_805407E8);
    }
    fn_802D6A9C();
    fn_802D752C(1);
    fn_802D6A9C();
    fn_802D7440(0);
    fn_8022ADE4();
    var_r29 = 0;
    var_r28 = 0;
    do {
        temp_r3_2 = (*(u32*)((char*)(lbl_8053AAF8)+0x82)) & (u8) (1 << var_r28);
        if ((u32) ((u32) (-temp_r3_2 | temp_r3_2) >> 0x1FU) == 1) {
            var_r29 += fn_80236228(var_r28);
        }
        var_r28 += 1;
    } while (var_r28 < 4);
    (*(u32*)((char*)(arg0)+0x314)) = 0;
    (*(u32*)((char*)(arg0)+0x318)) = 0;
    (*(u32*)((char*)(arg0)+0x31C)) = 1;
loop_9:
    if (var_r29 >= 0x3E8) {
        var_r29 -= 0x3E8;
        (*(u32*)((char*)(arg0)+0x314)) = (s32) ((*(u32*)((char*)(arg0)+0x314)) + 1);
        goto loop_9;
    }
}

/* --- auto_fn_802A6828_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D0B68;










void fn_802A6828(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D0B68);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D0B68 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D0B68 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D0B68 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D0B68 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D0B68 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D0B68 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D0B68 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D0B68 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802A6A4C_text.s --- */


extern char lbl_804A7F38;

char **fn_802A6A4C(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804A7F38;
        dtor_801F593C(0, &lbl_804A7F38);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_fn_802A6AAC_text.s --- */
u32 fn_802A3948(s32, void *, s32, s32, u32);            /* extern */


void fn_802A6AAC(void *arg0, s32 arg1) {
    u16 temp_r0;

    temp_r0 = (*(u32*)((char*)(arg0)+0x258));
    switch ((s32) temp_r0) {                        /* irregular */
    case 0x68:
    case 0x41:
        fn_802A3948(lbl_8053AC98, arg0 + 0xC, arg1, (*(u32*)((char*)(arg0)+0x4)), 0x13);
        return;
    case 0x50:
    case 0x6A:
    case 0x43:
        fn_802A3948(lbl_8053AC98, arg0 + 0xC, arg1, (*(u32*)((char*)(arg0)+0x4)), 0x51);
        return;
    case 0x52:
    case 0x14:
        fn_802A3948(lbl_8053AC98, arg0 + 0xC, arg1, (*(u32*)((char*)(arg0)+0x4)), 0x15);
        return;
    case 0x15A:
        fn_802A3948(lbl_8053AC98, arg0 + 0xC, arg1, (*(u32*)((char*)(arg0)+0x4)), 0x360);
        /* fallthrough */
        return;
    }
}

/* --- auto_03_802A6BC0_text.s --- */
void fn_802A6BC0(void) {

}

/* --- auto_fn_802A6BC4_text.s --- */
/*
Decompilation failure in function fn_802A6BC4:

Found bctr instruction at auto_fn_802A6BC4_text.s line 160, but the corresponding jump table is not provided.

Please include it in the input .s file(s), or in an additional file.

*/

/* --- auto_fn_802A75F4_text.s --- */
void *fn_801F856C();                                /* extern */
s32 fn_80226AE0(void *, s32);                       /* extern */
u32 fn_802A3884(s32, void *, u32, s32, u16);            /* extern */

u8 fn_802D800C(u32);                                /* extern */

extern s32 lbl_8046C828;
extern void *lbl_8053AB10;


void fn_802A75F4(void *arg0) {
    s32 *var_r5;
    s32 temp_r29;
    s32 temp_r31;
    s32 temp_r3_2;
    s32 var_ctr;
    s32 var_r29;
    s32 var_r30;
    u16 temp_r0_2;
    u16 temp_r0_3;
    u16 temp_r0_4;
    u16 temp_r3;
    u32 temp_r0;
    u32 temp_r4_2;
    char *temp_r4;

    if ((s32) (*(u32*)((char*)(arg0)+0x230)) == 1) {
        if (((u32(*)())(*(void**)((char*)(unk0)+0x34)))() != 0) {
            (*(u32*)((char*)(arg0)+0x244)) = fn_80226AE0(arg0 + 0xC, (*(u32*)((char*)(arg0)+0x4)));
            (*(u32*)((char*)(arg0)+0x258)) = (u16) (fn_802F9908((*(u32*)((char*)(lbl_8053AB10)+0x20)), (*(u32*)((char*)(arg0)+0x4)), (*(u32*)((char*)(arg0)+0x244))) & 0x3FF);
            ((u32(*)())(*(void**)((char*)(unk0)+0x54)))(arg0, -1);
            (*(u32*)((char*)(arg0)+0x11C)) = 0;
            return;
        }
        (*(u32*)((char*)(arg0)+0x244)) = fn_80226AE0(arg0 + 0xC, (*(u32*)((char*)(arg0)+0x4)));
        (*(u32*)((char*)(arg0)+0x258)) = (u16) (fn_802F9908((*(u32*)((char*)(lbl_8053AB10)+0x20)), (*(u32*)((char*)(arg0)+0x4)), (*(u32*)((char*)(arg0)+0x244))) & 0x3FF);
        temp_r3 = (*(u32*)((char*)(arg0)+0x258));
        if ((temp_r3 == 0x12) || (temp_r3 == 0x50) || (temp_r3 == 0x52) || (temp_r3 == 0x41) || (temp_r3 == 0x43) || (temp_r3 == 0x68) || (temp_r3 == 0x6A) || (temp_r3 == 0x15A) || ((u16) (temp_r3 - 0x13) <= 1U) || (temp_r3 == 0x51)) {
            (*(u32*)((char*)(arg0)+0x230)) = 2;
            if ((u16) (*(u32*)((char*)(arg0)+0x258)) == 0x41) {
                (*(u32*)((char*)(arg0)+0x258)) = 0x12U;
            }
            temp_r29 = (*(u32*)((char*)(arg0)+0x264));
            if (temp_r29 < 0) {
                temp_r31 = fn_801F856C(*(u32*)((char*)(())+0x1008));
                var_r29 = 0;
                var_r30 = 0;
loop_35:
                if (var_r29 < temp_r31) {
                    temp_r4 = *(fn_801F856C() + (var_r30 + 8));
                    if ((temp_r4 != NULL) && ((temp_r3_2 = (*(u32*)((char*)(temp_r4)+0x1A0)), (((u32) (temp_r3_2 + 0xACA90000) == 0x5434U) != 0)) || ((u32) (temp_r3_2 + 0xB3B10000) == 0x5357U)) && ((s32) (*(u32*)((char*)(arg0)+0x170)) == (s32) (*(u32*)((char*)(temp_r4)+0x170))) && ((temp_r4_2 = (*(u32*)((char*)(temp_r4)+0x90)), temp_r0 = temp_r4_2 & 0x1F, ((temp_r0 == 1) != 0)) || (temp_r0 == 2))) {
                        var_r5 = &lbl_8046C828;
                        var_ctr = 4;
loop_24:
                        if ((u32) (*(u32*)((char*)(arg0)+0x25C)) == (u32) ((temp_r4_2 >> *var_r5) & 0x1F)) {
                            (*(u32*)((char*)(arg0)+0x260)) = (u32) (temp_r4_2 >> 0x1BU);
                            fn_802D6A9C();
                            if (fn_802D800C((*(u32*)((char*)(arg0)+0x260))) != 0) {
                                ((u32(*)())(*(void**)((char*)(unk0)+0x54)))(arg0, -1);
                                (*(u32*)((char*)(arg0)+0x11C)) = 0;
                            } else {
                                temp_r0_2 = (*(u32*)((char*)(arg0)+0x258));
                                if ((temp_r0_2 == 0x13) || (temp_r0_2 == 0x51)) {
                                    if (temp_r0_2 == 0x13) {
                                        (*(u32*)((char*)(arg0)+0x258)) = 0x12U;
                                    } else {
                                        (*(u32*)((char*)(arg0)+0x258)) = 0x51U;
                                    }
                                    ((u32(*)())(*(void**)((char*)(unk0)+0x30)))(arg0, 0xFF, 0);
                                    fn_802A3884(lbl_8053AC98, arg0 + 0xC, -1, (*(u32*)((char*)(arg0)+0x4)), (*(u32*)((char*)(arg0)+0x258)));
                                }
                            }
                        } else {
                            var_r5 += 4;
                            var_ctr -= 1;
                            if (var_ctr != 0) {
                                goto loop_24;
                            }
                        }
                    }
                    var_r30 += 4;
                    var_r29 += 1;
                    goto loop_35;
                }
                temp_r0_3 = (*(u32*)((char*)(arg0)+0x258));
                if ((temp_r0_3 == 0x43) || (temp_r0_3 == 0x68) || (temp_r0_3 == 0x6A) || (temp_r0_3 == 0x41)) {
                    if (((u32(*)())(*(void**)((char*)(unk0)+0x34)))(arg0) != 0) {
                        ((u32(*)())(*(void**)((char*)(unk0)+0x54)))(arg0, -1);
                        (*(u32*)((char*)(arg0)+0x11C)) = 0;
                        return;
                    }
                    (*(u32*)((char*)(arg0)+0x230)) = 1;
                }
            } else {
                fn_802D6A9C();
                if (fn_802D800C((u32) temp_r29) != 0) {
                    ((u32(*)())(*(void**)((char*)(unk0)+0x54)))(arg0, -1);
                    (*(u32*)((char*)(arg0)+0x11C)) = 0;
                    return;
                }
                temp_r0_4 = (*(u32*)((char*)(arg0)+0x258));
                if ((temp_r0_4 == 0x43) || (temp_r0_4 == 0x68) || (temp_r0_4 == 0x6A)) {
                    (*(u32*)((char*)(arg0)+0x230)) = 1;
                }
            }
        }
    }
}

/* --- auto_fn_802A7978_text.s --- */
extern f32 lbl_80540804;
extern f32 lbl_80540808;
extern f32 lbl_8054080C;
extern f32 lbl_80540810;

void fn_802A7978(void *arg0) {
    f32 temp_f1;
    f32 temp_f4;
    s32 temp_r0;
    s32 temp_r0_2;

    (*(u32*)((char*)(arg0)+0x238)) = (s32) ((((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x16U) & 0x1F) + 1);
    (*(u32*)((char*)(arg0)+0x23C)) = (s32) ((((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x11U) & 0x1F) + 1);
    (*(u32*)((char*)(arg0)+0x240)) = (s32) ((*(u32*)((char*)(arg0)+0x90)) & 0x3E0);
    (*(u32*)((char*)(arg0)+0x234)) = (s32) ((*(u32*)((char*)(arg0)+0x90)) & 0x1F);
    (*(u32*)((char*)(arg0)+0x264)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0xCU) & 0x1F);
    if ((s32) (*(u32*)((char*)(arg0)+0x264)) == 0) {
        (*(u32*)((char*)(arg0)+0x264)) = -1;
    }
    (*(u32*)((char*)(arg0)+0x25C)) = (u32) ((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x1BU);
    if (((s32) (*(u32*)((char*)(arg0)+0x234)) == 8) && ((s32) (*(u32*)((char*)(arg0)+0x240)) == 0)) {
        (*(u32*)((char*)(arg0)+0x240)) = 0x3C;
    }
    (*(u32*)((char*)(arg0)+0x24C)) = (s32) (*(u32*)((char*)(arg0)+0x240));
    (*(u32*)((char*)(arg0)+0xC)) = (f32) ((*(u32*)((char*)(arg0)+0xC)) + lbl_80540804);
    (*(u32*)((char*)(arg0)+0x10)) = (f32) ((*(u32*)((char*)(arg0)+0x10)) + lbl_80540804);
    temp_r0 = (*(u32*)((char*)(arg0)+0x234));
    switch (temp_r0) {                              /* irregular */
    case 2:
    case 3:
        (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_80540808;
        (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_80540808;
        (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8054080C;
        (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8054080C;
        break;
    case 7:
        temp_f4 = lbl_80540810 * (f32) (*(u32*)((char*)(arg0)+0x238));
        temp_f1 = lbl_80540810 * (f32) (*(u32*)((char*)(arg0)+0x23C));
        (*(u32*)((char*)(arg0)+0x60)) = (f32) -temp_f4;
        (*(u32*)((char*)(arg0)+0x64)) = (f32) -temp_f1;
        (*(u32*)((char*)(arg0)+0x68)) = temp_f4;
        (*(u32*)((char*)(arg0)+0x6C)) = temp_f1;
        break;
    default:
        (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_80540808;
        (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_80540808;
        (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_8054080C;
        (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_8054080C;
        break;
    }
    (*(u32*)((char*)(arg0)+0x248)) = 0;
    temp_r0_2 = (*(u32*)((char*)(arg0)+0x234));
    if ((temp_r0_2 == 4) || (temp_r0_2 == 7)) {
        (*(u32*)((char*)(arg0)+0x230)) = 2;
    } else {
        (*(u32*)((char*)(arg0)+0x230)) = 1;
    }
    (*(u32*)((char*)(arg0)+0x250)) = -1;
    (*(u32*)((char*)(arg0)+0x260)) = -1;
}

/* --- auto_fn_802A7B18_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D0C68;










void fn_802A7B18(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D0C68);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D0C68 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D0C68 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D0C68 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D0C68 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D0C68 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D0C68 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D0C68 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D0C68 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_03_802A7D3C_text.s --- */
void fn_802A7D3C(void) {

}

/* --- auto_fn_802A7D40_text.s --- */
void *fn_8013CC50(s32, f32 *, u32, u32, u32, u32, u32, u32, f32, f32, f32); /* extern */

u32 fn_801F2B7C(void *, s32, u32, u32);                   /* extern */

void *fn_802D6A9C();                                /* extern */
u32 fn_802D79E8(s32, u32, f32, f32);                    /* extern */
extern f32 lbl_80540820;
extern f32 lbl_80540824;
extern f32 lbl_80540828;
extern f32 lbl_8054082C;
extern f32 lbl_80540830;

void fn_802A7D40(void *arg0) {
    f64 sp18;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f3;
    s32 temp_r0;
    s32 temp_r3_2;
    char *temp_r3;
    char *temp_r5;

    temp_r3 = fn_802D6A9C();
    temp_r0 = (*(u32*)((char*)(arg0)+0x230));
    switch (temp_r0) {                              /* irregular */
    case 0:
        (*(u32*)((char*)(arg0)+0x234)) = (s32) ((*(u32*)((char*)(arg0)+0x234)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x234)) == 0) {
            (*(u32*)((char*)(arg0)+0x230)) = 1;
            if ((s32) (u8) (*(u32*)((char*)(arg0)+0x90)) != 1) {
                return;
            }
            sp18 = (f64) (s32) ((*(u32*)((char*)(arg0)+0x10)) - (*(u32*)((char*)(temp_r3)+0xD0)));
            return;
        }
        return;
    case 1:
        if (((u32(*)())(*(void**)((char*)(unk0)+0x34)))(arg0) != 0) {
            (*(u32*)((char*)(arg0)+0x230)) = 2;
            (*(u32*)((char*)(arg0)+0x234)) = 1;
            return;
        }
        break;
    case 2:
        temp_r3_2 = (*(u32*)((char*)(arg0)+0x234));
        if (temp_r3_2 == 0) {
            if ((void *) (*(u32*)((char*)(arg0)+0x238)) == NULL) {
                temp_f2 = lbl_80540820 + (*(u32*)((char*)(arg0)+0x10));
                temp_f3 = (*(u32*)((char*)(arg0)+0x14));
                spC = temp_f2;
                sp8 = lbl_80540824 + (*(u32*)((char*)(arg0)+0xC));
                sp10 = temp_f3;
                (*(u32*)((char*)(arg0)+0x238)) = fn_8013CC50((*(u32*)((char*)(arg0)+0x4)), &sp8, 0x173, 1, 0, 0, 0, 1, lbl_80540828, temp_f2, temp_f3);
                (*(u32*)((char*)(arg0)+0x230)) = 3;
                temp_f2_2 = (*(u32*)((char*)(arg0)+0xC));
                (*(u32*)((char*)(arg0)+0xC)) = (f32) (temp_f2_2 + lbl_80540824);
                temp_f1 = (*(u32*)((char*)(arg0)+0x10));
                (*(u32*)((char*)(arg0)+0x10)) = (f32) (temp_f1 + lbl_80540820);
                fn_801F0E34(arg0, 0x30001, 0, temp_f1, temp_f2_2);
                (*(u32*)((char*)(arg0)+0x234)) = 0x14;
                return;
            }
        } else {
            (*(u32*)((char*)(arg0)+0x234)) = (s32) (temp_r3_2 - 1);
            return;
        }
        break;
    case 3:
        fn_802D6A9C();
        fn_802D79E8((*(u32*)((char*)(arg0)+0x4)), 0, lbl_8054082C, lbl_80540830);
        fn_801F2B7C(arg0, (*(u32*)((char*)(arg0)+0x114)), -1, 6);
        (*(u32*)((char*)(arg0)+0x234)) = (s32) ((*(u32*)((char*)(arg0)+0x234)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x234)) == 0) {
            (*(u32*)((char*)(arg0)+0x230)) = 4;
            return;
        }
        break;
    default:
        temp_r5 = (*(u32*)((char*)(arg0)+0x238));
        if (temp_r5 != NULL) {
            (*(u32*)((char*)(temp_r5)+0xF4)) = (s32) ((*(u32*)((char*)(temp_r5)+0xF4)) | 1);
            (*(u32*)((char*)(temp_r5)+0x24)) = 1;
            (*(u32*)((char*)(arg0)+0x238)) = NULL;
        }
        fn_801F3668(arg0);
        break;
    }
}

/* --- auto_fn_802A7F58_text.s --- */


void fn_801EE434(void *arg0);                                    /* extern */
extern char lbl_804A7FB8;

void *fn_802A7F58(void *arg0, s16 arg1) {
    if (arg0 != NULL) {
        (*(u32*)((char*)(arg0)+0x0)) = (u32)&lbl_804A7FB8;
        if ((u32) (*(u32*)((char*)(arg0)+0x238)) != 0U) {
            fn_801EE434();
        }
        dtor_801F593C(arg0, 0);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_03_802A7FCC_text.s --- */
extern f32 lbl_80540834;
extern f32 lbl_80540838;

void fn_802A7FCC(void *arg0) {
    (*(u32*)((char*)(arg0)+0x60)) = (f32) lbl_80540834;
    (*(u32*)((char*)(arg0)+0x64)) = (f32) lbl_80540834;
    (*(u32*)((char*)(arg0)+0x68)) = (f32) lbl_80540838;
    (*(u32*)((char*)(arg0)+0x6C)) = (f32) lbl_80540838;
    (*(u32*)((char*)(arg0)+0x238)) = 0;
    (*(u32*)((char*)(arg0)+0x230)) = 0;
    (*(u32*)((char*)(arg0)+0x234)) = 0x14;
}

/* --- auto_fn_802A7FFC_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D0D68;










void fn_802A7FFC(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D0D68);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D0D68 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D0D68 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D0D68 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D0D68 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D0D68 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D0D68 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D0D68 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D0D68 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802A8220_text.s --- */


extern char lbl_804A8010;

char **fn_802A8220(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804A8010;
        dtor_801F593C(0, &lbl_804A8010);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_03_802A8280_text.s --- */
void fn_802A8280(void) {

}

/* --- auto_fn_802A8284_text.s --- */
/*
Decompilation failure in function fn_802A8284:

Found bctr instruction at auto_fn_802A8284_text.s line 155, but the corresponding jump table is not provided.

Please include it in the input .s file(s), or in an additional file.

*/

/* --- auto_fn_802A92FC_text.s --- */
void fn_802A92FC(void *arg0) {
    s32 temp_r0;
    s32 temp_r0_2;
    s32 temp_r3;

    (*(u32*)((char*)(arg0)+0x248)) = 0;
    (*(u32*)((char*)(arg0)+0x24C)) = 0;
    (*(u32*)((char*)(arg0)+0x230)) = 0;
    (*(u32*)((char*)(arg0)+0x23C)) = 0;
    (*(u32*)((char*)(arg0)+0x240)) = 0;
    (*(u32*)((char*)(arg0)+0x244)) = (s32) (u8) (*(u32*)((char*)(arg0)+0x90));
    temp_r0 = (*(u32*)((char*)(arg0)+0x244));
    if ((temp_r0 != 3) && (temp_r0 != 0xC) && (((u32(*)())(*(void**)((char*)(unk0)+0x34)))() != 0)) {
        (*(u32*)((char*)(arg0)+0x11C)) = 0;
    }
    (*(u32*)((char*)(arg0)+0x240)) = (s32) (u8) ((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0xCU);
    if ((s32) (*(u32*)((char*)(arg0)+0x240)) == 0) {
        (*(u32*)((char*)(arg0)+0x240)) = 0x100;
    }
    (*(u32*)((char*)(arg0)+0x234)) = 1;
    (*(u32*)((char*)(arg0)+0x238)) = 0;
    temp_r0_2 = (*(u32*)((char*)(arg0)+0x240));
    switch (temp_r0_2) {                            /* irregular */
    case 0x28:
        (*(u32*)((char*)(arg0)+0x238)) = 1;
        break;
    case 0x78:
        (*(u32*)((char*)(arg0)+0x238)) = 2;
        break;
    case 0xC8:
        (*(u32*)((char*)(arg0)+0x238)) = 3;
        break;
    }
    temp_r3 = (*(u32*)((char*)(arg0)+0x244));
    if ((temp_r3 == 2) || (temp_r3 == 4) || ((u32) temp_r3 <= 1U) || ((u32) (temp_r3 - 8) <= 3U) || (temp_r3 == 0xD)) {
        (*(u32*)((char*)(arg0)+0x24C)) = 0x28;
    }
}

/* --- auto_fn_802A9428_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D0E68;










void fn_802A9428(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D0E68);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D0E68 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D0E68 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D0E68 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D0E68 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D0E68 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D0E68 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D0E68 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D0E68 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802A964C_text.s --- */


extern char lbl_804A80A0;

char **fn_802A964C(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804A80A0;
        dtor_801F593C(0, &lbl_804A80A0);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_03_802A96AC_text.s --- */
void fn_802A96AC(void) {

}

/* --- auto_fn_802A96B0_text.s --- */
/*
Decompilation failure in function fn_802A96B0:

Found bctr instruction at auto_fn_802A96B0_text.s line 58, but the corresponding jump table is not provided.

Please include it in the input .s file(s), or in an additional file.

*/

/* --- auto_03_802AA0B8_text.s --- */
extern char lbl_8046C850;

void fn_802AA0B8(void *arg0) {
    (*(u32*)((char*)(arg0)+0x234)) = (s32) ((*(u32*)((char*)(arg0)+0x90)) & 0x1F);
    if ((s32) (*(u32*)((char*)(arg0)+0x234)) != 5) {
        (*(u32*)((char*)(arg0)+0x230)) = 0;
    } else {
        (*(u32*)((char*)(arg0)+0x230)) = 7;
    }
    (*(u32*)((char*)(arg0)+0x244)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> (*(u32*)((char*)&lbl_8046C850+0x0))) & 0x1F);
    (*(u32*)((char*)(arg0)+0x248)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> (*(u32*)((char*)&lbl_8046C850+0x4))) & 0x1F);
    (*(u32*)((char*)(arg0)+0x24C)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> (*(u32*)((char*)&lbl_8046C850+0x8))) & 0x1F);
    (*(u32*)((char*)(arg0)+0x250)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> (*(u32*)((char*)&lbl_8046C850+0xC))) & 0x1F);
}

/* --- auto_fn_802AA140_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D0F68;










void fn_802AA140(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D0F68);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D0F68 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D0F68 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D0F68 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D0F68 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D0F68 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D0F68 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D0F68 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D0F68 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802AA364_text.s --- */


extern char lbl_804A8118;

char **fn_802AA364(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804A8118;
        dtor_801F593C(0, &lbl_804A8118);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_03_802AA3C4_text.s --- */
void fn_802AA3C4(void) {

}

/* --- auto_fn_802AA3C8_text.s --- */
u32 fn_801F0D20(void *, u32);                           /* extern */

void fn_801F35AC(void *arg0);                              /* extern */





extern char lbl_8046C860;
extern void *lbl_8053AAF8;
extern void *lbl_8053AB10;

extern f32 lbl_80540888;
extern f32 lbl_8054088C;

void fn_802AA3C8(void *arg0) {
    f32 sp28;
    f32 sp24;
    f32 sp20;
    f32 sp1C;
    f32 sp18;
    f32 sp14;
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    f32 temp_f1_2;
    f32 temp_f1_3;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f2_3;
    s32 temp_r0;
    void **temp_r3;
    void **temp_r3_2;
    void **temp_r3_3;
    void **temp_r3_4;
    void **temp_r3_5;
    void **temp_r3_6;

    temp_r0 = (*(u32*)((char*)(arg0)+0x230));
    switch (temp_r0) {                              /* irregular */
    case 0:
        if (((u32(*)())(*(void**)((char*)(unk0)+0x34)))() == 1) {
            fn_802A3948(lbl_8053AC98, arg0 + 0xC, 0, (*(u32*)((char*)(arg0)+0x4)), 0x38);
            temp_f2 = (*(u32*)((char*)(arg0)+0x10)) - lbl_80540888;
            temp_f1 = (*(u32*)((char*)(arg0)+0xC));
            sp20 = temp_f1;
            sp24 = temp_f2;
            sp28 = lbl_8054088C;
            fn_802A3948(lbl_8053AC98, &sp20, 0, (*(u32*)((char*)(arg0)+0x4)) + 1, 0x39, temp_f1, temp_f2);
            fn_801F0E34(arg0, 0x30016, 0);
            if ((s32) (*(u32*)((char*)(arg0)+0x4)) < 8) {
                (*(u32*)((char*)(arg0)+0x230)) = 2;
                (*(u32*)((char*)(arg0)+0x240)) = 2;
                return;
            }
            temp_r3 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3))+0x18)))(temp_r3, 0x53434820, &lbl_8046C860, lbl_8053AAF8), 0, 0, 0x40, 0xC0);
            (*(u32*)((char*)(arg0)+0x230)) = 1;
            return;
        }
        return;
    case 1:
        fn_802D6A9C();
        if (fn_802D800C((*(u32*)((char*)(arg0)+0x234))) != 0) {
            fn_801F0D20(arg0, 3);
            (*(u32*)((char*)(arg0)+0x230)) = 4;
            return;
        }
        break;
    case 2:
        (*(u32*)((char*)(arg0)+0x240)) = (s32) ((*(u32*)((char*)(arg0)+0x240)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x240)) == 0) {
            temp_r3_2 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_2))+0x18)))(temp_r3_2, 0x53434820, &lbl_8046C860, lbl_8053AAF8), 0xC0, 0, 0x40, 0xC0);
            fn_801F0E34(arg0, 0x30016, 0);
            (*(u32*)((char*)(arg0)+0x230)) = 3;
            (*(u32*)((char*)(arg0)+0x240)) = 2;
            return;
        }
        break;
    case 3:
        (*(u32*)((char*)(arg0)+0x240)) = (s32) ((*(u32*)((char*)(arg0)+0x240)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x240)) == 0) {
            temp_r3_3 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_3))+0x18)))(temp_r3_3, 0x53434820, &lbl_8046C860, lbl_8053AAF8), 0, 0, 0x40, 0xC0);
            (*(u32*)((char*)(arg0)+0x230)) = 1;
            (*(u32*)((char*)(arg0)+0x240)) = 2;
            return;
        }
        break;
    case 4:
        (*(u32*)((char*)(arg0)+0x240)) = (s32) ((*(u32*)((char*)(arg0)+0x240)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x240)) == 0) {
            if ((s32) (*(u32*)((char*)(arg0)+0x4)) < 8) {
                temp_r3_4 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
                fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_4))+0x18)))(temp_r3_4, 0x53434820, &lbl_8046C860, lbl_8053AAF8), 0xC0, 0, 0x40, 0xC0);
                (*(u32*)((char*)(arg0)+0x230)) = 5;
                (*(u32*)((char*)(arg0)+0x240)) = 2;
            } else {
                fn_802A3884(lbl_8053AC98, arg0 + 0xC, 0, (*(u32*)((char*)(arg0)+0x244)));
                temp_f2_2 = (*(u32*)((char*)(arg0)+0x10)) - lbl_80540888;
                temp_f1_2 = (*(u32*)((char*)(arg0)+0xC));
                sp14 = temp_f1_2;
                sp18 = temp_f2_2;
                sp1C = lbl_8054088C;
                fn_802A3884(lbl_8053AC98, &sp14, 0, (*(u32*)((char*)(arg0)+0x4)) + 1, 0U, temp_f1_2, temp_f2_2);
                temp_r3_5 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
                fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_5))+0x18)))(temp_r3_5, 0x53434820, &lbl_8046C860, lbl_8053AAF8), 0x180, 0, 0x40, 0xC0);
                if ((s32) (*(u32*)((char*)(arg0)+0x23C)) == 0) {
                    fn_801F35AC(arg0);
                } else {
                    (*(u32*)((char*)(arg0)+0x11C)) = 0;
                }
            }
            fn_801F0E34(arg0, 0x30015, 0);
            return;
        }
        break;
    case 5:
        (*(u32*)((char*)(arg0)+0x240)) = (s32) ((*(u32*)((char*)(arg0)+0x240)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x240)) == 0) {
            fn_802A3884(lbl_8053AC98, arg0 + 0xC, 0, (u16) (*(u32*)((char*)(arg0)+0x4)), (*(u32*)((char*)(arg0)+0x244)));
            temp_f2_3 = (*(u32*)((char*)(arg0)+0x10)) - lbl_80540888;
            temp_f1_3 = (*(u32*)((char*)(arg0)+0xC));
            sp8 = temp_f1_3;
            spC = temp_f2_3;
            sp10 = lbl_8054088C;
            fn_802A3884(lbl_8053AC98, &sp8, 0, (*(u32*)((char*)(arg0)+0x4)) + 1, 0U, temp_f1_3, temp_f2_3);
            temp_r3_6 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_6))+0x18)))(temp_r3_6, 0x53434820, &lbl_8046C860, lbl_8053AAF8), 0x180, 0, 0x40, 0xC0);
            if ((s32) (*(u32*)((char*)(arg0)+0x23C)) == 0) {
                fn_801F35AC(arg0);
                return;
            }
            (*(u32*)((char*)(arg0)+0x11C)) = 0;
        }
        break;
    }
}

/* --- auto_fn_802AA868_text.s --- */







extern void *lbl_8053AAF8;
extern void *lbl_8053AB10;




void fn_802AA868(void *arg0) {
    f32 sp10;
    f32 spC;
    f32 sp8;
    f32 temp_f1;
    f32 temp_f2;
    void **temp_r3;
    void **temp_r3_2;

    (*(u32*)((char*)(arg0)+0x234)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x16U) & 0x1F);
    (*(u32*)((char*)(arg0)+0x23C)) = (s32) (((u32) (*(u32*)((char*)(arg0)+0x90)) >> 0x11U) & 0x1F);
    (*(u32*)((char*)(arg0)+0x230)) = 0;
    (*(u32*)((char*)(arg0)+0x244)) = fn_802F9908((*(u32*)((char*)(lbl_8053AB10)+0x20)), (*(u32*)((char*)(arg0)+0x4)), fn_80226AE0(arg0 + 0xC, (*(u32*)((char*)(arg0)+0x4))), lbl_8053AB10);
    fn_802D6A9C();
    if (fn_802D800C((*(u32*)((char*)(arg0)+0x234))) != 0) {
        fn_802A3884(lbl_8053AC98, arg0 + 0xC, 0, (*(u32*)((char*)(arg0)+0x4)), (*(u32*)((char*)(arg0)+0x244)));
        temp_f2 = (*(u32*)((char*)(arg0)+0x10)) - lbl_80540888;
        temp_f1 = (*(u32*)((char*)(arg0)+0xC));
        sp8 = temp_f1;
        spC = temp_f2;
        sp10 = lbl_8054088C;
        fn_802A3884(lbl_8053AC98, &sp8, 0, (*(u32*)((char*)(arg0)+0x4)) + 1, 0U, temp_f1, temp_f2);
        temp_r3 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
        fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3))+0x18)))(temp_r3, 0x53434820, &lbl_8046C860, lbl_8053AAF8), 0x180, 0, 0x40, 0xC0);
        (*(u32*)((char*)(arg0)+0x11C)) = 0;
        return;
    }
    temp_r3_2 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
    fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_2))+0x18)))(temp_r3_2, 0x53434820, &lbl_8046C860, lbl_8053AAF8), 0, 0, 0x40, 0xC0);
}

/* --- auto_fn_802AA9D8_text.s --- */
u32 __register_global_object(char *, char *, char *);          /* extern */



















extern char lbl_804D1068;










void fn_802AA9D8(void) {
    if ((s8) lbl_8053A2AC == 0) {
        fn_80028974(&lbl_804B21AC);
        __register_global_object(&lbl_804B21AC, &fn_80021D0C, &lbl_804D1068);
        lbl_8053A2AC = 1;
    }
    if ((s8) lbl_8053A2AD == 0) {
        fn_80028974(&lbl_804B21BC);
        __register_global_object(&lbl_804B21BC, &fn_80021CB8, &lbl_804D1068 + 0xC);
        lbl_8053A2AD = 1;
    }
    if ((s8) lbl_8053A2AE == 0) {
        fn_80028974(&lbl_804B21CC);
        __register_global_object(&lbl_804B21CC, &fn_80021C64, &lbl_804D1068 + 0x18);
        lbl_8053A2AE = 1;
    }
    if ((s8) lbl_8053A2AF == 0) {
        fn_80028974(&lbl_804B21DC);
        __register_global_object(&lbl_804B21DC, &fn_80021C10, &lbl_804D1068 + 0x24);
        lbl_8053A2AF = 1;
    }
    if ((s8) lbl_8053A2B0 == 0) {
        fn_80028974(&lbl_804B21EC);
        __register_global_object(&lbl_804B21EC, &fn_80021BBC, &lbl_804D1068 + 0x30);
        lbl_8053A2B0 = 1;
    }
    if ((s8) lbl_8053A2B1 == 0) {
        fn_80028974(&lbl_804B21FC);
        __register_global_object(&lbl_804B21FC, &fn_80021B68, &lbl_804D1068 + 0x3C);
        lbl_8053A2B1 = 1;
    }
    if ((s8) lbl_8053A2B2 == 0) {
        fn_80028974(&lbl_804B220C);
        __register_global_object(&lbl_804B220C, &fn_80021B14, &lbl_804D1068 + 0x48);
        lbl_8053A2B2 = 1;
    }
    if ((s8) lbl_8053A2B3 == 0) {
        fn_80028974(&lbl_804B221C);
        __register_global_object(&lbl_804B221C, &fn_80021AC0, &lbl_804D1068 + 0x54);
        lbl_8053A2B3 = 1;
    }
    if ((s8) lbl_8053A2B4 == 0) {
        fn_80028974(&lbl_804B222C);
        __register_global_object(&lbl_804B222C, &fn_80021A6C, &lbl_804D1068 + 0x60);
        lbl_8053A2B4 = 1;
    }
}

/* --- auto_fn_802AABFC_text.s --- */


extern char lbl_804A8170;

char **fn_802AABFC(char **arg0, s16 arg1) {
    if (arg0 != NULL) {
        *arg0 = &lbl_804A8170;
        dtor_801F593C(0, &lbl_804A8170);
        if (arg1 > 0) {
            dtor_80084580(arg0);
        }
    }
    return arg0;
}

/* --- auto_03_802AAC5C_text.s --- */
void fn_802AAC5C(void) {

}

/* --- auto_fn_802AAC60_text.s --- */


void *fn_801F856C();                                /* extern */

u32 fn_802D7920(u32);                                   /* extern */

extern char lbl_8046C878;
extern void *lbl_8053AAF8;
extern void *lbl_8053AB10;

void fn_802AAC60(void *arg0) {
    s32 temp_r0;
    s32 temp_r0_2;
    void **temp_r3;
    void **temp_r3_2;
    void **temp_r3_3;

    temp_r0 = (*(u32*)((char*)(arg0)+0x230));
    switch (temp_r0) {                              /* switch 1; irregular */
    case 0:                                         /* switch 1 */
        (*(u32*)((char*)(arg0)+0x238)) = (s32) ((*(u32*)((char*)(arg0)+0x238)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x238)) == 0) {
            temp_r3 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3))+0x18)))(temp_r3, 0x53434820, &lbl_8046C878, lbl_8053AAF8), 0, 0, 0x40, 0xC0);
            (*(u32*)((char*)(arg0)+0x230)) = 1;
            fn_801F0E34(arg0, 0x30015, 0);
        }
        /* fallthrough */
    case 1:                                         /* switch 1 */
        temp_r0_2 = (*(u32*)((char*)(arg0)+0x234));
        switch (temp_r0_2) {                        /* switch 2; irregular */
        case 0:                                     /* switch 2 */
            if (((u32(*)())(*(void**)((char*)(unk0)+0x34)))(arg0) != 0) {
                fn_801F0D20(arg0, 3);
                (*(u32*)((char*)(arg0)+0x230)) = 2;
                (*(u32*)((char*)(arg0)+0x238)) = 8;
                return;
            }
            return;
        default:                                    /* switch 2 */
        case 1:                                     /* switch 2 */
            if ((u8) fn_801F856C(*(u32*)((char*)(())+0x305C)) == 1) {
                fn_801F0D20(arg0, 3);
                (*(u32*)((char*)(arg0)+0x238)) = 8;
                (*(u32*)((char*)(arg0)+0x230)) = 2;
                return;
            }
            break;
        }
        break;
    case 2:                                         /* switch 1 */
        (*(u32*)((char*)(arg0)+0x238)) = (s32) ((*(u32*)((char*)(arg0)+0x238)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x238)) == 0) {
            temp_r3_2 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_2))+0x18)))(temp_r3_2, 0x53434820, &lbl_8046C878, lbl_8053AAF8), 0xC0, 0, 0x40, 0xC0);
            (*(u32*)((char*)(arg0)+0x230)) = 3;
            fn_801F0E34(arg0, 0x30016, 0);
            (*(u32*)((char*)(arg0)+0x238)) = 2;
            return;
        }
        break;
    case 3:                                         /* switch 1 */
        (*(u32*)((char*)(arg0)+0x238)) = (s32) ((*(u32*)((char*)(arg0)+0x238)) - 1);
        if ((s32) (*(u32*)((char*)(arg0)+0x238)) == 0) {
            temp_r3_3 = (*(u32*)((char*)(lbl_8053AAF8)+0xA4));
            fn_802FA160((*(u32*)((char*)(lbl_8053AB10)+0x20)), ((u32(*)())(*(void**)((char*)((*temp_r3_3))+0x18)))(temp_r3_3, 0x53434820, &lbl_8046C878, lbl_8053AAF8), 0x180, 0, 0x40, 0xC0);
            fn_802D6A9C();
            fn_802D7920(0);
            (*(u32*)((char*)(arg0)+0x11C)) = 0;
            return;
        }
        break;
    default:                                        /* switch 1 */
        (*(u32*)((char*)(arg0)+0x11C)) = 0;
        break;
    }
}

